### ISSUE TITLE
[HELP] Does server automatically send RPC about device removal/renaming

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard-gateway#1010]
**Describe the issue**
1. Does server automatically send RPC about device removal/renaming?

2. If no, where I can get ID of gateway to manually send that RPC?
I know that once server creates device (after gateway has sent `connect` message) it also create `Created` relation between gateway and device. But when device has been deleted, the relation automatically has been deleted as well, so I cannot get ID of gateway through `Created` relation.

Only thing I got on server after device removal is `lastConnectedGateway` (see device's `additionalInfo`) where ID is. Fortunately, this covers our scenario but not all

**Comment by samson0v** [comment]
Hi @devaskim, server automatically send RPC about device removal/renaming.
