### ISSUE TITLE
[HELP]|ERROR| - [mqtt_connector.py] - mqtt_connector - __connect - 285 - [Errno 111] Connection refused

### ISSUE THREAD

**Issue by S1L3NTANG3L** [thingsboard/thingsboard-gateway#1020]
**Describe the issue**
Keep getting this error even though the connection is open and running. Have a raspi using the same connection to send data to thingsboard.

**Configuration** (Attach your configuration file)
[https://logpaste.com/Uwm1bz76](https://logpaste.com/Uwm1bz76)
[https://logpaste.com/Gwculy3u](https://logpaste.com/Gwculy3u)
[https://logpaste.com/QgfGZyq1](https://logpaste.com/QgfGZyq1)
[https://logpaste.com/10ed32M4](https://logpaste.com/10ed32M4)

**Connector name (If you need help with some connector/converter):**
[e.g. MQTT Connector]

**Versions (please complete the following information):**
 - OS: Unraid 6.11.3
 - Thingsboard IoT Gateway version : latest : 3.2
 - Python version: 3.9

**Comment by S1L3NTANG3L** [comment]
Also trying to run both dockers on the same machine is that a problem?

**Comment by samson0v** [comment]
Hi @S1L3NTANG3L, please, send the MQTT Connector configuration file.

**Comment by samson0v** [comment]
Hi @S1L3NTANG3L, any updates?

**Comment by S1L3NTANG3L** [comment]
Hi I think I've found the issue, still working one the mqtt server so I'll keep you updated. @samson0v Can you maybe send me a sql database creation script that has the right layout needed by the gateway(Have and api I want to put between the gateway and a few devices with weird json structures) Regards

**Comment by hao-prog** [comment]
> Hi I think I've found the issue, still working one the mqtt server so I'll keep you updated. @samson0v Can you maybe send me a sql database creation script that has the right layout needed by the gateway(Have an api I want to put between the gateway and a few devices with weird json structures) Regards Edit: Sorry for the late reply got distracted by some other high priority projects

Hi, what's your solution. I'm having the same issue.

**Comment by hao-prog** [comment]
My configuration:
tb_gateway.yaml: https://logpaste.com/Gn2sLbVY
mqtt.son: https://logpaste.com/PnmJ8h82

**Comment by S1L3NTANG3L** [comment]
@samson0v Quick follow up was able to fix the mqtt broker issues but can't seem to get postgres talking to the gateway? ""2022-12-29 13:19:07" - |ERROR| - [odbc_connector.py] - odbc_connector - __init_connection - 328 - [ODBC Connector] Failed to connect to database: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'psqlODBC' : file not found (0) (SQLDriverConnect)")"

**Comment by S1L3NTANG3L** [comment]
@samson0v Same error with the postgresql -> 
""2022-12-29 13:31:58" - |INFO| - [odbc_connector.py] - odbc_connector - run - 174 - [ODBC Connector] Will reconnect to database in 60 second(s)"

""2022-12-29 13:32:58" - |ERROR| - [odbc_connector.py] - odbc_connector - __init_connection - 328 - [ODBC Connector] Failed to connect to database: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'PostgreSQL' : file not found (0) (SQLDriverConnect)")"

**Comment by samson0v** [comment]
@S1L3NTANG3L, it is mean that you incorrectly configure the driver name.
Make sure that you have installed unixODBC (https://github.com/mkleehammer/pyodbc/wiki/Install)
Also, you can configure the driver name in the `odbc.ini` file.
For Mac OS configuration files are located in:
`/opt/homebrew/etc/odbc.ini`
`opt/homebrew/etc/odbcinst.ini`

**Comment by S1L3NTANG3L** [comment]
Hi I have unixodbc installed within the container just need to figure out where the ini file is

**Comment by samson0v** [comment]
@S1L3NTANG3L try to google it

**Comment by S1L3NTANG3L** [comment]
Found the file but its empty

**Comment by S1L3NTANG3L** [comment]
Okay I followed this: https://datacadamia.com/odbc/unix/odbcinst.ini is it correct?

**Comment by samson0v** [comment]
@S1L3NTANG3L, yes

**Comment by S1L3NTANG3L** [comment]
Keep running insto this error though: 
""2022-12-29 14:27:01" - |INFO| - [odbc_connector.py] - odbc_connector - run - 174 - [ODBC Connector] Will reconnect to database in 60 second(s)"

""2022-12-29 14:27:01" - |ERROR| - [odbc_connector.py] - odbc_connector - __init_connection - 328 - [ODBC Connector] Failed to connect to database: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/usr/lib/psqlodbcw.so' : file not found (0) (SQLDriverConnect)")"

**Comment by S1L3NTANG3L** [comment]
Used apt-get install odbc-postgresql

**Comment by S1L3NTANG3L** [comment]
Unicode or Ansi?

**Comment by S1L3NTANG3L** [comment]
> Unicode or Ansi?

ANSI Works, new error XD
""2022-12-29 14:44:05" - |ERROR| - [odbc_connector.py] - odbc_connector - __init_iterator - 382 - [ODBC Connector] Failed to init iterator from database: ('42P01', '[42P01] ERROR: relation "ts_kv" does not exist;\nError while executing the query (1) (SQLExecDirectW)')"

**Comment by S1L3NTANG3L** [comment]
ts_kv in the odbc.json is the issue does it refer to the timeseries table?

**Comment by S1L3NTANG3L** [comment]
Is entity_id => device_id ?

**Comment by S1L3NTANG3L** [comment]
Fixing those two deviations between the sql creation script and the odbc.json and setting the driver to PostgreSQL ANSI fixed all my issues.
""2022-12-29 14:50:52" - |INFO| - [odbc_connector.py] - odbc_connector - __poll - 231 - [ODBC Connector] Polling iteration finished. Processed rows: current 0, total 0"

**Comment by samson0v** [comment]
> ts_kv in the odbc.json is the issue does it refer to the timeseries table?



> Is entity_id => device_id ?

The answers to these questions are in the [official documentation](https://thingsboard.io/docs/iot-gateway/config/odbc/).

**Comment by samson0v** [comment]
> Fixing those two deviations between the sql creation script and the odbc.json and setting the driver to PostgreSQL ANSI fixed all my issues. ""2022-12-29 14:50:52" - |INFO| - [odbc_connector.py] - odbc_connector - __poll - 231 - [ODBC Connector] Polling iteration finished. Processed rows: current 0, total 0"

Ok, so can we close the issue?

**Comment by S1L3NTANG3L** [comment]
Yeah, I'll open a new issue if I run into any other issues, Thanks for the help
