### ISSUE TITLE
[BUG] Unexpected behaviour when writing on variables with variables with OPC-UA

### ISSUE THREAD

**Issue by SimoneG97** [thingsboard/thingsboard-gateway#1021]
1. When writing an a mapped variable under a variable, the device doesn't get updated unless the deviceNodePattern points directly at that variable containing a variable
2. In the attributes_updates section, attributeOnDevice doesn't work if defined with namespace + node identifier, only works with node path.
Is this normal?

**Connector name (If bug in the some connector):**
OPC-UA Connector

**Error traceback (If available):**
No traceback available, even with all loggers set to DEBUG

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04
 - Thingsboard IoT Gateway version: 2 weeks old from this day (I had not found an easy way to determine the gateway version, using docker)
 - Python version: 3.8.10

Configuration example (using Prosys):
```
{
	"server": {
		"name": "OPC-UA Prosys Server",
		"url": "192.2.90.2:53530",
		"timeoutInMillis": 5000,
		"scanPeriodInMillis": 5000,
		"disableSubscriptions": true,
		"subCheckPeriodInMillis": 1000,
		"showMap": true,
		"security": "None",
		"identity": {
			"type": "anonymous"
		},
		"mapping": [
			{
				"deviceNodePattern": "${ns=3;s=85/0:Simulation}",
				"deviceNamePattern": "Prosys",
				"attributes": [],
				"timeseries": [
					{
						"key": "Sawtooth",
						"path": "${Root\\.Objects\\.Simulation\\.Sawtooth}"
					}
				],
				"rpc_methods": [],
				"attributes_updates": [
					{
						"attributeOnThingsBoard": "StrTest",
						"attributeOnDevice": "Root\\.Objects\\.Simulation\\.StringTest"
					},
					{
						"attributeOnThingsBoard": "StrTest2",
						"attributeOnDevice": "Root\\.Objects\\.Simulation\\.TOBJ\\.Param"
					},
					{
						"attributeOnThingsBoard": "V1",
						"attributeOnDevice": "Root\\.Objects\\.Simulation\\.TOBJ\\.TOBJ2\\.TOBJ3\\.V1"
					},
					{
						"attributeOnThingsBoard": "V2",
						"attributeOnDevice": "Root\\.Objects\\.Simulation\\.TOBJ\\.TOBJ2\\.F1\\.V2"
					},
					{
						"attributeOnThingsBoard": "SubVar",
						"attributeOnDevice": "Root\\.Objects\\.Simulation\\.TOBJ\\.Param\\.SubVar"
					},
					{
						"attributeOnThingsBoard": "V4",
						"attributeOnDevice": "Root\\.Objects\\.Simulation\\.SimulationChild\\.SB1\\.V4"
					}
				]
			},
			{
				"deviceNodePattern": "${ns=3;i=1009}",
				"deviceNamePattern": "Prosys var with vars",
				"attributes": [],
				"timeseries": [
					{
						"key": "TS",
						"path": "${ns=3;i=1019}"
					}
				],
				"rpc_methods": [],
				"attributes_updates": [
					{
						"attributeOnThingsBoard": "SubVar",
						"attributeOnDevice": "Root\\.Objects\\.Simulation\\.TOBJ\\.Param\\.SubVar"
					}
				]
			}
		]
	}
}
```

Behaviour description:
1. This creates 2 devices on thingsboard:
- `Prosys` which has deviceNodePattern pointing to the `Simulation` folder
- `Prosys var with vars` which has deviceNodePattern pointing to the variable `Param`
Both have the exact same variable `SubVar`.
3. When creating/editing the shared attribute `SubVar` in the `Prosys` device, the value _does not_ change on Prosys.
4. When creating/editing the shared attribute `SubVar` in the `Prosys var with vars` device, the value _does_ change on Prosys.
I had this problem on other PLCs too, not just simulated ones.
Here is a screenshot of the node structure of Prosys
![immagine](https://user-images.githubusercontent.com/38068023/206226242-a8c7ba2d-0e28-4ef3-b74e-15d118ff3b3a.png)

**Comment by samson0v** [comment]
Hi @SimoneG97, I reproduce your Prosys Server config and OPC-UA Connector config and have the following result:
<img width="877" alt="зображення" src="https://user-images.githubusercontent.com/43861229/208860835-4bfb194b-8c8f-4b43-a628-ea018aaad38a.png">
<img width="791" alt="зображення" src="https://user-images.githubusercontent.com/43861229/208860880-09439429-dca3-45bd-aff6-0e83c13ffc2b.png">
<img width="1381" alt="зображення" src="https://user-images.githubusercontent.com/43861229/208860922-ed06616b-c07f-44b0-9b6c-b9af166dd215.png">

So it seems that Prosys doesn't allow write value to this variable type.

**Comment by SimoneG97** [comment]
I think you haven't set the variable as writable since it is returning you `BadNotWritable`, I only see AccessLevel as `[CurrentRead, HistoryRead]` in the screenshot you provided.  
It also needs `[CurrentWrite]` as I have shown in my previous screenshot.
Just in case I forgot to mention, I was able to reproduce this also on real OPCUA PLCs, so this means it shouldn't be Prosys related.

**Comment by samson0v** [comment]
@SimoneG97 ok, I retest and in the result, I can write the value (OPC-UA Connector config is the same as above).
<img width="900" alt="зображення" src="https://user-images.githubusercontent.com/43861229/209089026-70390bea-70c4-4525-81c6-b8d523cedc8c.png">
<img width="889" alt="зображення" src="https://user-images.githubusercontent.com/43861229/209089072-7ebb87f5-12bd-44d7-acad-7fae3946cce5.png">
<img width="870" alt="зображення" src="https://user-images.githubusercontent.com/43861229/209089119-5740223f-56f5-4437-99bd-c1a96cfe8d03.png">

**Comment by SimoneG97** [comment]
This behaviour is working ok on my end too (Variable inside an object).
Now try writing a value on a variable inside a variable.
Like this:
![immagine](https://user-images.githubusercontent.com/38068023/209101036-910179a3-e4a1-4c8b-847f-cf13e60f3a40.png)
Writing in `Test` doesn't work in the different tests I've made.

**Comment by samson0v** [comment]
@SimoneG97, I found a bug, fixing it...
