### ISSUE TITLE
[HELP] Can I pause the Connector via RPC?

### ISSUE THREAD

**Issue by psxbox** [thingsboard/thingsboard-gateway#1037]
Can I pause the Connector via RPC?

**Versions (please complete the following information):**
 - OS: [Docker image]
 - Thingsboard IoT Gateway version [3.2]

**Comment by samson0v** [comment]
Hi @psxbox, no

**Comment by psxbox** [comment]
If the connector exits from the run method, does the gateway restart it? Thanks

**Comment by samson0v** [comment]
> If the connector exits from the run method, does the gateway restart it? Thanks

@psxbox, no
