### ISSUE TITLE
[HELP] Failed to process database row: 'type'"

### ISSUE THREAD

**Issue by S1L3NTANG3L** [thingsboard/thingsboard-gateway#1042]
**Describe the issue**
```
""2023-01-10 15:09:14" - |INFO| - [odbc_connector.py] - odbc_connector - __poll - 231 - [ODBC Connector] Polling iteration finished. Processed rows: current 4, total 2628"

""2023-01-10 15:09:14" - |WARNING| - [odbc_connector.py] - odbc_connector - __process_row - 264 - [ODBC Connector] Failed to process database row: 'type'"

```
**Configuration** (Attach your configuration file)

[odbc.txt](https://github.com/thingsboard/thingsboard-gateway/files/10383923/odbc.txt)
[tb_gateway.txt](https://github.com/thingsboard/thingsboard-gateway/files/10383924/tb_gateway.txt)

**Connector name (If you need help with some connector/converter):**
[e.g. MQTT Connector]
ODBC

**Error traceback (If it was raised):**
```
'deviceName'
Traceback (most recent call last):
  File "<input>", line 2, in <module>
KeyError: 'deviceName'
```

**Versions (please complete the following information):**
 - OS: Unraid
 - Thingsboard IoT Gateway version Docker 3.2
 - Python version3.9

**Comment by samson0v** [comment]
Hi @S1L3NTANG3L, you have to configure deviceType as in the example below:
<img width="275" alt="зображення" src="https://user-images.githubusercontent.com/43861229/211622438-3cfaeb62-09e9-43c6-bf83-2ee01649a7f3.png">
