### ISSUE TITLE
Get Data from Webservice SOAP (WSDL)

### ISSUE THREAD

**Issue by mamadouly12** [thingsboard/thingsboard-gateway#1046]
**Describe the issue**
We would like get datas using soap (wsdl file) as protocol of integration. But we are not sure how to get there.

**Comment by samson0v** [comment]
Hi @mamadouly12, Gateway doesn't support CoAP protocol, so you can use [ThingsBoard CoAP Integration](https://thingsboard.io/docs/user-guide/integrations/coap/).

**Comment by mamadouly12** [comment]
Hi @samson0v : Thank you for your feedback, 
How do we call and consume the data from the wsdl file?

**Comment by samson0v** [comment]
@mamadouly12 please, make a request to our support team
https://thingsboard.io/docs/contact-us/
