### ISSUE TITLE
[HELP]How to get telemetry data through rule chain node，I tried, but it didn't work。

### ISSUE THREAD

**Issue by a-jiang** [thingsboard/thingsboard-gateway#1060]
**Describe the issue**
1、 message
![image](https://user-images.githubusercontent.com/9330004/219577997-4a220eac-5b15-4f76-9f6d-612e973bb22b.png)
2、my config
![image](https://user-images.githubusercontent.com/9330004/219578433-ce6addaf-ff1e-4512-abd7-20899afd8a34.png)
3、rule chains
![image](https://user-images.githubusercontent.com/9330004/219579646-f2a89d5c-03d2-4fb5-9b7d-2b36923eae4d.png)
4、the script
![image](https://user-images.githubusercontent.com/9330004/219579491-ec463a3f-1ee8-45e3-bec6-3383194e39d5.png)

5、telemetry
![image](https://user-images.githubusercontent.com/9330004/219580491-489c5a44-e05a-41c6-8ec5-81ed72ec57cc.png)

**Connector name (If you need help with some connector/converter):**
[e.g. MQTT Connector]

**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Thingsboard IoT Gateway version [e.g. 3.0.1]
 - Python version[e.g. 3.9]

**Comment by imbeacon** [comment]
Hi @a-jiang ,

You can enable debug on rule node, save rule chain, wait for the data and open **Events** tab for this rule-node in rule chain, it will give you ability to see the incoming messages and then build your script. [Debugging](https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#debugging)

**Comment by a-jiang** [comment]
> Hi @a-jiang ,
> 
> You can enable debug on rule node, save rule chain, wait for the data and open **Events** tab for this rule-node in rule chain, it will give you ability to see the incoming messages and then build your script. [Debugging](https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#debugging)

Thank you very much, I found out that the data I got is not the raw data I want through debug mode.
![image](https://user-images.githubusercontent.com/9330004/219598898-a0b5cc39-db1c-4635-b0d6-a561bea14f7b.png)
**my raw data like this**
`{'body': {'serviceId': 'analog', 'nodeId': 'kd_huawei_pvi1', 'serviceProperties': {'PV_DC': '60.44', 'PV_TC': '18048.98', 'ERROR_CODE': '0.00', 'PV_ST': '1676621429.00', 'PV_T': '34.00', 'PV_EF': '98.24', 'PV_FQ': '50.03', 'PV_PF': '1.00', 'PV_OQP': '-0.02', 'PV_OAP': '6.34', 'PV_HP': '24.62', 'PV_UIC': '9.04', 'PV_UIB': '9.06', 'PV_UIA': '9.05', 'PV_UVC': '232.40', 'PV_UVB': '234.00', 'PV_UVA': '232.50', 'PV_CA': '401.10', 'PV_BC': '402.60', 'PV_AB': '402.10', 'PV_IP': '6.45', 'PV4_A': '2.78', 'PV4_V': '577.20', 'PV3_A': '2.74', 'PV3_V': '574.60', 'PV2_A': '2.84', 'PV2_V': '577.10', 'PV1_A': '2.78', 'PV1_V': '581.30', 'warn2': '0.00', 'warn1': '0.00', 'warn': '0.00', 'staus3': '7.00', 'staus2': '0.00', 'status': '6.00'}}, 'timestamp': '2016-09-05T17:53:22Z'}`

**Comment by imbeacon** [comment]
Hi @a-jiang ,

It is a statistic data, you should see there different messages, for devices. This message is just a gateway statistic data.

**Comment by a-jiang** [comment]
> Hi @a-jiang ,
> 
> It is a statistic data, you should see there different messages, for devices. This message is just a gateway statistic data.
 thank you for your answer. I got an error ，See the logs below
![image](https://user-images.githubusercontent.com/9330004/220516388-ef5aeb17-fbe7-41db-99c4-9f1f631358c5.png)
below is the output data which from coustom
`{'body': {'serviceId': 'analog', 'nodeId': 'kd_huawei_pvi1', 'serviceProperties': {'PV_DC': '60.44', 'PV_TC': '18048.98', 'ERROR_CODE': '0.00', 'PV_ST': '1676621429.00', 'PV_T': '34.00', 'PV_EF': '98.24', 'PV_FQ': '50.03', 'PV_PF': '1.00', 'PV_OQP': '-0.02', 'PV_OAP': '6.34', 'PV_HP': '24.62', 'PV_UIC': '9.04', 'PV_UIB': '9.06', 'PV_UIA': '9.05', 'PV_UVC': '232.40', 'PV_UVB': '234.00', 'PV_UVA': '232.50', 'PV_CA': '401.10', 'PV_BC': '402.60', 'PV_AB': '402.10', 'PV_IP': '6.45', 'PV4_A': '2.78', 'PV4_V': '577.20', 'PV3_A': '2.74', 'PV3_V': '574.60', 'PV2_A': '2.84', 'PV2_V': '577.10', 'PV1_A': '2.78', 'PV1_V': '581.30', 'warn2': '0.00', 'warn1': '0.00', 'warn': '0.00', 'staus3': '7.00', 'staus2': '0.00', 'status': '6.00'}}, 'timestamp': '2016-09-05T17:53:22Z'}`

**how can i solve this error,please help me,thank you very much.**

**Comment by imbeacon** [comment]
Hi,

Timestamps supports only unix timestamp, not a date string.
Ability to use date string as timestamp will be added after implementing functionality, described in https://github.com/thingsboard/thingsboard-gateway/issues/1256
