### ISSUE TITLE
[BUG] can't recieve shared attributes or RPC message any more after MQTT reconnected

### ISSUE THREAD

**Issue by allenlincg** [thingsboard/thingsboard-gateway#1061]
**Describe the bug**
It can't recieve shared attributes or RPC message any more after MQTT reconnected.
I send the share attributes from the Thingsboard UI for the shared attributes of device. And I send the RPC message from the control widget of Thingsboard Dashboard.

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04
 - Thingsboard IoT Gateway version 3.1
 - Python version 3.8

**Comment by Zerolee001** [comment]
For this issue, I modified0 like this： 

1. in tb_device_mqtt.py， I add a fucntion called:

`    def gw_connect_device_alive(self, device_name, device_type):
        info = self._client.publish(topic=GATEWAY_MAIN_TOPIC + "connect", payload=dumps({"device": device_name, "type": device_type}),
                                    qos=self.quality_of_service)
        print("gw_connect_device_alive:", device_name)
        return info`

3. call gw_connect_device_alive in tb_gateway_service.py
`
            while not self.stopped:
                #print("tb_gateway_service still alive !!!")
                cur_time = time() * 1000
                if not self.tb_client.is_connected() and self.__subscribed_to_rpc_topics:
                    self.__subscribed_to_rpc_topics = False
                if self.tb_client.is_connected() and not self.__subscribed_to_rpc_topics:
                    for device in self.__saved_devices:
                        #print("tb_gateway_service call add_device ~~", self.__saved_devices[device], device)
                        self.add_device(device, {"connector": self.__saved_devices[device]["connector"]},
                                        device_type=self.__saved_devices[device]["device_type"])

                        print("self.tb_client.publish ")
                        **self.tb_client.client.gw_connect_device_alive(device, self.__saved_devices[device]["device_type"])**
`

Is this a correct way to keep device alive in service side, so that service can sent shared attributes or rpc command to iot gateway at anytime.?
