### ISSUE TITLE
[HELP] I need to convert a string with data into a telemetry series

### ISSUE THREAD

**Issue by rungg12** [thingsboard/thingsboard-gateway#1068]
A sensor sends temperature, humidity, ... in this format:
	
{'motion': 7.0, 'temperature': 22.5, 'soundPeak': 84.0, 'humidity': 35.0, 'vdd': 3574.0, 'light': 1040.0, 'soundAvg': 47.0}

and the goal would be to see the different keys in Telemetry.

My actual rulechain looks like this:

`if (!('object' in msg))
    return { msg: msg, metadata: metadata,  msgType: msgType };
    
var data = JSON.parse(msg.object);

var newData = {};
var mappings = {
    "motion" : { 'name': 'Bewegung', 'divider': 1 },
    "temperature" : { 'name': 'Temperatur', 'divider': 1 },
    "humidity" : { 'name': 'Luftfeuchte', 'divider': 1 },
    "soundAvg" : { 'name': 'Lautstaerke Durchschnitt', 'divider': 1},
    "light" : { 'name': 'Licht', 'divider': 1 },
    "vdd" : { 'name': 'Batterie', 'divider': 1 },
    "soundPeak" : { 'name': 'Lautstaerke max', 'divider': 1 },

};
for (var i = 0; i < data.length; ++i) {
    var shortName = data[i].id.substr(data[i].id.lastIndexOf('.') + 1); 
    var mappingRule = mappings[shortName];
    newData[mappingRule.name];
}

return {
msg: newData ,
metadata: metadata,
msgType: msgType
};`

How must the rulechain look like?

**Comment by samson0v** [comment]
Hi @rungg12, if you are not using Gateway, I think that it is better to create an issue in the ThingsBoard [repo](https://github.com/thingsboard/thingsboard).
