### ISSUE TITLE
Attribute failed to update after OPC-UA Server restarts

### ISSUE THREAD

**Issue by shaunysj** [thingsboard/thingsboard-gateway#107]
Hi,

I am facing this problem where device attribute failed to update after kepServerEX OPC-UA Server restarts.

Im using thingsboard 2.1.0 and tb-gateway 2.0.4

Steps taken:
1.  Create a OPC-UA device gateway and copied the access token to "/etc/tb-gateway/conf/tb-gateway.yml"
2. Added a new extension. Here is the configuration file
`[{"id":"M580","type":"OPC UA","configuration":{"servers":[{"applicationName":"Thingsboard OPC-UA client","applicationUri":"","host":"BMSServerDev","port":49320,"scanPeriodInSeconds":10,"timeoutInMillis":5000,"security":"Basic128Rsa15","identity":{"type":"anonymous"},"keystore":{"type":"PKCS12","location":"example.pfx","password":"secret","alias":"gateway","keyPassword":"secret","fileContent":"MIIKIgIBAzCCCdwGCSqGSIb3DQEHAaCCCc0EggnJMIIJxTCCBWoGCSqGSIb3DQEHAaCCBVsEggVXMIIFUzCCBU8GCyqGSIb3DQEMCgECoIIE+jCCBPYwKAYKKoZIhvcNAQwBAzAaBBTBjlJoN3UVdEU9BnUHdWaUob11AwICBAAEggTIZ3WuZbOvZDX8zjfZuTw0fReCq6UNbKwXI6MNfJiI44eer4kK8Rz6Uqre0sN0eIE51J1SJL2+VzrfJkYBLc2uQMYYOJvUycZeXLltX2G2mKlw0jqGO/o3fVOyE9YD0BQ5kWLUEf+/TaWTifrD6vE3v/W4EuQVOvG916B2PidfGT0pRCykWXJWaIhHIw+/kTybqxIvRRqtF6qRZJhqFyoRzcGHLgNOtfH9JYcP3vTZgvC+Jf7kVE7x4xWyNGuJAO3NJDx/sZhpkm6pbrP9UpEXIkBhpdlIZLgN1vKEv3x0KWCNnPJRX6+7fAdUGlJ8qNwS7yNps+2bvS9I+cpRfHvikUvPmZ/6yY7CAmqRSeDOlJ2ZiMdo27L4rcd9y0ymEMJW7d6G0TKsKV2vyIgPM4dKfGKinaWAlPJ6BzL+60fJyOXF1i5lpGu7hcVDgFrCx26SvMwAnDySg7ZTCgWUA7vQ0BcSGiavUJR3tcFn1UKzMIisuN+KESaQSyokVTkIIVwE/X8bCIihfTP+xaD6jRbT3lq5VD8UtUmpp91zwUOfaW48CY91Dot17ohgUDIXlYQAMTu0rdERvWv8UsbEV0OC0OfMp8+BwkqZgVsqn4BRtF4hgPnttPolkK410vRAMmNqtNJNlTCacvBdBsYSjkd0lA+aZWj/CnH+rIVOcBVvGqoQBfbGAcnPxnJZnBgdVGRYvG3F8VfvbBxdueTF80w37B9tkoor3Q1QE6OL0pIXsGx1udZRkwh/L3uGwUhdjtWXzcgwedLMc3krgg+s+HiYv9ijYbtlf4xLCqeDWMYfoePaYYBcZqB0tCjqOl9z8Qg8dOp+nSWm7aU/iZfb/aKWHJ4qnA6OwiCsFb1OlxgOKoKXb/nirsA61zCnTv1T6WMaWcVyenZlWQH9VJRbxGF4mDQwUH1ODwMOEkjzq6tQf1/pBAMLnPRJJVxwugRI3BhOPlh9dKHx6Kz/IOsWD6a74JGxeNwrlKJWdiFxT5PE0RdyAUb7hXTd+JfaTzW/y1vQP9fpiQtR/VkksjWkvhareumlOImMqNlETtMZpnhKJYHvf2KwvZcLlPJiZJRP4poH2RlKs0+PyWlSDLorfWU/Aih2HvP7CHsY4qqv5fyHHwkrdtRpEcSILP0x229wjEzgOBP7Dhqv0/FYRkQ6p4lYG0GfjGYLNtfhLjT4i8Kk2EX4D5TCuI5YEjB2uAO1bY6q7wCcEDJ1J/fuk+/PSF3POPSuT+gawtq7Wzzxd7l0KqcJcr/3DOfvwKepywPD1qXrg5N197/reQ5pWxRN0yu86Fvqdo4Vcz8rZzPsKijf3kO2BJohH8zdPEZeBpPbx9u19XIzIF1ALn74gse6GoVRQaygTF/qKWqmcpW4KnRlHLmgiWYEfPSO9PAG5UOObHDq7h/lLpCD2AbL6oaB90EINCcDT35qJenZJbaRiUdJXqvx79cqNWosUbDwuOIpJ+ZvVsDGIgXlOPv9kDIcZ4r1EbiLtmsEMSNWnjUXE/pPRKElFgbHmG07CbzMWIhXCEebGhnEy4FdTraidI6r8Q6CjpBgAxWntRPTucg2gC0fEBDB6HBSlAb+MekBFgQbwCk7KFCo+fuFd/zoFDy0BqRpPvwWL5XSj5HqMUIwHQYJKoZIhvcNAQkUMRAeDgBnAGEAdABlAHcAYQB5MCEGCSqGSIb3DQEJFTEUBBJUaW1lIDE1MjAyMDU3NzY5OTYwggRTBgkqhkiG9w0BBwagggREMIIEQAIBADCCBDkGCSqGSIb3DQEHATAoBgoqhkiG9w0BDAEGMBoEFMffFY5blz/6TYqX7DQ9ofE/vBZMAgIEAICCBABr4otaoQA6aScKn/oGap/7XxJQYoj5mDIs040v8kujDVtdIrBDVKzaU4A5XP2OjOgCx8e+bYop0F7uvnGRFPsrkCqdWBecT+yVY6z7UxTjqq1Dt1it/6GGbGpx9LieGRAsMCWZB80ly5b8QUfx565Ym8Bfl6eMHA8pVByAFdXpsUDJU0KqJjHmUGzxHe32ly9PguNtj8qh7ulPUfIsJXDOYWtbF7hPdz1qMIEbFfqs5Xf0ehy7gpVCyCfX0xCjrDKeosg0KbcZ3rbnCwxBCWpbDXMEyQ/c1DnUuoie/RuIV7QayZHP+rzxJ6RV549hT1lm2oIIOJtdUR/+vOCCSQgzVESXnS5e7HzGpSfzLFC6FSG2/BESY9PaYY+V5BXitOrY5mmNZbgGNKyi1p+Kp1lwHrjmB0szgXFynAxtGkA/kq05j31kycYMhY7ckkoZ92NUPELV190LAlz3IOoTx9C4yeyHYbC/Y0nzZs5FQvkajuzAU4EsI+Te3iFh1kohC0Ulk4SQKCPq+Ob/dvModO9l61R8yCHDxsZeFACaCCsH7RQJRxeV1LUVHoiX1aJVuE01bj3jEBQN+ZI1A8qNdbCI+/q1o/GMVKQxtz5PY02A8VIa1cMGUwY5ljJJlTdRzPqiy3qP5ClbHKsbWucUECKfhAkqTuS0Uqm+h3Y6IN6yYxYqjbKEIuqgwbGiOJZzu82nVG51QpBtvMf1eDyOSOkQ2JZey+vXlOghavQl8aFluv5FHigw9Zk9yVZf8Z8Jk1ruVvFzlB1NXnn2YqKtKhYb+J/dqVhKiToDMQccYY7Hw8HSBXRzl345EVLxyjCngyAU6VjztqjCW6HYNjNggyUVYmDQ49XOsq6U/7QhzBEbhYo48f7qvPVetRxShSjXt5Jnc+5mJG7UXHAhBSUayFv5T5CUmKlhbcuKyzX0Euib6WgajPdKcgib4bUpAD7L1Y2cEYorWE/yASnY06ZNabRAcyRSQnkZecZ0X95GTUmX08oOblskmQlBzQunjQSRvdpLBCu1356NwYZ8CJ/bqMp1g25FBKXCStKoDuluD1PT9Trd7Dv+f65EPvKTt6S90h/EscPV3D1sx+foPf6kdPl3LfX7/o4H2b01yErbTDCYcew0qkoRLpqHJr8GAyTjW6478sgqxCDbW1R0dpGiJkCHyqEQd8g/b9zu+4Pab4Y1O5lIKhhnnVWfajdWmY1NJk7hvpJwpkydRTuic/JhMnmUafuoGW5ZLxfjyejZnH4z8SIxVXJeljHuOgp0wMxGiXbq+dcj2t5o9F3AMJ5lwfS5mzhvNIieGdOjGiyORx/HuAXwLOxg/6IhhP1usbZ1NXYyrPEMiN3icg0i8juDnvsiMD0wITAJBgUrDgMCGgUABBTQs2HzR+FLxtn2YexYPyg+nzXREAQUj8/6NHfuC4w2C2cblAttX3rFlzcCAgQA"},"mapping":[{"deviceNodePattern":"Modbus\\.M580","deviceNamePattern":"M580","attributes":[{"key":"MW100","type":"string","value":"${MW100}"}],"timeseries":[]}]}]}}]`

3. Sync the device and refresh the page. M580 device was added automatically and attribute value is in sync with the OPC-UA server (went to change the attribute value and it got reflected on thingsboard)
4. Restart kepServerEX service
5. Change the attribute value but did not get reflected on thingsboard
6. Restarted tb-gateway and checked the logs. It keep displaying outgoing queue is not empty. The only way to fix it was to delete and recreate the gateway and device.

> 2018-07-24 14:39:29,240 [main] INFO  o.t.gateway.GatewayApplication - Started GatewayApplication in 6.609 seconds (JVM running for 7.877)
2018-07-24 14:39:29,856 [pool-3-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-07-24 14:39:30,857 [pool-3-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-07-24 14:39:31,857 [pool-3-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-07-24 14:39:32,858 [pool-3-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress

**Comment by zbeacon** [comment]
Hi, @shaunysj 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
 - Less footprint and memory impact
 - Easier to extend and customize
 - Improved functionality.

You can try using a new gateway for your purposes instead of a Java gateway.

We look forward to your feedback.
