### ISSUE TITLE
[HELP] Adding TLS to Gateway

### ISSUE THREAD

**Issue by DriftingShadows** [thingsboard/thingsboard-gateway#1070]
Sorry as I'm kind of new to dealing with TLS and all that. I'm not entirely sure how to add the TLS + Access Token capability to my Gateway on AWS. Where do I get the certificate? (based on https://thingsboard.io/docs/iot-gateway/configuration/?storageConfig=sqlite&securityConfig=tlsToken).

Are those instructions related to the ones [here](https://thingsboard.io/docs/user-guide/mqtt-over-ssl/)? It mentions that the Load Balancer can't be used to secure the traffic for 2-way SSL. Any guidance appreciated.

**Comment by samson0v** [comment]
Hi @DriftingShadows, thanks for your interest in ThingsBoard IoT Gateway!
If you are using ThingsBoard Cloud, you can easily download a valid certificate for [ThingsBoard Cloud](https://thingsboard.cloud/signup).
Follow the [MQTT over SSL](https://thingsboard.io/docs/user-guide/mqtt-over-ssl/) guide to provision server certificate if you are hosting your own ThingsBoard instance.

https://thingsboard.io/docs/user-guide/access-token/#mqtts-mqtt-over-ssl

**Comment by samson0v** [comment]
Hi @DriftingShadows, any updates? Can we close the issue?
