### ISSUE TITLE
is OPC-DA supported?

### ISSUE THREAD

**Issue by lyongdee** [thingsboard/thingsboard-gateway#1092]
is  OPC-DA supported?

**Comment by samson0v** [comment]
Hi @lyongdee, thanks for your interest in ThingsBoard IoT Gateway!
No, OPC-DA is not supported and will not be supported in the future.
OPC-UA is the successor to OPC-DA. It has many benefits, one of the most prominent being platform agnostic. There are SDKs available in many languages and OPC-UA can be implemented on anything from a tiny embedded device running Linux, to a desktop running Windows, or a server running the OS of your choice.
