### ISSUE TITLE
[BUG] Server side RPC: data instead of params

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard-gateway#1106]
**Describe the bug**

!!! Note !!!  For some reasons `data` key is used in others method of the MQTT connector. Is it breaking change?

![data](https://user-images.githubusercontent.com/86909129/235352209-f194ffba-30be-42ff-80c4-88561656a14b.jpg)

**Connector name (If bug in the some connector):**
MQTT Connector

**Versions (please complete the following information):**
 - Thingsboard 3.4.1
 - Thingsboard IoT Gateway version: master

**Comment by samson0v** [comment]
Hi @devaskim, thanks for your interest in ThingsBoard IoT Gateway!
Send, please, your MQTT Connector config file.

**Comment by devaskim** [comment]
Thanks @samson0v for your attention

My MQTT Connector configuration isn't a secret, but I think, it doesn't help, because there is **only** `mapping` section.
To send RPC, I use default `RPC button` widget.

![rpc](https://user-images.githubusercontent.com/86909129/235643834-247faea0-e6e2-415a-88a1-752f1a32e296.jpg)

**Comment by devaskim** [comment]
I patched a bit code of MQTT connector, so once the gateway gets this RPC, it will call [self._send_current_converter_config()](https://github.com/thingsboard/thingsboard-gateway/blob/master/thingsboard_gateway/connectors/mqtt/mqtt_connector.py#L445) which you have added recently.

**Comment by samson0v** [comment]
@devaskim
<img width="1064" alt="зображення" src="https://user-images.githubusercontent.com/43861229/235648819-8126de9f-18bd-48c6-97e9-c9c176661643.png">
<img width="772" alt="зображення" src="https://user-images.githubusercontent.com/43861229/235648847-e6fc489e-ae09-4f33-82d8-9a7489c35be6.png">

**Comment by devaskim** [comment]
Strange, what is your server version? Mine is 3.4.1

**Comment by samson0v** [comment]
@devaskim, I can't see `device` in your content.
It won't work even if you change data to params.

**Comment by samson0v** [comment]
@devaskim try to check your Entity Alias, maybe it is the cause of the problem.

**Comment by samson0v** [comment]
@devaskim 
<img width="614" alt="зображення" src="https://user-images.githubusercontent.com/43861229/235650267-9d1a4f33-faf0-4f92-96a6-e3c3f7df40ff.png">
<img width="689" alt="зображення" src="https://user-images.githubusercontent.com/43861229/235650310-8cd42d50-d51a-437d-a183-830c2345f0b6.png">
<img width="483" alt="зображення" src="https://user-images.githubusercontent.com/43861229/235650338-ef902bf8-8556-411c-a99b-d9232d94de71.png">

**Comment by devaskim** [comment]
I got my RPC on gateway side, so entity alias is correct and the same is yours. Here is the code of gateway with my fix and patch for new RPC method for connector.

![rpc](https://user-images.githubusercontent.com/86909129/235650778-4131e008-2965-47f4-87c4-18ffb73ba4d5.jpg)

**Comment by devaskim** [comment]
@samson0v So (my) problem occurs on the step 1

**Comment by samson0v** [comment]
@devaskim, ok, I understand how it is working.
You can't simply change data to params because RPC for the device and gateway are different.
I will create a PR.

**Comment by devaskim** [comment]
Thanks @samson0v for help
Could you add RPC for synchronizing converters' config as I did? If yes, the name is up to you.

**Comment by samson0v** [comment]
@devaskim, we decided that client attributes will update every time when the converter config updates.

**Comment by devaskim** [comment]
> we decided that client attributes will update every time when the converter config updates

@samson0v It may be even more convenient, but how does connector know if **custom** converter config is changed? Would it be some callback that converter could call on its config update? Just to remind, our converter has 2 part of config: static (from `mqtt.json`) and dynamic, so called, dictionaries which converter receives from MQTT broker.

**Comment by devaskim** [comment]
Sad, it doesn't cover our case.

Do you think the flow you have described is needed at all? I mean, you just duplicates data from shared attribute to client attribute.

**Comment by imbeacon** [comment]
@devaskim These parameters depends on the entitiy that you uses to send RPC for. You can easily change in your version of the MQTT connector and use it. We will think about mechanism that we can develop to give ability to implement custom RPC for connectors, But it will be in the future, after releasing a new version of the gateway remote configuration.

**Comment by devaskim** [comment]
Ok, thanks team
