### ISSUE TITLE
[HELP]I got a log error and log files are empty

### ISSUE THREAD

**Issue by a-jiang** [thingsboard/thingsboard-gateway#1115]
**Describe the issue**
i got a log error .
![image](https://user-images.githubusercontent.com/9330004/237014837-b8f872ca-2fd2-4a36-b479-0bccafa4047f.png)

and log files are empty 
![image](https://user-images.githubusercontent.com/9330004/237015120-28507ff3-fcee-44cf-8831-99861f524420.png)

**Configuration** (Attach your configuration file)
**Notate: Remove Access token from file if you want to attach a tb_gateway.yaml**

**Connector name (If you need help with some connector/converter):**
[e.g. MQTT Connector]

**Error traceback (If it was raised):**
```
'deviceName'
Traceback (most recent call last):
  File "<input>", line 2, in <module>
KeyError: 'deviceName'
```

**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Thingsboard IoT Gateway version [e.g. 3.0.1]
 - Python version[e.g. 3.9]

**Comment by samson0v** [comment]
Hi @a-jiang, thanks for your interest in ThingsBoard IoT Gateway!
Please, send configuration files (connector config file, tb_gateway.yml, logs.conf) and log files.

**Comment by samson0v** [comment]
Hi @a-jiang, can we close the issue?
