### ISSUE TITLE
Has anyone setup a RUT955 or any Teltonika device to Thingsboard website so that the thingsboard website can control devices through the control widgets/RPC??

### ISSUE THREAD

**Issue by Buhaw85** [thingsboard/thingsboard-gateway#1123]
Rule Engine
Installation
Im using the RUT955 to read registers from my devices and send that info to the thingsboard website. I have this working great. I would now like to control my devices from the thingsboard website. I would like to write registers from the thingsboard website using their control widgets and RPC. But I am having troube to get this to work. I can write registers from the RUT955 using the test function and it works great but now I woulid like to use the thingsboard website to do this using control widgets.

Has anyone figured this out? Is there a step by step guide in seting up the RUT955 and Thingsboard so I can control my devices from the the thingsboard dashboard?

Thanks

**Comment by samson0v** [comment]
Hi @Buhaw85,
Teltonika RUT955 can work only as an uplink or downlink but not simultaneously.
Also, we will publish the "Teltonika RUT955 with Siemens LOGO!  to ThingsBoard" guide.
[PR](https://github.com/thingsboard/thingsboard.github.io/pull/1173)
