### ISSUE TITLE
[HELP] use expression to get label

### ISSUE THREAD

**Issue by andonoc** [thingsboard/thingsboard-gateway#1124]
Hi,
Is it possible with the MQTT connector, to use a JSON expression that is looking for a label in the incoming message for example to use room_22 as label in thingsboard?
Thank you

**Comment by samson0v** [comment]
Hi @andonoc, thanks for your interest in ThingsBoard IoT Gateway!
Unfortunately, ThingsBoard doesn't support this functionality.

**Comment by andonoc** [comment]
thank you @samson0v
