### ISSUE TITLE
[HELP]Install failing in windows by python3

### ISSUE THREAD

**Issue by kiraten191010** [thingsboard/thingsboard-gateway#1126]
Hello , Is this  "thingsboard-gateway" is possible to install in Windows10 by python3 ?

I use command     pip3 install thingsboard-gateway

but it keep failing.

It always have this error

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio
  Running setup.py clean for grpcio
Failed to build grpcio
ERROR: Could not build wheels for grpcio, which is required to install pyproject.toml-based projects

**Comment by samson0v** [comment]
Hi @kiraten191010, thanks for your interest in ThingsBoard IoT Gateway!
Try to use this solution https://stackoverflow.com/questions/56357794/unable-to-install-grpcio-using-pip-install-grpcio
Also, try to google: how to install grpcio on Windows if the above doesn't help.

**Comment by samson0v** [comment]
Hi @kiraten191010, can we close the issue?

**Comment by kiraten191010** [comment]
Thank you very much
