### ISSUE TITLE
Gateway does not connect with ThingsBoard

### ISSUE THREAD

**Issue by letsbtw** [thingsboard/thingsboard-gateway#1128]
Hello, my problem is pretty simple: I can't seem to connect my gateway with ThingsBoard. No error is showed when I run the gateway, but also nothing happens on ThingsBoard.
What I am trying to do is to send telemetry with MQTT from an external device to ThingsBoard. So I have a modbus simulator sending data to this external device, and I want the same data to be sent with MQTT to ThingsBoard. 

Configuration files
[mqtt.txt](https://github.com/thingsboard/thingsboard-gateway/files/11792324/mqtt.txt)
[tb_gateway.yaml.txt](https://github.com/thingsboard/thingsboard-gateway/files/11791867/tb_gateway.yaml.txt)
[custom_mqtt_uplink_converter.py.txt](https://github.com/thingsboard/thingsboard-gateway/files/11791891/custom_mqtt_uplink_converter.py.txt)
[service.log](https://github.com/thingsboard/thingsboard-gateway/files/11791859/service.log)
[storage.log](https://github.com/thingsboard/thingsboard-gateway/files/11791862/storage.log)
[tb_connection.log](https://github.com/thingsboard/thingsboard-gateway/files/11791864/tb_connection.log)
[connector.log](https://github.com/thingsboard/thingsboard-gateway/files/11791888/connector.log)

Connector name 
MQTT Connector

 - OS: [Ubuntu Server 22.04]
 - Thingsboard IoT Gateway version [3.2]

**Comment by samson0v** [comment]
Hi @leitinhakk, thanks for your interest in ThingsBoard IoT Gateway!
Please, replace all `INFO` with `DEBUG` levels in logs.conf and send them here, we need more logs to understand your problem.

**Comment by leitinhakk** [comment]
here they are

[service.log](https://github.com/thingsboard/thingsboard-gateway/files/12099081/service.log)
[tb_connection.log](https://githu
[connector.log](https://github.com/thingsboard/thingsboard-gateway/files/12099085/connector.log)
b.com/thingsboard/thingsboard-gateway/files/12099083/tb_connection.log)

**Comment by imbeacon** [comment]
The issue is outdated, and relates to old version of the gateway, please use a new verison of the gateway and feel free to create a new issue if you notice some misbehaviour.
