### ISSUE TITLE
thingsborad cloud updated shared attribute close error [BUG]

### ISSUE THREAD

**Issue by guoziqin** [thingsboard/thingsboard-gateway#1130]
**Describe the bug**
Clear and concise description of what the bug is.

**Connector name (If bug in the some connector): 
ModbusConnector

**Error traceback (If available):**
```
ConvertWorker close error
```

**Versions (please complete the following information):**
 - OS: MacOS 13 m2 Max
 - Thingsboard IoT Gateway version 3.2
 - Python version: 3.10

description:
thingsboard cloud update shared attribute  trigger thingsborad gateway update remoteconfiguration callback __apply_new_connectors_configuration method,  self.__gateway.available_connectors[connector_name].close() 
ModbusConnector close methods only close socket ConvertWoker thread not close? this is bug ?

**Comment by guoziqin** [comment]
![dec7c367223a01491484f19c53b6cac3](https://github.com/thingsboard/thingsboard-gateway/assets/37041136/8b122df2-23e6-4735-a8dd-dd1df672a463)
thread debugger

**Comment by guoziqin** [comment]
load_slave in put queue,but close no execute queue.clear()

**Comment by samson0v** [comment]
Hi @guoziqin, thanks for your interest in ThingsBoard IoT Gateway!
Can you, please, describe your bug more clearly?
Also, write steps to reproduce, pls.

**Comment by samson0v** [comment]
Hi @guoziqin, can we close the issue?
