### ISSUE TITLE
[HELP]Support on single-chip microcomputer

### ISSUE THREAD

**Issue by klonhj2015** [thingsboard/thingsboard-gateway#1147]
If we want to deploy the tb-gateway on single-chip microcomputer, but most single-chip microcomputers do not support python ,so is there any plan to develop code in other languages otherwise python

**Comment by samson0v** [comment]
Hi, @klonhj2015, thanks for your interest in ThingsBoard IoT Gateway!

> so is there any plan to develop code in other languages otherwise python?

Yes, we have in plan to write ThingsBoard IoT Gateway in C++ but it won't be in the nearest future.

**Comment by imbeacon** [comment]
Closed as not planned, at the moment.
