### ISSUE TITLE
[HELP]maximum number of connected thingsboard gateway to thingsboard

### ISSUE THREAD

**Issue by redasdasd** [thingsboard/thingsboard-gateway#1153]
How many thingsbaord gateways can be connected to thingsboard at most? and where can I set the maximum number of connected thingsboard gateway to thingsboard?

**Comment by samson0v** [comment]
Hi @redasdasd, thanks for your interest in ThingsBoard IoT Gateway!
You can connect as many gateways to the ThignsBoard as you want but it must be different devices.
That means you can have only one active connection from the gateway to ThingsBoard with the same creds.

We know about this limitation and will improve it in some of the next releases.

**Comment by samson0v** [comment]
Hi @redasdasd, can we close the issue?
