### ISSUE TITLE
[HELP] add/update config via external system

### ISSUE THREAD

**Issue by JoyceWithCat** [thingsboard/thingsboard-gateway#1156]
Hi all, may I know is there any offical way to add/update connector json and tb_gateway.yaml in docker. I have an external system and i would like to handle those connectors in my own system. Thank you.

**Comment by samson0v** [comment]
Hi @JoyceWithCat, thanks for your interest in ThingsBoard IoT Gateway!
Can you, please, provide more about what you want to do?

**Comment by samson0v** [comment]
Hi @JoyceWithCat, is this bug still actual for you or can we close it?
