### ISSUE TITLE
Device type is required

### ISSUE THREAD

**Issue by mileo** [thingsboard/thingsboard-gateway#116]
Hi,

Where i can create a device type?

![image](https://user-images.githubusercontent.com/1975978/44828635-418b9400-abef-11e8-8b36-0447752b8afd.png)

I can't add a Device without type.

Thanks in advance

**Comment by mp-loki** [comment]
Device type is required by ThingsBoard, but it is just a String value. you can type 'default' or smth like that for the Device Type

**Comment by mileo** [comment]
Thanks, I think I've been working too long.
