### ISSUE TITLE
[HELP] Is there a way to config clientSideRpc for mqtt connector

### ISSUE THREAD

**Issue by xiaomalover** [thingsboard/thingsboard-gateway#1163]
**Describe the issue**
 Is there a way to config clientSideRpc for mqtt connector

**Configuration** (Attach your configuration file)
**Notate: Remove Access token from file if you want to attach a tb_gateway.yaml**

**Connector name (If you need help with some connector/converter):**
MQTT Connector

**Error traceback (If it was raised):**
```
'deviceName'
Traceback (most recent call last):
  File "<input>", line 2, in <module>
KeyError: 'deviceName'
```

**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Thingsboard IoT Gateway version [e.g. 3.0.1]
 - Python version[e.g. 3.9]

**Comment by samson0v** [comment]
Hi @xiaomalover, thanks for your interest in ThingsBoard IoT Gateway!
Unfortunately, Mqtt Connector doesn't have this functionality.

**Comment by samson0v** [comment]
Hi @xiaomalover, can we close the issue?
