### ISSUE TITLE
[BUG / HELP] ThingsBoard Gateway Widget - Save Button Not Functional

### ISSUE THREAD

**Issue by AIOTEL-sanjanaa** [thingsboard/thingsboard-gateway#1165]
**Describe the bug**
I am using demo.thingsboard.io connected to ThingsBoard Gateway version 3.3.4. I wanted to remotely configure my OPC-UA, so I tried using the Gateway widgets provided from the widget bundle. However, unfortunately, the save button does not seem to be working or is non-functional.
![Screenshot from 2023-08-17 10-30-48](https://github.com/thingsboard/thingsboard-gateway/assets/132904735/59552e98-aa58-4b23-99f1-ea402f35d684)

**Versions (please complete the following information):**
 - Thingsboard IoT Gateway version - 3.3.4
 - Python version - 3

**Comment by samson0v** [comment]
Hi @AIOTEL-sanjanaa, thanks for your interest in ThingsBoard IoT Gateway!
We will release a fully new Gateway Remote Configuration dashboard soon.
The old widgets will remove.

**Comment by AIOTEL-sanjanaa** [comment]
> Hi @AIOTEL-sanjanaa, thanks for your interest in ThingsBoard IoT Gateway! We will release a fully new Gateway Remote Configuration dashboard soon. The old widgets will remove.

Okay thank you.
