### ISSUE TITLE
[HELP] The description of the RPC request initiated by the device side cannot be found in the document

### ISSUE THREAD

**Issue by zhifuChen1999** [thingsboard/thingsboard-gateway#1166]
**Describe the issue**
The description of the RPC request initiated by the device side cannot be found in the document

**Comment by samson0v** [comment]
Hi @zhifuChen1999, thanks for your interest in ThingsBoard IoT Gateway!
Sorry, but I do not understand clearly what you mean.
Please describe in more detail what you mean.

**Comment by samson0v** [comment]
Hi @zhifuChen1999, can we close the issue?
