### ISSUE TITLE
[Question] Thingsboard Gateway deployment scenario

### ISSUE THREAD

**Issue by shashank-r25** [thingsboard/thingsboard-gateway#1168]
Hello,

What are the deployment scenarios for Thingsboard Gateway?
How many devices and requests can be handled?
Gateway should be deployed in a new server or within the existing server.
what is the persistent file storage format when it's stored in the gateway?
persistent file storage should be with the Thingsboard gateway&cloud server or in a separate server?
licensing of Thingsboard gateway?

Thank You,

**Comment by samson0v** [comment]
Hi @shashank-r25, thanks for your interest in ThingsBoard IoT Gateway!
You can deploy Gateway as another regular service (docker, source, deb, etc.).
About storages: https://thingsboard.io/docs/iot-gateway/configuration/#storage-configuration

**Comment by shashank-r25** [comment]
Hi @samson0v, Thank you for the reply.
