### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pgirgis** [thingsboard/thingsboard-gateway#1169]
**Describe the bug**
A comma is missing in setup.py on line 63 resulting in the failuse to run.

**Connector name (If bug in the some connector):**
main setup.py file

**Error traceback (If available):**
```
python3 setup.py install
error in thingsboard-gateway setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
    urllib3<=1.26.15requests>=2.31.0
           ~~~~~~~~~~^
```

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04]
 - Thingsboard IoT Gateway version MASTER
 - Python version[e.g. 3.10]

**Comment by imbeacon** [comment]
Hi @pgirgis ,

Thank you for your help, updated in master branch.
