### ISSUE TITLE
[HELP] split data to multiple devices

### ISSUE THREAD

**Issue by z1z2** [thingsboard/thingsboard-gateway#1170]
Hi, @samson0v 

You mentioned in the following issue that we can use Request Connector to split data. Would you please show me how to do it? It seems the convert function just return such object: {"deviceName": None, "deviceType": None, "attributes": [], "telemetry": []}

_Originally posted by @samson0v in https://github.com/thingsboard/thingsboard-gateway/issues/1065#issuecomment-1477544039_

**Comment by samson0v** [comment]
Hi @z1z2, thanks for your interest in ThingsBoard IoT Gateway! 
You can use the same `url` parameter in several `mapping` items but parse it differently.
Send, please, your config files (tb_gateway.yaml, request.json).
