### ISSUE TITLE
[HELP] Remote Converter Update feature : JSON Configuration

### ISSUE THREAD

**Issue by AIOTEL-sanjanaa** [thingsboard/thingsboard-gateway#1171]
**Remote Converter Update:**
- In the [Remote Converter Update Documentation](https://thingsboard.io/docs/iot-gateway/guides/how-to-use-remote-converter-update/) there is no mention of the json format to follow to use the feature.
-  I tried connecting it to my gateway and send shared attributes for my OPC-UA connector. 
![image](https://github.com/thingsboard/thingsboard-gateway/assets/132904735/2fbc5822-f63d-4621-930b-f0cb706727dc)
- But the configuration is not updated.
- This is my logs from thingsboard-gateway:
![image](https://github.com/thingsboard/thingsboard-gateway/assets/132904735/ff9e2430-8c6b-4b2a-a408-65f8a0ef05e0)
- This is the tb_gateway.yaml configuration.
![image](https://github.com/thingsboard/thingsboard-gateway/assets/132904735/3617c1ef-d4ce-4e49-9c1b-2b13e132c292)
![image](https://github.com/thingsboard/thingsboard-gateway/assets/132904735/db204627-eed6-480f-96e7-916ff150c1f0)

**Questions:**
- What is the proper format of shared attributes?
- Is there any other configurations that I have to add in the tb_gateway.yaml file?
- What additional steps are required for a functional Remote Converter Update feature?

**Versions:**
 - OS: Ubuntu
 - Thingsboard IoT Gateway version: 3.3
 - Thingsboard: 3.5
 - Python version: 3.10

**Comment by samson0v** [comment]
Hi @AIOTEL-sanjanaa, thanks for your interest in ThingsBoard IoT Gateway!
![image](https://github.com/thingsboard/thingsboard-gateway/assets/43861229/09ba74f7-f897-4974-8ccb-52749d20e672)

**Comment by AIOTEL-sanjanaa** [comment]
Okay, thank you
