### ISSUE TITLE
[HELP]how gateway resent to thingsboard

### ISSUE THREAD

**Issue by codeMark1** [thingsboard/thingsboard-gateway#1177]
If the gateway MQTT fails to send a message to thingsboard, how is the already sent message resent?

**Comment by imbeacon** [comment]
Hi @codeMark1,

For this functionality responsible paho-mqtt library, it will resend if you have QoS 1 in general configuration file (qos is set to 1 by default).

**Comment by samson0v** [comment]
Hi @codeMark1, can we close the issue?
