### ISSUE TITLE
[HELP]The configuration file tb_gateway of the gateway was changed from yml to json and cannot be run.

### ISSUE THREAD

**Issue by MaryLee7979** [thingsboard/thingsboard-gateway#1181]
Question 1. Gateway's tb_gateway.yml has been changed to json format. Is there a more detailed description of the "connectors" parameter? The official website information is still in yml format.

Question 2. Trying to set tb_gateway.json and start tb_gateway.py through python, but the following error occurs and cannot be run.

**Configuration** (Attach your configuration file)
[tb_gateway.txt](https://github.com/thingsboard/thingsboard-gateway/files/12681672/tb_gateway.txt)

![pip_list](https://github.com/thingsboard/thingsboard-gateway/assets/143065053/eec1d821-69be-4eaf-8a52-6969aa6be263)

**Error traceback (If it was raised):**
![tb_gateway_err](https://github.com/thingsboard/thingsboard-gateway/assets/143065053/670c5867-f921-4bf1-b354-d076e21ad166)

**Versions (please complete the following information):**
 - Thingsboard IoT Gateway version [3.3]
 - Python version:3.9.5

**Comment by imbeacon** [comment]
Hi, @MaryLee7979 

Yes, starting from the version 3.4 we decided to use JSON instead of yaml to decrease amount of required libraries and unify configuration files. You should have tb_gateway.json in the configuration folder with your configurations. If no - please let us know about this.

**Comment by imbeacon** [comment]
Documentation is in progress and it will updated as soon as possible.

**Comment by MaryLee7979** [comment]
> Hi, @MaryLee7979
> 
> Yes, starting from the version 3.4 we decided to use JSON instead of yaml to decrease amount of required libraries and unify configuration files. You should have tb_gateway.json in the configuration folder with your configurations. If no - please let us know about this.

iot gateway v3.4 the package contains json format files,Then I will run it using v3.3 for now and wait for your completed operating instructions for 3.4.
Thanks you.

**Comment by mrangics** [comment]
Would really helpful to provide a sample configuration file with the new JSON format including the OOTB connectors, even here, just to post it.

**Comment by devaskim** [comment]
@mrangics Did you mean [this file from the repo](https://github.com/thingsboard/thingsboard-gateway/blob/master/thingsboard_gateway/config/tb_gateway.json) ?

**Comment by mrangics** [comment]
> @mrangics Did you mean [this file from the repo](https://github.com/thingsboard/thingsboard-gateway/blob/master/thingsboard_gateway/config/tb_gateway.json) ?
> 
> ```
> ...
>  "connectors": [
>     {
>     // the same fileds as in yaml but with json formatting
>     }
> ]
> ...
> ```

Hi,
yes, but this is not complete. A complete JSON is necessary to show how to define the connectors!
Thanks,
Máté

**Comment by devaskim** [comment]
@mrangics Agree, it is not complete and that might be a problem for new users. For others, it is just YAML to JSON conversion of existing configuration and there is a lot online converters

**Comment by devaskim** [comment]
In general, it is sad that there is no caution at least [on the release page](https://github.com/thingsboard/thingsboard-gateway/releases) about migrating to JSON format.

**Comment by samson0v** [comment]
Hi @devaskim and @MaryLee7979, thanks for your interest in ThingsBoard IoT Gateway!
Documentation [PR](https://github.com/thingsboard/thingsboard.github.io/pull/1166) created, waiting for merge.

**Comment by devaskim** [comment]
@samson0v Great! Now I am calm for humanity ;)

**Comment by samson0v** [comment]
Updated docs:
https://thingsboard.io/docs/iot-gateway/guides/how-to-enable-remote-configuration/
https://thingsboard.io/docs/iot-gateway/getting-started/
