### ISSUE TITLE
Installation Issue in Ubuntu [HELP]

### ISSUE THREAD

**Issue by Seungchan-Daliworks** [thingsboard/thingsboard-gateway#1197]
**Describe the issue**

I did installation process described in the following link.
[https://thingsboard.io/docs/iot-gateway/install/deb-installation/](https://thingsboard.io/docs/iot-gateway/install/deb-installation/)

But, in the Step2 'sudo apt install ./python3-thingsboard-gateway.deb -y' command, I got a error message and couldn't complete installation.
![Screenshot from 2023-10-18 16-54-48](https://github.com/thingsboard/thingsboard-gateway/assets/142375061/65e8961e-746f-4a65-bc23-f4ea1c17cd47)

**Versions (please complete the following information):**
 - OS: Ubuntu 20 (Mac Mini)
 - Python version : pip 20.0.2

**Comment by pro100805** [comment]
WARNING: Running pip as the 'root' user can result in broken permissions

....
Installing collected packages: jsonschema
  Attempting uninstall: jsonschema
    Found existing installation: jsonschema 3.2.0
    Not uninstalling jsonschema at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'jsonschema'. No files were found to uninstall.
Successfully installed jsonschema-3.1.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: h                                                                                                                                                                                                ttps://pip.pypa.io/warnings/venv
Installation completed
Enabling daemon...
1021
Created symlink /etc/systemd/system/multi-user.target.wants/thingsboard-gateway.service → /etc/systemd/system/thingsboard-gateway.service.
1021
-e Thingsboard Gateway has been installed. Have a nice day :)
Setting up gcc (4:11.2.0-1ubuntu1) ...
Setting up libexpat1-dev:amd64 (2.4.7-1ubuntu0.2) ...
Setting up libgd3:amd64 (2.3.0-2ubuntu2) ...
Setting up libstdc++-11-dev:amd64 (11.4.0-1ubuntu1~22.04) ...
Setting up zlib1g-dev:amd64 (1:1.2.11.dfsg-2ubuntu9.2) ...
Setting up libc-devtools (2.35-0ubuntu3.4) ...
Setting up g++-11 (11.4.0-1ubuntu1~22.04) ...
Setting up libpython3.10-dev:amd64 (3.10.12-1~22.04.2) ...
Setting up python3.10-dev (3.10.12-1~22.04.2) ...
Setting up g++ (4:11.2.0-1ubuntu1) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
Setting up build-essential (12.9ubuntu3) ...
Setting up libpython3-dev:amd64 (3.10.6-1~22.04) ...
Setting up python3-dev (3.10.6-1~22.04) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.4) ...
Scanning processes...
Scanning linux images...

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
N: Download is performed unsandboxed as root as file '/home/gde/python3-thingsboard-gateway.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

Versions (please complete the following information):

    OS: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-86-generic x86_64) clean installation

**Comment by pro100805** [comment]
WARNING: Running pip as the 'root' user can result in broken permissions 

![3 4 1](https://github.com/thingsboard/thingsboard-gateway/assets/135635967/df34cceb-e1ea-4741-96f3-a1e86b242573)
 
OS: 22.04.3 LTS (GNU/Linux 5.15.0-86-generic x86_64) clean installation deb 3.4.1

**Comment by samson0v** [comment]
Hi @Seungchan-Daliworks, thanks for your interest in ThingsBoard IoT Gateway!
Try to run the following command:
`pip install cryptography==3.4.0 --force-reinstall`

**Comment by Tasosgi** [comment]
I am also dealing the same problem

**Comment by Tasosgi** [comment]
Works with the Ubuntu Server 22.04.3 LTS
