### ISSUE TITLE
Installation in Ubuntu 22.04 [HELP]

### ISSUE THREAD

**Issue by pro100805** [thingsboard/thingsboard-gateway#1199]
WARNING: Running pip as the 'root' user can result in broken permissions
![3 4 1](https://github.com/thingsboard/thingsboard-gateway/assets/135635967/973fc0d2-8a03-4396-9c19-b8d4abd4becf)
OS: 22.04.3 LTS (GNU/Linux 5.15.0-86-generic x86_64) clean installation deb 3.4.1

**Comment by imbeacon** [comment]
Hi @pro100805,

You are right in case of service installation we are using system environment to install the package.
