### ISSUE TITLE
Custom timestamp when using mqtt

### ISSUE THREAD

**Issue by chatper** [thingsboard/thingsboard-gateway#12]
I think it should be possible to set custom timestamps when using mqtt (or other backends), not just using the one that corresponds to when the message arrives to the gateway.

**Comment by AlexanderJP91** [comment]
Is there any update about this issue? I noticed that in the new development branch the timestamp mapping has been added

**Comment by AlexanderJP91** [comment]
I forked the repo and added the possibility of having client-side (custom) timestamp using mqtt. Made a pull request for it, but still not approved. For the moment you can find it on my personal repos

**Comment by mp-loki** [comment]
Merged [#55](https://github.com/thingsboard/thingsboard-gateway/pull/55).
