### ISSUE TITLE
OPC UA extension - NPE when None security 

### ISSUE THREAD

**Issue by mike0sv** [thingsboard/thingsboard-gateway#120]
The problem is at org.thingsboard.gateway.extensions.opc.OpcUaServerMonitor:85 - you try to load certificates even if security policy is "None" and since there is no certs, it yields NPE.

I configured extension from GUI, and I noticed that even when you choose "None" security policy (and GUI hides cert configuration), gateway still receives leftover configuration in the keystore field. In my case there was null value in the fileContent field, which got me this NPE.

**Comment by mp-loki** [comment]
@mike0sv Thank you for pointing this. This is a known issue and it will be fixed in next minor release.

**Comment by mp-loki** [comment]
Fixed
https://github.com/thingsboard/thingsboard-gateway/releases/tag/2.1.1
