### ISSUE TITLE
[BUG] Configs sync When using remote configuration feature

### ISSUE THREAD

**Issue by Jonnik84** [thingsboard/thingsboard-gateway#1211]
Configs, that are located in TBGW configs folder do not apear in TB at all.
If I create new config on TB server, new config.json file is successfully created on gateway and sync TB--->TBGATEWAY works...till gateway is restarted. 

After restarting the gateway (start stop container for example), if I make changes in already created configs on TB side , they will not appear in TBGW

**Comment by imbeacon** [comment]
Hi @Jonnik84,

This issue is fixed in the master branch and in existing release, you can use the both variants.
