### ISSUE TITLE
[HELP] Offline instalation

### ISSUE THREAD

**Issue by LukaszDuss** [thingsboard/thingsboard-gateway#1217]
**Describe the issue**
I can't install gateway using docker on offline vm 

I had downloaded docker image but container still needs connection to internet to update linux and python packages. 
![image](https://github.com/thingsboard/thingsboard-gateway/assets/42135726/f2dcf534-ca9e-4162-9eea-99d58a4ad404)

Does anyone have some kind of workaround?

**Versions (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - Thingsboard IoT Gateway version [3.4.2]

**Comment by samy4sam** [comment]
I'm struggling with exactly the same problem.
![image](https://github.com/thingsboard/thingsboard-gateway/assets/42201209/c8ddfcce-6bf6-4628-bb46-8f7228781dca)

The connectivity tests for http:
``curl -v -X POST http://<LOCAL_IP>:8080/api/v1/<TOKE>/telemetry --header Content-Type:application/json --data "{temperature:25}"``
and mqtt:
``mosquitto_pub -d -q 1 -h <LOCAL_IP> -p 1883 -t v1/devices/me/telemetry -u <TOKEN> -m "{temperature:25}"``
work without any problems.

As a temporary fix, I installed Thingsboard Gateway with pip without Docker: [Installation Guide](https://thingsboard.io/docs/iot-gateway/install/pip-installation/)

**Comment by imbeacon** [comment]
Hi,

The first installation and configuration require an internet connection to download the required packages, unfortunately, it cannot be changed.
