### ISSUE TITLE
[BUG] TB Gateway 3.4.2 + Docker on RPI4

### ISSUE THREAD

**Issue by elgutierrez** [thingsboard/thingsboard-gateway#1223]
**Describe the bug**
I'm trying to run `tb-gateway` on RPI 4 using docker. I'm pulling the latest image (3.4.2), but when I run the `docker run` command, I get  `exec /bin/sh: exec format error`

**Error traceback (If available):**
```
sudo docker run -it   -v ~/.tb-gateway/logs:/thingsboard_gateway/logs   -v ~/.tb-gateway/extensions:/thingsboard_gateway/extensions   -v ~/.tb-gateway/config:/thingsboard_gateway/config   --name tb-gateway --restart unless-stopped   thingsboard/tb-gateway

exec /bin/sh: exec format error
```

**Versions (please complete the following information):**
 - OS: Raspbian
 - Thingsboard IoT Gateway: 3.4.2

**Comment by Jonnik84** [comment]
Its because docker container is not made for Rpi. Pls guys, add Rpi container to official list.

**Comment by samy4sam** [comment]
I have the same problem. If you take a look at the [Thingsboard Gateway Docker images](https://hub.docker.com/r/thingsboard/tb-gateway/tags), you will see that the ARM architecture is no longer supported since version 3.4: 
![image](https://github.com/thingsboard/thingsboard-gateway/assets/42201209/8aba33e9-7418-43d0-be43-ee470c054167)

**Comment by elgutierrez** [comment]
Thanks @simenkid! I had to install from the sources as the latest release still have Bacnet issues but it might be useful in the future

**Comment by rajatksud** [comment]
this is because cryptography requires the rust compiler which can be installed by modifying the dockerfile 

`# Install Rust
RUN apt-get update && apt-get install -y curl && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $HOME/.bashrc && \
    /bin/bash -c "source $HOME/.bashrc" && \
    rustup update`
    
 The tb_updater.py file has import version and this module cannot be found

**Comment by rajatksud** [comment]
This is because rust compiler is not available within docker which is used by cryptography

**Comment by imbeacon** [comment]
Hi,

We have created a separated tag for RPi - tb-gateway:3.5.1-rpi, please try to use it instead of latest. Unfortunately, at the moment we cannot combine them.
