### ISSUE TITLE
[HELP] ODBC Connector

### ISSUE THREAD

**Issue by mica83** [thingsboard/thingsboard-gateway#1228]
Hello guys,

one simple question: Is it possible pass to methods a dynamic value coming from TB - shared attribute?

In the documentation i see some examples but just with fixed values as arguments:

"methods": [
{
  "name": "rpcProcOne",
  "args": [ "One", 2, 3.0 ],
  "query": "CALL procedureOne(?,?,?)"
},
{
  "name": "functionOne",
  "args": [ false ]
}
]

**Comment by imbeacon** [comment]
Hi @mica83,

Thank you for your interest in Thingsboard IoT Gateway.
Yes, it is possible - just add "overrideRpcConfig": true to serverSideRpc section and send configs in params for RPC method from ThingsBoard. Please let us know about the results.
