### ISSUE TITLE
OPC-UA telemetry data cannot be collected

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard-gateway#123]
hi，I used TB-gateay1.4 connection to OPC UA server, and the log showed that the connection was successful, but TB could not collect data.Hope everyone's help！
The log file is as follows：

[tb-gateway log.txt](https://github.com/thingsboard/thingsboard-gateway/files/2404524/tb-gateway.log.txt)

**opc-config.json：**
{
  "servers": [
    {
      "applicationName": "Thingsboard OPC-UA client",
      "applicationUri": "",
      "host": "127.0.0.1",
      "port": 4840,
      "scanPeriodInSeconds": 10,
      "timeoutInMillis": 5000,
      "security": "None",
      "identity": {
        "type": "anonymous"
      },
      "keystore": {
        "type": "PKCS12",
        "location": "example.pfx",
        "fileContent": "",
        "password": "secret",
        "alias": "gateway",
        "keyPassword": "secret"
      },
      "mapping": [
        {
          "deviceNodePattern": "Objects/sta0/Analog",
          "deviceNamePattern": "AB",
           "attributes":[
             {
               "key": "Boolean val",
               "type": "LONG",
               "value":"${analog1}"

             }
           ],

          "timeseries":[
            {
              "key": "Double Val",
              "type":"LONG",
              "value":"${analog2}"
            }
          ]
        }
      ]
    }
  ]
}

![a](https://user-images.githubusercontent.com/30205233/45869863-23631f00-bdbc-11e8-8de3-72f732f684fc.png)

**Comment by mp-loki** [comment]
"deviceNodePattern" in the config file maps to the Device ID on the OPC-UA server, not the fqn. 
In your case the ID is `station_sta0.analog.analogX`, so I think the correct deviceNodePattern will be
`station_sta0\\.analog\\.analog\\d`

```log
16:06:18.199 [main] TRACE o.t.g.e.opc.OpcUaServerMonitor - Scanning node: OpcUaNode(nodeId=NodeId{ns=1, id=station_sta0.analog}, name=Analog, fqn=Objects.sta0.Analog)
16:06:18.205 [main] TRACE o.t.g.e.opc.OpcUaServerMonitor - Scanning node: OpcUaNode(nodeId=NodeId{ns=1, id=station_sta0.analog.analog0}, name=analog0, fqn=Objects.sta0.Analog.analog0)
16:06:18.212 [main] TRACE o.t.g.e.opc.OpcUaServerMonitor - Scanning node: OpcUaNode(nodeId=NodeId{ns=1, id=station_sta0.analog.analog1}, name=analog1, fqn=Objects.sta0.Analog.analog1)
```
