### ISSUE TITLE
How to control a device remotely via a tb-gateway?

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard-gateway#124]
I noticed in TB's architecture diagram that there are two-way arrows between TB-GATEWAY and TB.Then, can TB control remote devices through tb-gateway?.As described in the tutorial, TB can control the Raspberry Pi 3 remotely, but Raspberry Pi 3 is directly listening to TB services.If Raspberry Pi 3 is used to connect to TB-gateway and then to TB, how to achieve remote control?I now need to connect the device through the tb-gateway, and the device cannot directly access TB.Who can help me

https://thingsboard.io/docs/samples/raspberry/gpio/

![1](https://user-images.githubusercontent.com/30205233/46252270-37cca900-c499-11e8-894c-c70e20a6e1ab.png)

**Comment by adamfadil** [comment]
Hi,
yes with MQTT Extension, TB can control remote devices through tb-gateway.
you can first install tb-gateway on your Raspberry Pi 3, then you can follow this link https://thingsboard.io/docs/iot-gateway/mqtt/
Regards
