### ISSUE TITLE
[HELP] MQTT converter

### ISSUE THREAD

**Issue by LibraLY** [thingsboard/thingsboard-gateway#1240]
**Describe the issue**
After updating Gateway to version 3.4.3, I am unable to parse nested JSON.

**Connector name (If you need help with some connector/converter):**
MQTT Connector

**Error traceback (If it was raised):**
For example, if the JSON is {"a":{"b":value,"c":value}}, previously I could get the value of b through ${a.b}，now it will return just " ${a.b}"

**Versions (please complete the following information):**
 - docker
 - Thingsboard IoT Gateway version [3.4.3]

**Comment by imbeacon** [comment]
Hi @LibraLY,

Thank you for your interest in Thingsboard IoT Gateway.
You are right, there was an issue with JsonExpression parsing, please try to use a version from the master or wait for the release.
