### ISSUE TITLE
[BUG] OPC-UA Variables that have another variable as a parent are not found.

### ISSUE THREAD

**Issue by samy4sam** [thingsboard/thingsboard-gateway#1249]
**Describe the bug**
In industry, it is often the case that manufacturers such as Siemens offer ready-made OPC-UA interfaces. With these interfaces, it often happens that variables are set as sub-variables of other variables. 
For example, value1 and value2 are sub-variables of the variable values:

![image](https://github.com/thingsboard/thingsboard-gateway/assets/42201209/46e6230b-4e48-42e4-acd3-c18f58c40e76)

However, the current implementation of _**opcua_connector.py**_ ignores such sub-variables if they are mapped with an absolute or relative path. With namespace and identifier, however, they are found without any problems.

If the **___search_node_** function is adapted as follows, sub-variables are also taken into account:

``` python
if regex_search:
 if self.__show_map:
     self._log.debug("SHOW MAP: Current node path: %s - NODE FOUND", new_node_path)
 if new_node_class == ua.NodeClass.Object:
     if self.__show_map:
         self._log.debug("SHOW MAP: Search for %s in %s", fullpath, new_node_path)
     self.__search_node(child_node, fullpath, result=result)
 elif new_node_class == ua.NodeClass.Variable:
     if self.__show_map:
         self._log.debug("SHOW MAP: Search for %s in %s", fullpath, new_node_path)
     self.__search_node(child_node, fullpath, result=result)
 elif new_node_class == ua.NodeClass.Method and search_method:
     self._log.debug("Found in %s", new_node_path)
     result.append(child_node)                  
```
Can this change be included in the next version? It would improve the industrial suitability of the IoT gateway.
I have tested the modification with a simulation environment under Windows.

Pull request: #1251 

**Connector name:**
OPC-UA Connector

**Versions (please complete the following information):**
 - OS: Windows
 - Thingsboard IoT Gateway version: 3.4.3.1
 - Python version[e.g. 3.7]

**Comment by SimoneG97** [comment]
This might be related to #1021
