### ISSUE TITLE
RPC requests through tb gateway with MQTT

### ISSUE THREAD

**Issue by lorenzomicheletti** [thingsboard/thingsboard-gateway#125]
Hello, i'm pretty new to thingsboard and i'm struggling with RPC commands passing through the tb gateway: 
i've set up thingsboard and tb-gateway services on the same machine, the gateway is using an external MQTT broker and it seems to work fine as i'm able to send telemetry data and attributes via posting to the external broker.
I've made a mqtt-config file similar to the one present on the online documentation, and left the serversideRpc config exactly the same:

`{
...
      "serverSideRpc": [
        {
          "deviceNameFilter": ".*",
          "methodFilter": "echo",
          "requestTopicExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
          "responseTopicExpression": "sensor/${deviceName}/response/${methodName}/${requestId}",
          "responseTimeout": 10000,
          "valueExpression": "${params}"
        },
        {
          "deviceNameFilter": ".*",
          "methodFilter": "no-reply",
          "requestTopicExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
          "valueExpression": "${params}"
        }
      ]
...
}`

Giving a look at the tb-gateway log it seems like the gateway service isn't even getting any input of any RPC commands i send and the external broker isn't getting any messages, but connecting directly at the device and subscribing at "v1/devices/me/rpc/request/+" i can see that the command is correctly issued.
Is there something wrong with the configuration section or is there something i'm not understanding of how it is supposed to work?
Hope you can help, and thanks in advance!

[thingsboard.log](https://github.com/thingsboard/thingsboard-gateway/files/2472667/thingsboard.log)
[tb-gateway.log](https://github.com/thingsboard/thingsboard-gateway/files/2472668/tb-gateway.log)

**Comment by colognebroker** [comment]
did you find a solution ?
i have the same problem

**Comment by initialChris** [comment]
I have the same problem

**Comment by wangdongyi1** [comment]
I am meeting the same problem

**Comment by Dionisseus** [comment]
Same things. Only way  to make it work is to create a rule node with the mqtt object but is not the ideal solution as it should be embedded into the gateway. mm..

**Comment by zbeacon** [comment]
Hi, @lorenzomicheletti , @initialChris , @wangdongyi1 , @Dionisseus 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
Less footprint and memory impact
Easier to extend and customize
Improved functionality.

If your request is still relevant, i can help you. You should try to use a new gateway, to solve this problem. Main flow of RPC requests from ThingsBoard to broker over the gateway is:
ThingsBoard sends RPC request to the gateway -> The gateway checks it configuration -> gateway sends data to topic in configuration. About configuration for MQTT you can read more here.

For example:
If you want send RPC request from to broker on 127.0.0.1, device name is "SN-0002" and you use [demo.thingsboard.io](http://demo.thingsboard.io), you should configure the gateway using [this guide](https://thingsboard.io/docs/iot-gateway/getting-started/) and [configure a MQTT connector](https://thingsboard.io/docs/iot-gateway/config/mqtt/). You should add to a section "serverSideRpc" in the mqtt configuration file following strings:

    {
      "deviceNameFilter": ".*",
      "methodFilter": "no-reply",
      "requestTopicExpression": "/sensor/${deviceName}/request/${methodName}/",
      "valueExpression": "${params}"
    }

If the gateway receives RPC request to device with this configuration, it will send data from RPC "params" to topic "/sensor/SN-0002/request/no-reply/" on external broker.
