### ISSUE TITLE
Repeated forwarding of the last data prior to a connection loss

### ISSUE THREAD

**Issue by nmenoni** [thingsboard/thingsboard-gateway#126]
I am using the tb-gateway 2.0.4 and TB 2.1.3. I have experienced that when a connection loss occurs and the gateway has to accumulate messages while the thingboards is unreachable, when recovering the connection and sending all the data queued, everything worked correctly except that **it keeps resending the last data prior to the outage**, which means that if you have a last value widget in a dashboard, this last value changes every time the old data is forwarded.

When the old data is forwarded, the log level in the tb-gateway shows:

`2018-10-19 19:39:27,280 [nioEventLoopGroup-2-63] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalStateException: complete already: DefaultPromise@ec1b79(failure: java.util.concurrent.CancellationException)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:97)
	at nl.jk5.mqtt.MqttChannelHandler.handlePuback(MqttChannelHandler.java:215)
	at nl.jk5.mqtt.MqttChannelHandler.channelRead0(MqttChannelHandler.java:37)
...`

and 

`2018-10-19 19:39:32,679 [pool-3-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress`

**It's like the queue never ends emptying**.

**Comment by zbeacon** [comment]
Hi, @nmenoni 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
Less footprint and memory impact
Easier to extend and customize
Improved functionality.

You can try using a new gateway for your purposes instead of a Java gateway.
