### ISSUE TITLE
[HELP] Assigning devices to Customers using HTTP endpoint

### ISSUE THREAD

**Issue by dmohns** [thingsboard/thingsboard-gateway#1261]
**Describe the issue**

Is it possible to write a Thingsboard IoT gateway HTTP point that assigns a devices (based on some filter values) to a customer? Unfortunately, I couldn't find an information about it.

**Configuration** (Attach your configuration file)
N/A

**Connector name (If you need help with some connector/converter):**
HTTP Connector

**Error traceback (If it was raised):**
N/A

**Versions (please complete the following information):**
 - OS: k8s
 - Thingsboard IoT Gateway version: `3.4.3.1`
 - Python version: `3.9`

**Comment by devaskim** [comment]
There is no such functionality and, I think, the better place for such purpose is server's rule engine. You can catch `Entity Created` (and maybe `Connected Event`) and then assign device with the help of `Assign To Customer` rule node.
