### ISSUE TITLE
TB gateway transfer data to other platform

### ISSUE THREAD

**Issue by Jzhenli** [thingsboard/thingsboard-gateway#1262]
Hi, I want to know if it's possible to use TB gateway as a general gateway, just collect data and then transfer them with HTTP to a private web?  Thanks.

**Comment by samson0v** [comment]
Hi @Jzhenli, thanks for your interest in ThingsBoard IoT Gateway!
You can only transfer data from the gateway to the ThingsBoard server (cloud or local).
