### ISSUE TITLE
[BUG] OPC-UA Connector refuses Connection after restart

### ISSUE THREAD

**Issue by samy4sam** [thingsboard/thingsboard-gateway#1264]
**Describe the bug**
After restarting the gateway, the OPC-UA Connector refuses the connection.
If I disable and enable the connector manually in the Connectors View, the connection to the OPC-UA server works.

However, I expect the gateway to attempt to re-establish the connection after a certain amount of time without me having to intervene manually.

**Connector name (If bug in the some connector):**
 OPC-UA Connector

**Error traceback (If available):**
![image](https://github.com/thingsboard/thingsboard-gateway/assets/42201209/386117ac-5798-47cf-9cee-849970f3f443)

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04
 - Thingsboard IoT Gateway version: 3.4.3.1

**Comment by samson0v** [comment]
Hi @samy4sam, thanks for your interest in ThingsBoard IoT Gateway!
We were trying to reproduce your problem but in our case, Gateway does reconnect automatically. 
Try to use the latest version from the master branch and let us know about the result.
