### ISSUE TITLE
[HELP WANTED] Data Already successfully send in TB device (Gateway), but my sensor still cannot get telemetry data

### ISSUE THREAD

**Issue by yinghai97** [thingsboard/thingsboard-gateway#1266]
I able to run thingsboard-gateway in CLI
![image](https://github.com/thingsboard/thingsboard-gateway/assets/32979739/56942a44-cf26-4bc0-83f0-6ace75444136)

and I successfully get some info from gateway 
![image](https://github.com/thingsboard/thingsboard-gateway/assets/32979739/29559e46-ffd5-4906-b258-0cd8a24acf6e)

but I the data did not send to my sensor device
![image](https://github.com/thingsboard/thingsboard-gateway/assets/32979739/b3a81f83-8706-48c7-a143-7c238ef269af)

Am I do something incorrectly? 

[modbus.json](https://github.com/thingsboard/thingsboard-gateway/files/13726451/modbus.json)
[tb_gateway.json](https://github.com/thingsboard/thingsboard-gateway/files/13726452/tb_gateway.json)

**Comment by yinghai97** [comment]
![image](https://github.com/thingsboard/thingsboard-gateway/assets/32979739/ca5fc3a7-e1f3-4075-ae56-c5c655c4540c)
I solved the problem by add this in shared attribute.
But I not sure whether is correct way.

you may close this post if this is the correct way
thankyou

**Comment by DuXiaoChuang** [comment]
![image](https://github.com/thingsboard/thingsboard-gateway/assets/149569575/aab77621-809f-43d7-a2e5-de32d2641e25)
![image](https://github.com/thingsboard/thingsboard-gateway/assets/149569575/76c5e4fd-f89a-480e-8046-7713d2f23b14)
 My question is the same as yours，"Can you help me take a look at my question, just like yours?"

**Comment by imbeacon** [comment]
Closed, due to inactivity, should be solved in one of the latest releases.
