### ISSUE TITLE
[BUG] In the latest telemetry data, the leading digit is 0, it will not be displayed.

### ISSUE THREAD

**Issue by Zhuoyuan1** [thingsboard/thingsboard-gateway#1269]
**Describe the bug**
In the latest telemetry data, when a key's value is of type string and the leading digit is 0, it will not be displayed.

**Connector name (If bug in the some connector):**
MQTT Connector

**Error traceback (If available):**
![1](https://github.com/thingsboard/thingsboard-gateway/assets/41421622/97641e8d-82e6-40cd-9e8b-1edffac4e6d1)
![2](https://github.com/thingsboard/thingsboard-gateway/assets/41421622/8516a06c-d93b-43e7-90da-f85875ba3f5f)
![3](https://github.com/thingsboard/thingsboard-gateway/assets/41421622/0aad2ff9-3ff4-4829-bc59-e82a4de5568c)

**Versions (please complete the following information):**
 - OS: Ubuntu 22.04
 - Thingsboard IoT Gateway version 3.4.3.1
 - Python version 3.11.6

**Comment by imbeacon** [comment]
Hi @Zhuoyuan1,

This issue doesn't relates to the gateway, it sends the correct data, but conversion in ThingsBoard - removes the leading 0.
