### ISSUE TITLE
there is no proper version of netty-mqtt for thingsboard-gateway compilation

### ISSUE THREAD

**Issue by hawkwang** [thingsboard/thingsboard-gateway#127]
2.0.0TB is needed, but current is 2.0.1TB

**Comment by mp-loki** [comment]
You can update the TB version in your thingsboard-gateway/pom.xml

**Comment by stieuquy** [comment]
@mp-loki  there is compile error when I use netty-mqtt v2.0.1TB.
Because of **create** method the class **MqttClient**. In v2.0.0TB the method have only one argument, but with v2.0.1TB it has two arguments

**Comment by stieuquy** [comment]
@felix-ma officially not, I just temporary implement (write a warning log) these methods base on API document.

**Comment by mp-loki** [comment]
Build netty-mqtt from our repository first:
https://github.com/thingsboard/netty-mqtt

**Comment by mp-loki** [comment]
In ThingsBoard v2.2 netty-mqtt is included in the main project, so now you don't have to build netty-mqtt separately. Just build ThingsBoard and then build thingsboard-gateway.
