### ISSUE TITLE
[HELP] socket connector ERROR 154 Address already is use.

### ISSUE THREAD

**Issue by william96c** [thingsboard/thingsboard-gateway#1271]
![2023-12-28_15-35](https://github.com/thingsboard/thingsboard-gateway/assets/130973006/10673372-bbc1-49c8-9e65-1b14d1a75b0b)

![2023-12-28_15-35_1](https://github.com/thingsboard/thingsboard-gateway/assets/130973006/902ccccb-f2b4-4e0f-959a-cd07f3f549cc)

**Versions (please complete the following information):**
 -  Ubuntu 20.04
 - Thingsboard IoT Gateway version 3.4.3
 - Python version 3.8

**Comment by imbeacon** [comment]
Hi @william96c,

Thank you for your interest in ThingsBoard IoT Gateway, please try the version from the master branch and let us know about the results, or you can wait for release.
