### ISSUE TITLE
[HELP] Gateway disconnect and connect every some msec

### ISSUE THREAD

**Issue by Tasosgi** [thingsboard/thingsboard-gateway#1286]
I can send telemetry data to platform but the gateway disconnect and connect every some msec. It seems that it tries to subscribe to attributes without success.

<img width="1825" alt="gateway" src="https://github.com/thingsboard/thingsboard-gateway/assets/31473443/6f1de752-2615-472b-a35d-1e47d0913dda">

[modbus_serial.txt](https://github.com/thingsboard/thingsboard-gateway/files/14076826/modbus_serial.txt)
[tb_gateway.json.txt](https://github.com/thingsboard/thingsboard-gateway/files/14076827/tb_gateway.json.txt)

**Comment by imbeacon** [comment]
Hi @Tasosgi,

Usually disconnect with this reason code appears if you have already connected gateway with the same credentials, could you try to generate a new accessToken and use it?

**Comment by Tasosgi** [comment]
Hello, yes I have seen that in other cases. But in this case there isn't another gateway or device online. Anyway I will check it today.

Another strange think I see in this version is that if I don't put the "type": "serial" **before** "master" my configuration file don't works and the gateway use the default one. According to the examples it must  be under "slaves". I have attach my configuration files

**Comment by imbeacon** [comment]
Ok, another option is rate limits, could you check your notifications on the platform - don't you have a message like "Rate limits exceeded?

**Comment by Tasosgi** [comment]
No message like this. This platform hasn't big load. There was a traffic yesterday when I tested the gateway but I think because the repeatedly connect - disconnect procedure.

 
![API usage](https://github.com/thingsboard/thingsboard-gateway/assets/31473443/fb3a234a-8fcb-446a-83c5-cfbd2cec55bb)

**Comment by imbeacon** [comment]
@Tasosgi I mean notification (bell icon in the top panel), there is rate limits per device on ThingsBoard level. And if you restart the gateway 3 or 4 times per minute - it may be triggered.

**Comment by Tasosgi** [comment]
Thanks to the help of @imbeacon I found the problem. I had gave the same name to the gateway, when I created it in the platform, and the slave, in the modbus configuration file
