### ISSUE TITLE
source compilation error with v2.0.4-draft1

### ISSUE THREAD

**Issue by bilelkhedira** [thingsboard/thingsboard-gateway#129]
Hi,
To sum up, i need thingsboard-gateway source code compatible with the thingsboard-2.0.4
but when trying to compile thingsboard-gateway v2.0.4-draft1, i have this error MqttQoS cannot be resolved to a variable (The import io.netty.handler.codec.mqtt cannot be resolved)
I found some others compilation errors  
[ERROR] D:\IOT Project src\thingsboard-gateway\src\main\java\org\thingsboard\gateway\service\gateway\MqttGatewayService.java:[101,30] GraphicsPrimitive is internal proprietary API and may be removed in a future release

Any idea on this issue ?
Thanks

**Comment by mp-loki** [comment]
Please check out and build our fork of netty-mqtt first: https://github.com/thingsboard/netty-mqtt
