### ISSUE TITLE
[BUG] preserve JSON type in attributeUpdates for MQTT

### ISSUE THREAD

**Issue by Fishwaldo** [thingsboard/thingsboard-gateway#1295]
**Describe the issue**
Is there a way to preserve the json type of a attribute when sending via the MQTT broker?

eg, if I define two shared attributes on my device:
test1 - string
test2 - integer

and modify those values, then the attributeValue is either only enclosed in quotes or not, depending upon the valueExpression in the in the attributeUpdates block of my configuration:
```
   {
      "retain": false,
      "deviceNameFilter": "SN.*",
      "attributeFilter": "test.*",
      "topicExpression": "sensor/${deviceName}/${attributeKey}",
      "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"
    }
```

what I would like to do, it only add the quotes around the attributeValue if its a string, and not for other json types (eg, integer or float)

if I remove the quotes around $attributeValue like such:
```
      "valueExpression": "{\"${attributeKey}\":${attributeValue}}"
```
then string based shared attributes cause a JSON syntax error when parsing due to lack of " (and likewise for integer/bool etc types when adding quotes)

**Comment by imbeacon** [comment]
Hi @Fishwaldo,

Thank you for your interest in ThingsBoard IoT gateway, it is a bug, we will fix it.

**Comment by Fishwaldo** [comment]
Thanks. I believe the same issue will exist with the attributeRequests as well? (as in the reply posted back to a request)

**Comment by imbeacon** [comment]
Probably yes, because we are using strings to form payload, we will add additional conversion to MQTT connector to avoid this situation.

**Comment by imbeacon** [comment]
Hi @Fishwaldo,

We have added a fix for this in the master branch, you may try it or wait for the release.

**Comment by Fishwaldo** [comment]
Hi,
Sorry, I don't see the commit where it's fixed?

**Comment by imbeacon** [comment]
You may check on_attribute_update method in Matt_connector in bdbf1807.
