### ISSUE TITLE
[BUG] Wrong check hasattr(self, '_TBGatewayService__statistics_service')

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard-gateway#1298]
**Describe the bug**

The attribute `statistics_service` always [exists](https://github.com/thingsboard/thingsboard-gateway/blob/master/thingsboard_gateway/gateway/tb_gateway_service.py#L304), but it could be initialized or `None`

**Comment by imbeacon** [comment]
Hi @devaskim,

Thank you for your participating in the project life, you are right, added fix in c844839
