### ISSUE TITLE
[BUG] Thingsboard IoT Gateway unresponsive at high sample rates

### ISSUE THREAD

**Issue by andreasmatz1** [thingsboard/thingsboard-gateway#1333]
**Describe the bug**
Dear Thingsboard team,

I have connected a Modbus device to Thingsboard Cloud v3.6.2 via the IoT gateway v3.4.4. I am reading 4 Modbus registers at sampling rates of 50…200Hz. I found that when I exceed a certain sampling rate, the IoT gateway becomes unresponsive from the ThingsBoard cloud. 

In this situation disabling the connector does not stop the gateway from sending modbus requests to the device, and changing the connector configuration reports “successfully updated”, but does not actually change the configuration on the IoT gateway.

Is this expected behavior? How can I avoid it? Reducing the sampling rate is not possible unfortunately, since the process I am monitoring requires quick data collection.

The IoT gateway runs on a Khadas VIM 1 board with a 1.5GHz quad-core ARM-A53 CPU, which shows about 25% load on all cores at the mentioned sample frequencies. Data is forwarded via WiFi to thingsboard cloud.

Best regards
Andreas Matz

**Connector name (If bug in the some connector):**
Modbus Connector

**Error traceback (If available):**
none observed

**Versions (please complete the following information):**
 - OS: Ubuntu 22.04
 - Thingsboard Cloud 3.6.2
 - Thingsboard IoT Gateway version 3.4.4
 - Python version 3.10.12

**Comment by skewty** [comment]
The GW as written by ThingsBoard is very basic in implementation and is sadly synchronous in nature so it is unlikely to scale well for your use case.

Try running multiple instances of the GW and reference a sub-set of your devices per GW instance.

**Comment by samson0v** [comment]
Hi @andreasmatz1, this bug was fixed. 
Please, wait until the next release (~1 week) and try to use the new version. 
After that let us know about the result.

**Comment by andreasmatz1** [comment]
Hi @samson0v , I have not yet been able to test the new gateway version myself - but I have built one for a colleague, I will ask him about the improvements.

**Comment by skewty** [comment]
> Hi @skewty, any updates?

Thank you for the opportunity to respond but we have written our own gateways to work around issues we had with the upstream one. I am no longer in a position to comment on this issue beyond my familiarity with the source code / project.

**Comment by samson0v** [comment]
@andreasmatz1 any updates from your colleague or you?

**Comment by andreasmatz1** [comment]
Not yet. We are currently moving the welding cell where I did the experiments, I can try again once it is setup again in the new building.
