### ISSUE TITLE
[BUG] Multiple connections opened on one serial port

### ISSUE THREAD

**Issue by khoahoangqenergy** [thingsboard/thingsboard-gateway#1336]
**Describe the bug**
Clear and concise description of what the bug is.
When we have multiple devices daisy chained - with different modbus device IDs, under the same serial port, we have to make several slaves in modbus_serial.json config. However, we notice that for every slave instance, Thingsboard IoT Gateway opens up a new connection in the serial port, causing congestion and sometimes a delay in data being read on these devices under the same serial port.
**Connector name (If bug in the some connector):**
[Modbus Serial Connector]

**Versions (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Thingsboard IoT Gateway version [3.4.3]
 - Python version[3.10]

**Comment by imbeacon** [comment]
Hi @khoahoangqenergy,

This issue fixed in the master branch, please try to use it or wait for the release.
