### ISSUE TITLE
[HELP] Converting MQTT JSON data arrays

### ISSUE THREAD

**Issue by andreasmatz1** [thingsboard/thingsboard-gateway#1338]
**Describe the issue**
I have a device that samples measurement data and sends JSON over MQTT messages containing the timestamp of the first sample and 100 samples of the measurement. All samples after the first are offset by N x 10 ms for a sampling rate of 100Hz. The format is as follows:

{"dt":"2022-11-17 15:07:09","value1":[1,4,2,4,5,7,7,8,...]}  <-- 100 values per message

I have successfully written a data converter in ThingsBoard that converts this data JSON messages to individual values with correct timestamps:
{"dt":"2022-11-17 15:07:09.000","value1":"1"}
{"dt":"2022-11-17 15:07:09.010","value1":"4"}
{"dt":"2022-11-17 15:07:09.020","value1":"2"}
etc.

I would like to connect this device to the TB IoT gateway and do the same conversion as above. However, I think there is no scripting ability in the converter, which makes processing long arrays challenging. What would be the correct way to deal with this format?

**Configuration** (Attach your configuration file)
none yet for MQTT connector

**Connector name (If you need help with some connector/converter):**
MQTT Connector

**Error traceback (If it was raised):**
none

**Versions (please complete the following information):**
 - OS: Ubuntu 22.04
 - Thingsboard IoT Gateway version 3.4.4
 - Python version 3.10.12

**Comment by devaskim** [comment]
> I think there is no scripting ability in the converter, which makes processing long arrays challenging

It is possible. You need to [develop custom converter](https://thingsboard.io/docs/iot-gateway/config/mqtt/?MqttConverterTypeConfig=custom#subsection-converter) and add it to `extension` folder of gateway.
