### ISSUE TITLE
[BUG] Gateway's connector stopped in case of slight connection problems

### ISSUE THREAD

**Issue by salvogs** [thingsboard/thingsboard-gateway#1339]
Sometimes, during night, i have connection problems outside my 
Ubuntu 22.04 VM hosting thingsboard (3.6.2) + gateway (3.4.4) with docker.

So, in the morning, i find out that my connectors is stopped.

This happening in both MQTT and MODBUS connectors with error log:
"[modbus.connector.py] - modbus_connector - 312 - 'Connector Name' has been stopped."
where, in my case, 'Connector Name' -> Inverters.

![Schermata del 2024-03-18 18-22-23](https://github.com/thingsboard/thingsboard-gateway/assets/49165064/6ce69542-16aa-43d8-853b-a528746daeb3)

**Comment by imbeacon** [comment]
Hi @salvogs,

Thank you, for your interest in ThingsBoard IoT Gateway.
Please try to use the latest version, it should work fine and write more information about why the connector was stopped.
If you encounter the same issue again - feel free to open a new issue.
