### ISSUE TITLE
[BUG] OPC-UA AsyncIO does not find sub variables

### ISSUE THREAD

**Issue by samy4sam** [thingsboard/thingsboard-gateway#1354]
**Describe the bug**
The OPC-UA AsyncIO connector does not find sub variables like the OPC-UA Connector.

- Old issue: [https://github.com/thingsboard/thingsboard-gateway/issues/1249](https://github.com/thingsboard/thingsboard-gateway/issues/1249)

- Old Pull request: [https://github.com/thingsboard/thingsboard-gateway/pull/1251](https://github.com/thingsboard/thingsboard-gateway/pull/1251) 

**Connector name (If bug in the some connector):**
OPC-UA AsyncIO Connector

**Versions (please complete the following information):**
 - OS: Docker
 - Thingsboard IoT Gateway version: 3.4.6

**Comment by samy4sam** [comment]
@samson0v @imbeacon any news on this bug?

**Comment by samson0v** [comment]
Hi @samy4sam,
I tried to reproduce your issue but I can't.
I have the following OPC-UA structure:
<img width="333" alt="image" src="https://github.com/thingsboard/thingsboard-gateway/assets/43861229/f65b4557-210d-44cd-a10c-b1f1db9b487f">

I trying to read **CounterSubVar**, for this purpose I used the following connector config:
```json
"mapping": [
      {
        "deviceNodePattern": "Root\\.Objects\\.Simulation",
        "deviceNamePattern": "Device asd",
        "attributes": [],
        "timeseries": [
          {
            "key": "humidity_sub",
            "path": "${Test\\.Counter\\.CounterSubVar}"
          }
        ],
      ....
```

And as you can see, sub variable read successfully:
<img width="468" alt="image" src="https://github.com/thingsboard/thingsboard-gateway/assets/43861229/d8ca7c94-3f6e-4dce-879e-19e41d4101c1">
