### ISSUE TITLE
Modbus TCP |ERROR| - [tb_logger.py] - tb_logger - exception - 98 - Exception Response(131, 3, IllegalAddress)[HELP]

### ISSUE THREAD

**Issue by DuXiaoChuang** [thingsboard/thingsboard-gateway#1360]
**Describe the issue**
Modbus TCP |ERROR| - [tb_logger.py] - tb_logger - exception - 98 - Exception Response(131, 3, IllegalAddress),，the tag 【Number of parts to be processed】‘s address is 62363  IllegalAddress。

**Configuration** (Attach your configuration file)
{
  "thingsboard": {
    "host": "thingsboard.cloud",
    "port": 1883,
    "remoteShell": false,
    "remoteConfiguration": true,
    "statistics": {
      "enable": true,
      "statsSendPeriodInSeconds": 3600
    },
    "deviceFiltering": {
      "enable": false,
      "filterFile": "list.json"
    },
    "maxPayloadSizeBytes": 1024,
    "minPackSendDelayMS": 200,
    "minPackSizeToSend": 500,
    "checkConnectorsConfigurationInSeconds": 60,
    "handleDeviceRenaming": true,
    "security": {
      "type": "accessToken",
      "accessToken": "s3iCKjoOySphGFoG5oOZ"
    },
    "qos": 1,
    "checkingDeviceActivity": {
      "checkDeviceInactivity": false,
      "inactivityTimeoutSeconds": 200,
      "inactivityCheckPeriodSeconds": 500
    }
  },
  "storage": {
    "type": "memory",
    "read_records_count": 100,
    "max_records_count": 100000,
    "data_folder_path": "./data/",
    "max_file_count": 10,
    "max_read_records_count": 10,
    "max_records_per_file": 10000,
    "data_file_path": "./data/data.db",
    "messages_ttl_check_in_hours": 1,
    "messages_ttl_in_days": 7
  },
  "grpc": {
    "enabled": false,
    "serverPort": 9595,
    "keepaliveTimeMs": 10000,
    "keepaliveTimeoutMs": 5000,
    "keepalivePermitWithoutCalls": true,
    "maxPingsWithoutData": 0,
    "minTimeBetweenPingsMs": 10000,
    "minPingIntervalWithoutDataMs": 5000,
    "keepAliveTimeMs": 10000,
    "keepAliveTimeoutMs": 5000
  },
  "connectors": [
    {
   "name": "Modbus Connector",
   "type": "modbus",
   "configuration": "modbus.json"
}]
}

**Connector name (If you need help with some connector/converter):**
[e.g. ModbusConnector]
{
  "master": {
    "slaves": [
      {
        "host": "192.168.1.4",
        "port": 502,
        "type": "tcp",
        "method": "socket",
        "timeout": 35,
        "byteOrder": "LITTLE",
        "wordOrder": "LITTLE",
        "retries": true,
        "retryOnEmpty": true,
        "retryOnInvalid": true,
        "pollPeriod": 5000,
        "unitId": 1,
        "deviceName": "沈阳机床",
        "sendDataOnlyOnChange": false,
        "connectAttemptTimeMs": 5000,
        "connectAttemptCount": 5,
        "waitAfterFailedAttemptsMs": 300000,
        "attributes": [
          {
            "tag": "CNC型号",
            "type": "string",
            "functionCode": 3,
            "objectsCount": 3,
            "address": 63001
          },
        ],
        "timeseries": [
          {
            "tag": "Number of parts to be processed",
            "type": "32int",
            "functionCode": 3,
            "objectsCount": 3,
            **"address": 62363**
          }
        ],
        "attributeUpdates": [
          {
            "tag": "shared_attribute_write",
            "type": "32int",
            "functionCode": 3,
            "objectsCount": 2,
            "address": 29
          }
        ],
        "rpc": [
          {
            "tag": "setValue",
            "type": "bits",
            "functionCode": 5,
            "objectsCount": 1,
            "address": 31
          },
          {
            "tag": "getValue",
            "type": "bits",
            "functionCode": 1,
            "objectsCount": 1,
            "address": 31
          },
          {
            "tag": "setCPUFanSpeed",
            "type": "32int",
            "functionCode": 16,
            "objectsCount": 2,
            "address": 33
          },
          {
            "tag": "getCPULoad",
            "type": "32int",
            "functionCode": 4,
            "objectsCount": 2,
            "address": 35
          }
        ]
      }
    ]
  },
  "id": "2c37dd3c-d968-4623-af70-b7c4b5b34a05"
}

![Uploading image.png…]()

**Versions (please complete the following information):**
 - OS: [windows]
 - Thingsboard IoT Gateway version 3.4.6
 - Python version 3.11.8

**Comment by mrangics** [comment]
Hi,

this means that you do not have such a register 62363. You have to check with a ModBus Reader like qModBus or something else, which is the correct register to read.
I think you should also check if you are reading the other values correctly, using the correct data type as I'm suspecting, that the 32int is not the correct data type, maybe 16uint or 32uint but a 32int is definitely surprising.

**Comment by DuXiaoChuang** [comment]
> Hi,
> 
> this means that you do not have such a register 62363. You have to check with a ModBus Reader like qModBus or something else, which is the correct register to read. I think you should also check if you are reading the other values correctly, using the correct data type as I'm suspecting, that the 32int is not the correct data type, maybe 16uint or 32uint but a 32int is definitely surprising.

ok，thank you ! you can close it .
