### ISSUE TITLE
[HELP] Can't get the latest telemtry data

### ISSUE THREAD

**Issue by Ziyor650** [thingsboard/thingsboard-gateway#1369]
**Describe the issue**
I am unable to check connectivity via getting data from latest telemetry

**Configuration** (Attach your configuration file)

**Connector name (If you need help with some connector/converter):**
[e.g. MQTT Connector]

Situation: I have successfully set up the network server, and i have set up my device in such a way that it is able to send the data to the network server. I am also able to set up mqtt broker, and connect it to my mqtt client for publishing and subscribing. 

this is to show that my iot device is able to communicate to my network server
![Image](https://github.com/thingsboard/thingsboard-gateway/assets/148713588/8e1ffa29-3bb7-4e92-8a7d-24e3def7d821)

The problem is when i want to check connectivity on my thingsboard devices section, i was able to send the data to the topic v1/devices/me/telemetry. but i do not receive it on my thingsboard devices latest telemetry

this is how i check connectivity on thingsboard CE, via [mosquitto_pub -d -q 1 -h 203.x.x.x -p 1883 -t v1/devices/me/telemetry -u "1or0ausqo2swjltvhyx" -m "{temperature:25}"]

This picture shows that i do not receive the manually inputed data on thingsboard Community Edition latest telemetry device page ![image](https://github.com/thingsboard/thingsboard-gateway/assets/148713588/8b1d0c76-c383-4ba7-9c3c-3d3e271b97f9)

This picture shows that i am able to receive the manually inputed data via the topic v1/devices/me/telemetry  ![image](https://github.com/thingsboard/thingsboard-gateway/assets/148713588/1bc4c8fe-7d35-48eb-920a-a23e3e11d1a2)

this is the output from the check connectivity [mosquitto_pub -d -q 1 -h 203.x.x.x -p 1883 -t v1/devices/me/telemetry -u "1or0ausqo2swjltvhyx" -m "{temperature:25}"]<- this is the command line i put into command prompt.

Client null sending CONNECT
Client null received CONNACK (0)
Client null sending PUBLISH (d0, q1, r0, m1, 'v1/devices/me/telemetry', ... (16 bytes))
Client null received PUBACK (Mid: 1, RC:0)
Client null sending DISCONNECT

'deviceName'
rak7204

**Versions (please complete the following information):**
 - OS: Windows 10
 - Thingsboard Community editiion v3.6.4
 - Network server: wisgate os

If you guys need more information please feel free to ask. 
I would really appreciate the help as i am so close but i do not know where i wernt wrong. 
From the bottom of my heart  thanks for taking a look at my issue

**Comment by imbeacon** [comment]
Hi @Ziyor650,

Unfortunately, this question doesn't relate to the gateway, so we cannot help you a lot. 
But it looks like you are trying to send a data that won't be parsed correctly ```"{temperature:25}"```, you need to send something like ```"{\"temperature\":25}"```.
