### ISSUE TITLE
[HELP]:  make Dynamic dashboard for 'Markers Placement'

### ISSUE THREAD

**Issue by kamisettychandan** [thingsboard/thingsboard-gateway#1378]
**Describe the issue**
**Aim**: I wants to make Dynamic dashboard for '**Markers Placement**'
I sent AHU telemetry to ThingsBoard Platform. AHU have Objects such as "**Temperature, Humidity, CO2, Pressure, Air Flow**"

**Please find below points:**
1. Selected 'Marker Placement Image Map Widget' in TB dashboard for multiple markers
2. As per ThingsBoard documentation, data source "**FUNCTION**" will not fetch telemetry from device for real-time scenario
3. If I used MQTT API, **JWT token** will be expire every 24 hours. so real-time its not possible
4. As per ThingsBoard Platform documentation, Developer should be use data source either **"DEVICE" or "ENTITY"**. But Multiple Markers are not showing
 
Kindly, help me to resolve issue
Please find snaps below for reference

![Type_Test](https://github.com/thingsboard/thingsboard-gateway/assets/58870266/4c7830b3-1f17-47ae-8bed-381850dfb982)
![Function_Test](https://github.com/thingsboard/thingsboard-gateway/assets/58870266/8d1ad222-3cd8-4051-be7b-dad017488fe1)
![jwt token](https://github.com/thingsboard/thingsboard-gateway/assets/58870266/ca0f9391-a4ff-4af0-b159-b00c9d6a2c2e)
![function](https://github.com/thingsboard/thingsboard-gateway/assets/58870266/2ac570e4-8dc6-458e-ae76-d8204d3e2105)

Kindly, guide me...Thanks in Advance

**Comment by imbeacon** [comment]
Hi @kamisettychandan,

Unfortunately, we cannot help you with this question, because it doesn't relate to the gateway. You can try to open an issue on main ThingsBoard [repository](https://github.com/thingsboard/thingsboard) or contact with support.
