### ISSUE TITLE
[BUG] Enabling or disabling the linker through platform gateway configuration causes devices under other linkers to be unable to communicate normally.

### ISSUE THREAD

**Issue by ultimate-smile** [thingsboard/thingsboard-gateway#1389]
**Describe the bug**
Different protocol devices are integrated through the platform. When the linker is closed using the platform, the previously controllable devices cannot be operated. In the case, mqtt is used to control the lights, and the opcua simulator simulates acquisition. When the opcua linker is closed, the lights cannot be controlled. Yes. The gateway becomes normal after hot restart.
.In addition, when closing the opcua linker and re-enabling the opcua linker, I found that the linker of the light in the connected_devices.json file under the gateway has been modified to the linker of opcua (normal light should maintain the linker of mqtt)
![image](https://github.com/thingsboard/thingsboard-gateway/assets/102498318/e651861a-7271-444b-a1cd-a3816ee13312)
![image](https://github.com/thingsboard/thingsboard-gateway/assets/102498318/7217aa21-652a-4ccf-9dc2-6b2ccdc3c5b8)

**Connector name (If bug in the some connector):**
[e.g. OPC-UA Connector]

**Error traceback (If available):**
```
'deviceName'
Traceback (most recent call last):
  File "<input>", line 2, in <module>
KeyError: 'deviceName'
```

**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Thingsboard IoT Gateway version [e.g. 3.6.4]
 - Python version[e.g. 3.10]

**Comment by imbeacon** [comment]
Hi, this point fixed in master branch, please use it or wait for next release.
