### ISSUE TITLE
POM Update

### ISSUE THREAD

**Issue by ssmaurya** [thingsboard/thingsboard-gateway#14]
paho client version 1.1.1 is now available in maven repo. POM can be updated now to use the same instead of 1.1.1-SNAPSHOT

**Comment by ssmaurya** [comment]
thingsboard version should also get updated to latest 1.2.3-SNAPSHOT for the build to be successful

**Comment by ashvayka** [comment]
Hi @ssmaurya , thanks for notice. We will do updates in a minute.
