### ISSUE TITLE
Error will be reported when installing Thboard-Gatewat according to the documentation

### ISSUE THREAD

**Issue by keyboardOut** [thingsboard/thingsboard-gateway#1407]
![Snipaste_2024-05-24_17-20-32](https://github.com/thingsboard/thingsboard-gateway/assets/132055558/ea4647cf-e40c-4ec5-9ffe-534c2c65dac6)

**Comment by samson0v** [comment]
Hi @keyboardOut, thanks for your interest in ThingsBoard IoT Gateway!
This bug was fixed. Try the version from the master branch.
