### ISSUE TITLE
[BUG] Abnormal rate limit with mqtt

### ISSUE THREAD

**Issue by yfPanne** [thingsboard/thingsboard-gateway#1408]
**Describe the bug**
The gateway has abnormal rate limit when connect to thingsboard by mqtt.
It is an logic caused bug, and in fact, it is a problem with the python-client-sdk repository.

**Error traceback (If available):**
The sleep function indicated by the arrow in the diagram below will always be cross-triggered.
That means the mqtt-sending rate will always be limited to 10 per second since the function `_publish_data` always `wait_for_publish`.
![image](https://github.com/thingsboard/thingsboard-gateway/assets/28749080/5ef6f00c-7594-47ed-8682-8bf3af74682a)
![image](https://github.com/thingsboard/thingsboard-gateway/assets/28749080/2e10b6dc-a6b3-46d3-9c0e-f4fbf80cf117)

**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Thingsboard IoT Gateway version [e.g. latest]
 - Python version[e.g. 3.11]

**Comment by imbeacon** [comment]
Hi @yfPanne,

This issue was solved in Python client SDK and it is available in the master branch of the SDK, you can try to use it or it will be also available in the nearest release of SDK.
