### ISSUE TITLE
Extensions configuration failed using TB GUI remote configuration

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard-gateway#141]
**tb-gateway.yml:**
server:
  # Server bind address
  address: "0.0.0.0"
  # Server bind port
  port: "9091"

# Check new version updates parameters
updates:
  # Enable/disable updates checking.
  enabled: "${UPDATES_ENABLED:true}"

gateways:
  tenants:
    -
      label: "Tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        host: localhost
        port: 1882
        retryInterval: 3000
        maxInFlight: 1000
        security:
          accessToken: "mQ3qvg52nPE5Gzm53sG6"
      remoteConfiguration: true

log:
[log.txt](https://github.com/thingsboard/thingsboard-gateway/files/2584208/log.txt)

What's the problem?

**Comment by mp-loki** [comment]
I assume you have OPC-UA extension configured in TB gui. You have configured security but did not upload the keystore file
