### ISSUE TITLE
I can't configure gateway using docker on windows and simulated Modbus server as getting started documentation[HELP]

### ISSUE THREAD

**Issue by mohammad-elnewehi** [thingsboard/thingsboard-gateway#1417]
**Describe the issue**
I'm using https://thingsboard.cloud/ tenant and downloaded the dashboard JSON file and widgets bundle file from the getting started documentation. 

also, I'm using docker desktop, and after creating the gateway on the dashboard, I downloaded the yml file then I used docker-compose up command.

I followed the steps as per the getting started documentation to use the simulated Modbus server and even using real Modbus server, but I'm not able to run the gateway.

I got a message on the terminal says "tb-gateway  | Cannot load GRPC connector!" and I don't know if this is the problem and if it is what can I do?

**Configuration** (Attach your configuration file)

[docker-compose.txt](https://github.com/user-attachments/files/15521253/docker-compose.txt)

[docker-logs.txt](https://github.com/user-attachments/files/15521280/docker-logs.txt)

[Modbus-server-logs.txt](https://github.com/user-attachments/files/15521309/Modbus-server-logs.txt)

![image](https://github.com/thingsboard/thingsboard-gateway/assets/66198499/e4647b96-a34f-46f8-807e-4d87e1a84aa0)

[modbus-connector.txt](https://github.com/user-attachments/files/15521319/modbus-connector.txt)

Connector name :
Modbus Connector

Versions :
 - OS: [docker desktop on Windows 11]
 - Thingsboard IoT Gateway version [3.5]
 - Python version [3.12.3]

**Comment by samson0v** [comment]
Hi @mohammad-elnewehi, thanks for your interest in ThingsBoard IoT Gateway!
As I can see from your logs file, Gateway successfully read data from the demo Modbus server (attach the screen of your logs file below).
<img width="1102" alt="image" src="https://github.com/thingsboard/thingsboard-gateway/assets/43861229/43b66f76-b4d5-4b6b-88ac-5d988bc08579">

So what is the problem?
