### ISSUE TITLE
[HELP]When I try to use CustomiMqttUplinkConverter,The code 'self. _ configuration. get (' extension-configuration ')' is always None

### ISSUE THREAD

**Issue by CMLiang** [thingsboard/thingsboard-gateway#1426]
**Describe the issue**
When I try to use CustomiMqttUplinkConverter,The code 'self. _ configuration. get (' extension-configuration ')' is always None

**Configuration** (Attach your configuration file)
**Notate: Remove Access token from file if you want to attach a tb_gateway.yaml**
[mqtt.json](https://github.com/user-attachments/files/15815203/mqtt.json)

**Connector name (If you need help with some connector/converter):**
MQTT Custom Converter.Perhaps similar custom converters also have similar issues

**Error traceback (If it was raised):**
```
So it always runs until this code=> dict_result["telemetry"] = {"data": int(body, 0)}  # if no specific configuration in config file - just send data which received,And then this code seems to have an issue, it will report an error↓

|ERROR| - [tb_gateway_service.py] - tb_gateway_service - __send_to_storage - 1070 - 'str' object has no attribute 'get'
```
I am trying to change it to "extensionConfiguration", which is consistent with expectations. Is it due to the Camel Case conversion?
Additionally, in the else code block, I changed it to append to resolve the error of 'str' object has no attribute 'get'

I hope you can see and give me a reply, thank you!

**Versions (please complete the following information):**
 - OS: Centos 7 
 - Thingsboard IoT Gateway version 3.5
 - Python version 3.9

**Comment by samson0v** [comment]
Hi @CMLiang,

Thank you for your interest in ThingsBoard IoT Gateway, we have updated the custom mqtt converter in extension folder in master branch.
