### ISSUE TITLE
thingsboard gateway3.5.1 modbus tcp

### ISSUE THREAD

**Issue by zha0jiapeng** [thingsboard/thingsboard-gateway#1430]
{
  "master": {
    "slaves": [
      {
        "host": "192.168.103.178",
        "port": 6066,
        "type": "tcp",
        "method": "socket",
        "timeout": 35,
        "byteOrder": "BIG",
        "wordOrder": "BIG",
        "retries": true,
        "retryOnEmpty": true,
        "retryOnInvalid": true,
        "pollPeriod": 5000,
        "unitId": 1,
        "deviceName": "ModebusDevice",
        "deviceType": "sensors",
        "sendDataOnlyOnChange": false,
        "connectAttemptTimeMs": 5000,
        "connectAttemptCount": 5,
        "waitAfterFailedAttemptsMs": 300000,
        "attributes": [],
        "timeseries": [
          {
            "tag": "humidity",
            "type": "16uint",
            "functionCode": 3,
            "objectsCount": 1,
            "address": 1
          },
          {
            "tag": "temperature",
            "type": "16uint",
            "functionCode": 3,
            "objectsCount": 1,
            "address": 0
          }
        ],
        "attributeUpdates": [],
        "rpc": []
      }
    ]
  },
  "logLevel": "DEBUG",
  "name": "ModbusGateway",
  "enableRemoteLogging": true,
  "id": "b6868d0b-620a-4f9c-b514-52d3bd172828"
}

我使用 modbus poll 和 java modbus4j做客户端都可以成功读取 请帮我看看 这配置有什么问题

**Comment by imbeacon** [comment]
Hi @zha0jiapeng,

Thank you for your interest in ThingsBoard IoT Gateway.
In your configuration it looks like you are trying to use address 0, for temperature, it may be shifted to 1 and humidity may be shifted to 2 as well, please try to use them. Also, please try to use the latest version of the gateway to avoid issues that was in Modbus connector in old verisons. Let us know if you discover the same issue on the newer gateway.
