### ISSUE TITLE
[HELP] bytes_modbus_uplink_converter - convert - 84 - Exception Response(131, 3, IllegalAddress)

### ISSUE THREAD

**Issue by knityanand** [thingsboard/thingsboard-gateway#1436]
**Describe the issue**
I am trying to get the data from energy meters with the following data config
![EM1](https://github.com/thingsboard/thingsboard-gateway/assets/55359481/0e548f8e-3c78-4f3b-8766-8f8b6371bcb9)
![EM2](https://github.com/thingsboard/thingsboard-gateway/assets/55359481/f3cf383a-f722-43db-92fd-411d6df0dd94)

and I am getting a NULL value and then the exception mentioned below
bytes_modbus_uplink_converter - convert - 84 - Exception Response(131, 3, IllegalAddress)

I get it for both the float and swapped float. I guess, **I am doing something wrong in the modbus.json. Would appreciate some help** Also what changes need to be done for a swapped float

Also, please find attached the values being fetched from modbus tester for the energy meter with float values
![ModbusTester](https://github.com/thingsboard/thingsboard-gateway/assets/55359481/95c38b90-3bea-49dd-a594-00e5b1aba775)

**Configuration** (Attach your configuration file)
[modbus.json](https://github.com/user-attachments/files/15977293/modbus.json)

**Connector name (If you need help with some connector/converter):**
modbus.json

**Error traceback (If it was raised):**
[error.log](https://github.com/user-attachments/files/15977216/error.log)

**Versions (please complete the following information):**
 - OS: Windows 11
 - Thingsboard IoT Gateway version 3.2
 - Python version 3.10.2

**Comment by DuXiaoChuang** [comment]
你的地址错误了，你试试地址+1或者-1

**Comment by knityanand** [comment]
@DuXiaoChuang Thanks so much.. This worked

**Comment by knityanand** [comment]
@DuXiaoChuang  Thanks so much.. This worked. Wondering why I have to add / subtract 1 from the address which works in modbus tester or modscan64.

**Comment by knityanand** [comment]
Closing this. @DuXiaoChuang  Thx again..

**Comment by DuXiaoChuang** [comment]
> Closing this. @DuXiaoChuang Thx again..

You're welcome. Can I add you to wechat? Continue to communicate if you have any questions.
