### ISSUE TITLE
[HELP]The project code runs normally in the IDE, how to package the code into an exe to run out of the ide

### ISSUE THREAD

**Issue by DuXiaoChuang** [thingsboard/thingsboard-gateway#1437]
The project code runs normally in the IDE, how to package the code into an exe to run out of the ide
![26340707c3f7537243ccbba902ac6e2](https://github.com/thingsboard/thingsboard-gateway/assets/149569575/280b0262-e071-4dbb-bb6c-7a83fc924d3c)

**Comment by imbeacon** [comment]
Hi @DuXiaoChuang,

We don’t support distribution like this, but you can try to use [PyInstaller](https://pyinstaller.org/en/stable/), to do this from sources.
