### ISSUE TITLE
thingsboard 3.4.1 failed to import thingsboard-gateway-widget-bundle.json

### ISSUE THREAD

**Issue by langlichong** [thingsboard/thingsboard-gateway#1438]
**Describe the bug**
my TB instance is base 3.4.1 tag , and use python3-thingsboard-gateway.deb to install the gateway,
after login to TB and to import gateway dashboard (refer  https://thingsboard.io/docs/iot-gateway/getting-started/#prerequisites) ,but get an error when import widget bundle (downloaded from https://thingsboard.io/docs/iot-gateway/resources/thingsboard-gateway-widget-bundle.json)
![image](https://github.com/thingsboard/thingsboard-gateway/assets/11713419/e887b65a-fc51-4644-b4e6-a4c9b0b43d42)
![image](https://github.com/thingsboard/thingsboard-gateway/assets/11713419/09c75275-45b9-485a-8e42-486b2acb9665)

- is the TB version is not suitable for gateway's version , what's the version releation about TB and TB gateway  or is other reason, please help

**Versions :**
 - OS: Ubuntu 20.04

**Comment by imbeacon** [comment]
Hi @langlichong,

Thank you for your interest in ThingsBoard IoT Gateway. Please try to use the following widget bundle and dashboard:

[gateway_widgets.json](https://github.com/user-attachments/files/16048172/gateway_widgets.json)
[thingsboard_iot_gateways.json](https://github.com/user-attachments/files/16048184/thingsboard_iot_gateways.json)

These are the latest versions of the widget bundle and dashboard, you can download them on demo.thingsboard.io or on thingsboard.cloud. (To get the latest verison of these files - you need to use a new tenant account)

But I’m not sure that they will work on ThingsBoard lower than 3.6.
