### ISSUE TITLE
[HELP] is it possible to make an update for Gateway from thingsboard UI?

### ISSUE THREAD

**Issue by Jonnik84** [thingsboard/thingsboard-gateway#1459]
Hi there
I’ve installed gateway on Ubuntu on RPi 3, using docker image. It’s the easiest way to install as I suppose…
Gateway is developing almost every day and you generate docker images also very often 
I plan  many many gateways . also I should tell that my gateways are inaccessible physically  and by ssh. 
Is there any possibility to make an update for them manually from thingsboard UI?

Maybe you just give me an advice for different kind of installation ?

also we can configure bash scripts for automatic update, but I think it is not very reliable and I’m afraid to do this automatically.

Thanks for developing great product.

**Comment by imbeacon** [comment]
Hi @Jonnik84,

Thank you for your interest in ThingsBoard IoT Gateway.
You can try to use a service rpc (just send RPC to gateway device from ThingsBoard) **gateway_update** without parameters, it will trigger update for the gateway library inside the container. If you need - you can restart the gateway service insode the container using **gateway_restart** RPC, with seconds as params or with no params.
