### ISSUE TITLE
OPC UA extension function needs to be improved

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard-gateway#147]
I noticed that there is a two-way transmission between OPC UA extension and OPC UA server. However, there is no configuration in the opc-config.json file to send data to OPC UA server. What's going on?
![image](https://user-images.githubusercontent.com/30205233/48930591-8bed8a00-ef2c-11e8-8b8f-e28af4c32aa0.png)

**Comment by dvk2018** [comment]
[Multiple tags write via Server-side RPC for OPC UA extension](https://github.com/thingsboard/thingsboard-gateway/pull/151)
