### ISSUE TITLE
[HELP] deviceNamePattern not recognizing certain paths

### ISSUE THREAD

**Issue by ivanlr** [thingsboard/thingsboard-gateway#1475]
**Describe the issue**
Create description about your issue, and your actions to solve it.
When I try to set the deviceNamePattern in connector's JSON to **"Device ${Root\\.Objects\\.Facility\\.A_5\\.Label}"**, the device is created with the literal name **"Device ${Root\\.Objects\\.Facility\\.A_5\\.Label}"**, while it should be created under the name:  **"Device xXXX"**, as xXXX is the value of the node **${Root\\.Objects\\.Facility\\.A_5\\.Label}**. 

It is weird, as when I try "deviceNamePattern": "Device ${Root\\.Objects\\.Server\\.Label}", it catchs the value of the node and correctly creates the device with expected name. It seems that paths under Server node are well recognized, but under any other different than Server is not caught.

**Configuration** (Attach your configuration file)
**Notate: Remove Access token from file if you want to attach a tb_gateway.yaml**
Connector JSON:
{
  "server": {
    "name": "Test",
    "url": "xxxx",
    "timeoutInMillis": 5000,
    "scanPeriodInMillis": 5000,
    "disableSubscriptions": true,
    "subCheckPeriodInMillis": 100,
    "showMap": false,
    "security": "Basic128Rsa15",
    "identity": {
      "type": "anonymous"
    },
    "mapping": [
      {
        "deviceNodePattern": "Root\\.Objects\\.Server",
        "deviceNamePattern": "Device ${Root\\.Objects\\.Server\\.Label}",
        "attributes": [],
        "timeseries": [
          {
            "key": "MySampleVar",
            "path": "${ns=2;xxxxxxxxxxxxxxxxxxxxx}"
          },
        ]
      },
      {
        "deviceNodePattern": "Root\\.Objects\\.Server",
        "deviceNamePattern": "Device ${Root\\.Objects\\.Facility\\.A_5\\.Label}",
        "attributes": [],
        "timeseries": [
          {
            "key": "MySampleVar",
            "path": "${ns=2;xxxxxxxxxxxxxxxxxxxxx}"
          }
        ]
      }
    ]
  },
  "logLevel": "DEBUG",
  "name": "Test",
  "enableRemoteLogging": false,
  "id": "76683839-58df-4d04-9774-xxxxxxxxxxx"
}

**Connector name (If you need help with some connector/converter):**
OPC-UA Connector

**Error traceback (If it was raised):**

**Versions (please complete the following information):**
 - OS: [Ubuntu 24.04 LTS]
 - Thingsboard IoT Gateway version 3.5.1
 - Python version 3.10.12

**Comment by samson0v** [comment]
Hi @ivanlr, thanks for your interest in ThingsBoard IoT Gateway!
I tried to reproduce your issue but didn't get a result and the device pattern works well.
My config was the following:
```json
"deviceNamePattern": "Demo Device ${Root\\.Objects\\.MyObject\\.MyStringVariable}",
```

Node value on the demo OPC-UA server:
![image](https://github.com/user-attachments/assets/f02d4ba2-19dc-428a-b71b-87da835f2de7)

A created device on ThingsBoard:
<img width="448" alt="image" src="https://github.com/user-attachments/assets/b6e9781b-4020-4201-b590-bd325043ea8b">

Please, try to use a version of the gateway from this [PR](https://github.com/thingsboard/thingsboard-gateway/pull/1501).
