### ISSUE TITLE
[BUG] exception - 127 - Node status code error: The requested operation has no match to return.(BadNoMatch) and other

### ISSUE THREAD

**Issue by ashdam** [thingsboard/thingsboard-gateway#1485]
**Describe the bug**

First of all, thank you for your support, guys ;) we have doing the stress tests right now

We have detected in our devices that some OPC-UA nodes some times are "offline" or not available temporally. In our current system this is something that may happens and it recovers when someone fixes the node.

We have observed the following errors after loading a big connector file with hundred of measures in an iotgateway:

![image](https://github.com/user-attachments/assets/617082ae-454c-418e-849c-e53b40bd931e)
![image](https://github.com/user-attachments/assets/45c95725-e501-46c1-a933-34640553ed56)
![image](https://github.com/user-attachments/assets/4dbf6daa-8702-426b-9048-15175833584c)
![image](https://github.com/user-attachments/assets/645df1f5-d22c-4fab-a9ef-1f131ca60b1c)

We have detected the following behaviour following this errors:

- No other (the rest of nodes and variables) data is sent while these nodes are configured. Would be nice the rest of telemetry is sent.
- DEBUG: Log doesn't blame the exact node with this problem so we have to figure it between hundreds.
- Any modification (in the TB UI through "Update" button) after this point is useless since the GW becomes unreachable as throwing the following error:
![image](https://github.com/user-attachments/assets/08519033-cc13-413a-bb10-447ae4a21dd5)

**configuration yml**:

![image](https://github.com/user-attachments/assets/a08b3770-3c46-4ba6-94b7-d2c74e0b8d01)

** full connector file **
[full_connector.json](https://github.com/user-attachments/files/16511865/full_connector.json)

**Connector name (If bug in the some connector):**
[OPC-UA asyncua Connector]

**Error traceback (If available):**
in the upper screens

**Versions (please complete the following information):**
 - OS: Ubuntu 22
 - Thingsboard IoT Gateway version: 3.5.1 (with this commit based on master https://github.com/thingsboard/thingsboard-gateway/commit/2030c90ae94c3103019ccb62e3b5199fb499e936 )
 - Python version: 3.12

**Comment by ashdam** [comment]
@imbeacon 
Looking at the code , i noticed that you modified **thingsboard_gateway/connectors/opcua/opcua_connector.py** file but the issue was reported on opcua async. shouldn't this be taken to thingsboard_gateway/connectors/**opcua_asyncio**/opcua_connector.py?

**Comment by samson0v** [comment]
@ashdam, with the last release, we abandoned synchronous opcua, so all opcua async code was moved to opcua.

**Comment by ashdam** [comment]
Understood ;)
