### ISSUE TITLE
[BUG] AttributeError: 'int' object has no attribute 'getName'

### ISSUE THREAD

**Issue by jay-kobs** [thingsboard/thingsboard-gateway#1504]
**Describe the bug**
As soon as I start the gateway I get the following error:

AttributeError: 'int' object has no attribute 'getName'

**Error traceback (If available):**

Cannot load GRPC connector!
Error in on_connect callback: %s
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/thingsboard_gateway/gateway/tb_client.py", line 236, in _on_connect
    if result_code.getName().lower() == "connection rate exceeded":
AttributeError: 'int' object has no attribute 'getName'

**Versions (please complete the following information):**

 - OS: Ubuntu 20.04.6 LTS
 - Thingsboard IoT Gateway version 3.5.1
 - Python version 3.8.10

**Comment by jay-kobs** [comment]
@samson0v @imbeacon Any ideas? :)

**Comment by imbeacon** [comment]
Hi @jay-kobs,

This issue was fixed in 3.6, please update your gateway.
