### ISSUE TITLE
[BUG]Is the storage function will when gw can't connect to tb

### ISSUE THREAD

**Issue by yehaha9876** [thingsboard/thingsboard-gateway#1507]
**Describe the bug**
Recently i want modfiy gateway for case when it can't connect to tb,  but it seems when mqtt disconnet there is't any data save in file. Over this time all of the event are lost.

**Connector name (If bug in the some connector):**
I only test on modbus.

I modify modbus attr from 1 to 12 after stop tb, then start tb. only the last attr value 12 receved.

**Versions (please complete the following information):**
 - OS: [e.g. centos 7.9]
 - Thingsboard IoT Gateway version [3.5.1(master source code)]
 - Python version[3.10.14]

**Comment by imbeacon** [comment]
Hi @yehaha9876,

It very depends on storage type that you are using - if you are using memory - this behaviour is expected, other storage types gives persistent storage even when the gateway is not connected to TB. In version 3.6.1 we have fixed major issue, related to file storage, please try the latest version and let us know if something won’t work.
