### ISSUE TITLE
2024-10-18 11:23:23 - |WARNING| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - __on_service_configuration - 297 - Timeout while waiting for service configuration!, session will use default configuration.

### ISSUE THREAD

**Issue by DuXiaoChuang** [thingsboard/thingsboard-gateway#1562]
![image](https://github.com/user-attachments/assets/cc587ac5-2bd2-4c5f-a456-8202f01eee36)

**Comment by imbeacon** [comment]
Hi @DuXiaoChuang,

Service configuration retrieving was added in ThingsBoard 3.8, in case of using older versions - the gateway will wait for configuration, but won’t receive it. It is expected behaviour.
