### ISSUE TITLE
Modbus TCP configuration maps device properties, data is not in device properties, in device telemetry

### ISSUE THREAD

**Issue by guodaxia103** [thingsboard/thingsboard-gateway#157]
Modbus TCP configuration mapping device attributes, data is not in device attributes, in device telemetry.

configuration:
[
    {
        "type": "MODBUS",
        "configuration": {
            "servers": [
                {
                    "transport": {
                        "type": "tcp",
                        "host": "localhost",
                        "port": 502,
                        "timeout": 5000,
                        "reconnect": true,
                        "rtuOverTcp": false
                    },
                    "devices": [
                        {
                            "unitId": 1,
                            "deviceName": "md1",
                            "attributesPollPeriod": 1000,
                            "timeseriesPollPeriod": 1000,
                            "attributes": [
                                {
                                    "tag": "key1",
                                    "type": "long",
                                    "pollPeriod": 1000,
                                    "functionCode": 3,
                                    "address": 0,
                                    "registerCount": 1,
                                    "bit": 0,
                                    "byteOrder": "BIG"
                                }
                            ],
                            "timeseries": [
                                {
                                    "tag": "key2",
                                    "type": "long",
                                    "pollPeriod": 1000,
                                    "functionCode": 3,
                                    "address": 2,
                                    "registerCount": 1,
                                    "bit": 0,
                                    "byteOrder": "BIG"
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        "id": "md1"
    }
]
![image](https://user-images.githubusercontent.com/24488392/50556617-4c2d7580-0d16-11e9-8ec3-29094596db7b.png)

**Comment by zbeacon** [comment]
Hi, @guodaxia103, 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
 - Less footprint and memory impact
 - Easier to extend and customize
 - Improved functionality.

You can try to use the new gateway for your purposes.
