### ISSUE TITLE
[HELP] Is it possible to run 2 Gateways at the same time?

### ISSUE THREAD

**Issue by IhorYednak** [thingsboard/thingsboard-gateway#1573]
Hi guys @imbeacon, @samson0v, could you please let me know if it's possible to run 2 gateways at 1 ubuntu server, cuz I'm trying to make that, I copied the original thingsboard-gateway folder, also copied the thingsboard-gateway service, changed the paths in the service file, but it doesn't work, and gives an error when I try to start the second service.
Attached is the screenshot of the error from console

![image](https://github.com/user-attachments/assets/a2002066-ba37-4741-aa6f-2446faa2aec6)

Could you please advice?

**Comment by imbeacon** [comment]
Hi @IhorYednak,

You can use setup in docker, but comment exposed port and change path to configuration. It is not possible to run two or more gateways as a service in the same system.
