### ISSUE TITLE
[BUG] .git directory inside published docker image

### ISSUE THREAD

**Issue by powermik** [thingsboard/thingsboard-gateway#1590]
**Describe the bug**
as there is no .dockerignorefile  .git (and some other not needed) directories are getting copied into the docker image and waste space and bandwidth when pulling.

**Versions **
 - OS: all docker based installations
 - Thingsboard IoT Gateway version 3.6 and earlier
 - Python version 3.11 (inside docker, but does not matter)

**Comment by imbeacon** [comment]
Hi @powermik,

Thank you for your interest in ThingsBoard IoT Gateway, we have added dockerignore and in future docker images not necessary repositories will be absent.
