### ISSUE TITLE
[BUG] BLE Connector auto install

### ISSUE THREAD

**Issue by powermik** [thingsboard/thingsboard-gateway#1600]
**Describe the bug**
in thingsboard_gateway/connectors/ble/ble_connector.py:
```
try:
    from bleak import BleakScanner
except ImportError:
    print("BLE library not found - installing...")
    TBUtility.install_package("bleak")
```
i think there is a missing
`from bleak import BleakScanner` as new line 33
after calling install_package like in most of the other connectors

seems related to issue #1221

**Connector name (If bug in the some connector):**
BLE Connector

**Error traceback (If available):**
-

**Versions (please complete the following information):**
 - OS: docker image tag: thingsboard/tb-gateway:3.6.1 with ID 578c20b44073
 - Thingsboard IoT Gateway version 3.6.1
 - Python version 3.11 (inside image)

**Comment by imbeacon** [comment]
Hi @powermik,

Please try the latest version of the image, we rearranged imports to install it correctly.
