### ISSUE TITLE
Message loss gateway 2.1.1

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard-gateway#161]
Hello, 
I am using tb gateway 2.1.1, and I have realized, not every message have been arrived to the thingsboard.
I suspect gateway loses the messages. If I doesnt use the gatewa the message loss won't occured.

**Comment by mp-loki** [comment]
Please try new [2.2.1.rc release](https://github.com/thingsboard/thingsboard-gateway/releases/tag/2.2.1rc). The should be fixed there

**Comment by JozsefGuyas** [comment]
I will try it.
Thank you
