### ISSUE TITLE
[HELP] What do use as Docker HEALTHCHECK

### ISSUE THREAD

**Issue by apachler** [thingsboard/thingsboard-gateway#1619]
**Component**

* TB Gateway

**Description**

Is there an application endpoint where some can do a solid healthcheck with? Because, checking for the running process is not suitable and does not give any hint if the application itself is working as expected.

**Environment**

* OS:  SLES 15, Docker Swarm
* TB Gateway: 3.5.2

**Comment by imbeacon** [comment]
Hi @apachler,

Unfortunately, there is no endpoints on the gateway at all, it doesn’t provide any API to interact with it.

**Comment by apachler** [comment]
Ok, thanks for the information.
