### ISSUE TITLE
Modbus tcp failed to get device data

### ISSUE THREAD

**Issue by guodaxia103** [thingsboard/thingsboard-gateway#164]
Configure modbus-config.json(modbus tcp):
When Tb_Gateway is running, one device is offline, the data of other online devices cannot be obtained, and no data is obtained after the offline device is started.
Delete the configuration of the offline device and restart Tb_Gateway to obtain data normally.
When Tb_Gateway is running, there is no guarantee that all devices are running

**Comment by edme10** [comment]
You got success, I have the same problem ....
