### ISSUE TITLE
Invalid extension file

### ISSUE THREAD

**Issue by Micckii** [thingsboard/thingsboard-gateway#166]
When I try to integrate an extension in a tenant admin account by selecting a .json file, thingsboard says  “Invalid extension file”.  I'm using the .json files which you get when downloading thingsboard-gateway from github(to get familiar with thingsboard). Does anyone know how to fix this?

**Comment by zhanglt** [comment]
https://thingsboard.io/docs/iot-gateway/resources/mqtt-gui-extension-configuration.json

**Comment by mp-loki** [comment]
The json file that you download with the gateway source is different from what you have to import via ThingsBoard GUI. Please use the file mentioned by @zhanglt
