### ISSUE TITLE
Can't build from source (compilation error: MqttGatewayService.java:[597,33])

### ISSUE THREAD

**Issue by sung-il** [thingsboard/thingsboard-gateway#167]
Thingsboard version: 2.2
Thignsboard gateway version: 1.4

I edit pom.xml.
<thingsboard.version> 1.4.0-SNAPSHOT to 2.2.0
...
<netty-mqtt.version> 2.0.0TB to 2.0.1TB
...
<thingsboard.version> 1.4.0-SNAPSHOT to 2.2.0

and I got some error.

COMPILATION ERROR:
..../gateway/MqttGatewayService.java:[597,33] error: method create in interface MqttClient cannot be applied to given types;

If you need any data, let me know.

Thank you.

**Comment by mp-loki** [comment]
The dependency for netty-mqtt has changed, and now it is:
`        <dependency>
            <groupId>org.thingsboard</groupId>
            <artifactId>netty-mqtt</artifactId>
            <version>${thingsboard.version}</version>
        </dependency>`
please refer to [pom.xml](https://github.com/thingsboard/thingsboard-gateway/blob/master/pom.xml) from master branch.
