### ISSUE TITLE
mqtt-json.config file not syncing with gateway

### ISSUE THREAD

**Issue by shrinivassridhar** [thingsboard/thingsboard-gateway#168]
hello ! i wanted to know weather the status got synced or not . The default mqtt config.json file is not accepted by the thingsboard UI, but even when i upload the downloaded file(mqtt-gui-configuration.json) the file gets uploaded but the status is still not in sync. Does anyone know how to resolve the issue and help me out differentiating on using the host and ports for tb-gateway.yml, thingsboard.yml and mqtt-config.json. 

[mqtt-gui-extension-configuration.txt](https://github.com/thingsboard/thingsboard-gateway/files/2820330/mqtt-gui-extension-configuration.txt)
[gatewayyml.txt](https://github.com/thingsboard/thingsboard-gateway/files/2820332/gatewayyml.txt)
[thingsboardyml.txt](https://github.com/thingsboard/thingsboard-gateway/files/2820336/thingsboardyml.txt)

**Comment by zhanglt** [comment]
--- mqtt-gui-extension-configuration.txt---
[{
		"id": "mqtt",
		"type": "MQTT",
		"configuration": {
			"brokers": [{
					"host": "0.0.0.0",  #mosquitto broker IP  （mqtt server IP）
					"port": 1883,  
					"ssl": false,
---------------------------------------------------------------------------
-- gatewayyml.txt-------
server:
  # Server bind address
  address: "localhost"  ####gateway IP ####
  # Server bind port
  port: "1884"

# Check new version updates parameters
updates:
  # Enable/disable updates checking.
  enabled: "${UPDATES_ENABLED:true}"

gateways:
  tenants:
    -
      label: "Tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        host: "${GATEWAY_HOST:localhost}" ###  thingsboard  IP###

NOTE: Mosquitto and ThingsBoard use the same port (1883) for MQTT service by default. If you want to use ThingsBoard and Mosquitto on the same host, you need to change the mqtt port in one of the servers. See corresponding ThingsBoard or Mosquitto documentation for more details.

**Comment by zhanglt** [comment]
--- mqtt-gui-extension-configuration.txt---
[{
		"id": "mqtt",
		"type": "MQTT",
		"configuration": {
			"brokers": [{
					"host": "0.0.0.0",
					"port": 1883,
					"ssl": false,
					"retryInterval": 3000,---mosquitto broker IP （mqtt server IP）---
-- gatewayyml.txt-------
server:
  address: "localhost"  --gateway IP --
  port: "1884"
updates:
  enabled: "${UPDATES_ENABLED:true}"
gateways:
  tenants:
    -
      label: "Tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        host: "${GATEWAY_HOST:localhost}"  --thingsboard IP--
        port: 1883
        retryInterval: 3000
        maxInFlight: 1000
        security:

NOTE: Mosquitto and ThingsBoard use the same port (1883) for MQTT service by default. If you want to use ThingsBoard and Mosquitto on the same host, you need to change the mqtt port in one of the servers. See corresponding ThingsBoard or Mosquitto documentation for more details.
