### ISSUE TITLE
@mp-loki hello ! As u told, i verified all my files and even have added my access token to the gateway.yml, and still if i import my mqtt-config.json file the sync status gets unsynced.

### ISSUE THREAD

**Issue by shrinivassridhar** [thingsboard/thingsboard-gateway#169]
@mp-loki hello sir ! As u told, i verified all my files and even have added my access token to the gateway.yml, and still if i import my mqtt-config.json file the sync status gets unsynced. 

[mqtt-gui-extension-configuration.txt](https://github.com/thingsboard/thingsboard-gateway/files/2811846/mqtt-gui-extension-configuration.txt)

[thingsboardyml.txt](https://github.com/thingsboard/thingsboard-gateway/files/2812002/thingsboardyml.txt)

[gatewayyml.txt](https://github.com/thingsboard/thingsboard-gateway/files/2812006/gatewayyml.txt)

_Originally posted by @shrinivassridhar in https://github.com/thingsboard/thingsboard-gateway/issues/53#issuecomment-458884812_

**Comment by zbeacon** [comment]
Hi, @shrinivassridhar 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
 - Less footprint and memory impact
 - Easier to extend and customize
 - Improved functionality.

We will add functionality you have requested to new release.
