### ISSUE TITLE
Is downlink possible?

### ISSUE THREAD

**Issue by arrowcircle** [thingsboard/thingsboard-gateway#173]
Hi! I am trying to figure how to send commands to devices, that are connected via thingsboard gateway.
Devices are connected in the following way: device -> lorawan gateway -> loraserver -> thingsboard gateway -> thingsboard.

Is it possible to control devices with GUI in thingsboard, that sends downlink to devices over thingsboard gateway?
If possible, where I can learn about it?
If not - what is the best place to start hacking on this?

**Comment by zbeacon** [comment]
Hi, @arrowcircle 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
 - Less footprint and memory impact
 - Easier to extend and customize
 - Improved functionality.

We have not implemented LoRaWan support to the new gateway. Perhaps we will add LoRaWan support in one of the future releases.
