### ISSUE TITLE
The data in opc-ua server is  Connected. but I can't see the data on Latest telemetry  

### ISSUE THREAD

**Issue by liangguorui666** [thingsboard/thingsboard-gateway#177]
tb-gateway.yml :

``` yml 
server:
  # Server bind address
  address: "0.0.0.0"
  # Server bind port
  port: "9090"
# Check new version updates parameters
updates:
  # Enable/disable updates checking.
  enabled: "${UPDATES_ENABLED:true}"
gateways:
  tenants:
    -
      label: "Tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        host: localhost
        port: 1883
        retryInterval: 3000
        maxInFlight: 1000
        security:
          accessToken: aUjiymacsKDykrFuumFu
      remoteConfiguration: true
      extensions:
        -
          id: "http"
          type: "HTTP"
          extensionConfiguration: http-config.json
#        -
#          id: "opc-ua"
#          type: "OPC UA"
#          extensionConfiguration: opc-config.json
opc:
  enabled: true
mqtt:
  enabled: true 
```
 extension： 
![image](https://user-images.githubusercontent.com/42400978/55400182-c244b100-557f-11e9-9c13-5e2c5b076fc0.png)

FreeOpcua Client
![image](https://user-images.githubusercontent.com/42400978/55401238-b7d7e680-5582-11e9-8f15-cffbcfd328a2.png)

conselLog
[console.log](https://github.com/thingsboard/thingsboard-gateway/files/3033798/console.log)

  Latest telemetry  ：
![image](https://user-images.githubusercontent.com/42400978/55401427-506e6680-5583-11e9-80c1-090f8409656f.png)

these configurations not good
deviceNodePattern ：Root\.Views\.AirConditionerView\.AirConditioner_10
deviceNodePattern ：Root\\.Views\\.AirConditionerView\\.AirConditioner_10
deviceNodePattern ：Root\/Views\/AirConditionerView\/AirConditioner_10
deviceNodePattern ：Root/Views/AirConditionerView/AirConditioner_10
deviceNodePattern ：Root/.Views/.AirConditionerView/.AirConditioner_10
deviceNodePattern ：Root//.Views//.AirConditionerView//.AirConditioner_10

**Comment by liangguorui666** [comment]
these configurations not good

**Comment by liangguorui666** [comment]
these configurations not good
Root\\.Views\\.AirConditionerView\\.AirConditioner_1\\d+$
Root\.Views\.AirConditionerView\.AirConditioner_1\\d+$
Root\.Views\.AirConditionerView\.AirConditioner_1\d+$
Waiting for your .  Online
@mp-loki

**Comment by mp-loki** [comment]
Please do the following:
1) backup your old tb-gateway.log file, 
2) set log level to DEBUG in your logback.xml for thingsboard section, 
3) restart your gateway and run your test again
4) attrach the new log file to this issue

**Comment by liangguorui666** [comment]
Thank you very much
I've seen the data, but my  deviceNodePattern : .* 
![image](https://user-images.githubusercontent.com/42400978/55528201-9edc4c00-56ce-11e9-9449-7924b5343fa3.png)
![image](https://user-images.githubusercontent.com/42400978/55528645-2ffff280-56d0-11e9-9316-ade5f27cd3df.png)

How do I write regex  “deviceNodePattern”and ”deviceNamePattern”  to see the telemetry values of all devices
![image](https://user-images.githubusercontent.com/42400978/55528121-5a50b080-56ce-11e9-9d05-3f70ae16744c.png)


@mp-loki

**Comment by zbeacon** [comment]
Hi, @liangguorui666 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
Less footprint and memory impact
Easier to extend and customize
Improved functionality.

You can try using a new gateway for your purposes instead of a Java gateway. You can read more about OPC-UA configuration in the new gateway [here](https://thingsboard.io/docs/iot-gateway/config/opc-ua/).
