### ISSUE TITLE
Can MBS add WRITE_COIL(5) function?

### ISSUE THREAD

**Issue by egeong** [thingsboard/thingsboard-gateway#184]
Is the MBS add WRITE_COIL(5) function planned in the near future?

thanks!

**Comment by zbeacon** [comment]
Hi, @egeong 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
 - Less footprint and memory impact
 - Easier to extend and customize
 - Improved functionality.

We have implemented WRITE_COIL(5) and WRITE_COILS(15) in the new gateway. You can try it use for your purposes.
