### ISSUE TITLE
How to fix the port of tcp connection

### ISSUE THREAD

**Issue by JerryZhangCN** [thingsboard/thingsboard-gateway#199]
I found that when the gateway can't connect to the thingboard, it will continue to reconnect, but this reconnection will generate a lot of tcp, and then the network will be congested. I want to know if there is a way to set a tcp connection to use a certain port, or to close the tcp connection when the reconnection request fails.

**Comment by zbeacon** [comment]
Hi, @JerryZhangCN 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
Less footprint and memory impact
Easier to extend and customize
Improved functionality.

We will consider adding functionality you have requested to new release.
