### ISSUE TITLE
gateway resend message to thingsboard

### ISSUE THREAD

**Issue by saesf** [thingsboard/thingsboard-gateway#203]
hi,
i'm using thingsboard 2.3.1 and tb-gateway 2.2.1rc on a single windows laptop.i wrote a python program that uses paho to send 7 messages to 7 different topics (say E0 to E6). messages are sent with 500ms delay. in order to see if mosquitto broker can receive messages correctly, i subscribed to all topics (using MQTTBox) and i received every message once and in order. but when i check thingsboard's rule nodes event log, i saw that some messages have been received twice with same timestamp. i also sent same message to different topics in order (send to E0 then E1 ...), but messages in thingsboard's event log were out of order.

for example, following values are message body and timestamp from event log when i received a message ("1e") twice:
`3e0 -> 1565154869745

1e0 -> 1565154862736

3e5 -> 1565154872283

3e6 -> 1565154872774`

as you can see it's timestamp is out of order and this will cause some problem.

i repeated this test 4 times and i sent 7 message to 7 different topics (49 message in total) and here is the result:

`test 1-> 4  messages resent, 10 out of order`
`test 2->10 messages resent, 2   out of order`
`test 3-> 0  messages resent, 0   out of order`
`test 4-> 8  messages resent, 3   out of order`

for me receiving messages out of order is not a problem but i can not receive each message twice. my question is why gateway send some messages twice and how can i  solve thins problem?

**Comment by zbeacon** [comment]
Hi, @saesf 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
Less footprint and memory impact
Easier to extend and customize
Improved functionality.

You can try using a new gateway for your purposes instead of a Java gateway.

We look forward to your feedback.
