### ISSUE TITLE
gateway telemetry can receive array data?

### ISSUE THREAD

**Issue by donnietung** [thingsboard/thingsboard-gateway#204]
gateway telemetry can receive array data? 
default is json object
thanks

**Comment by zbeacon** [comment]
Hi, @donnietung 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
Less footprint and memory impact
Easier to extend and customize
Improved functionality.

> gateway telemetry can receive array data?
> default is json object
> thanks

Yes, the gateway can receive json array with data and parse it. You can read more [here](https://thingsboard.io/docs/iot-gateway/config/mqtt/) about configuration.
