### ISSUE TITLE
How to upload data only to Attributes from Modbus Device via Thingsboard Gateway CE ?

### ISSUE THREAD

**Issue by andrevvell** [thingsboard/thingsboard-gateway#221]
I have a Local Thingsboard CE with TB Gateway and they are work well. But whem the data upload come from Modbus devices, the data only come as Timeseries, and I not want storage, only the online data.

in the modbus-config.json, they are defined as:

      "attributes": [ { "tag": "X", "type": "boolean", "functionCode": 1, "address":  0 },
      "timeseries": [ { "tag": "Y", "type": "boolean", "functionCode": 2, "address":  1 } ]

Since that I expect 1 Attribute and 1 timeseries, but both data values come as TIMESERIES, and they are stored in DB.

How can I fix that?

**Comment by zbeacon** [comment]
Hi, @andrevvell 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
Less footprint and memory impact
Easier to extend and customize
Improved functionality.

You can try to use the new gateway, using "memory" storage type and [this guide](https://thingsboard.io/docs/iot-gateway/config/modbus/) to configure connection to modbus.
