### ISSUE TITLE
modus.json facing issue for multiple attribute 

### ISSUE THREAD

**Issue by ankitfidel** [thingsboard/thingsboard-gateway#229]
Hi Please go through my modbus.json file 
{
  "server": {
    "name": "Modbus Default Server",
    "type": "tcp",
    "host": "10.128.31.39",
    "port": 502,
    "timeout": 35,
    "rtuOverTcp": false,
    "devices": [
      {
        "unitId": 4,
        "deviceName": "FM1.1 G30.1_04",
        "attributesPollPeriod": 5000,
        "timeseriesPollPeriod": 5000,
        "sendDataOnlyOnChange": true,
        "attributes": [
        ],
        "timeseries": [          {
          "byteOrder": "BIG",
          "tag": "Voltage",
          "type": "long",
          "functionCode": 4,
          "registerCount": 2,
          "address": 18436
        },        
        {
          "byteOrder": "BIG",
          "tag": "Frequency",
          "type": "long",
          "functionCode": 4,
          "registerCount": 2,
          "address": 18438
        }
        ]
      }
    ]
  }
} 

I am facing issue while running thingsboard tb_gateway_service_py
''2019-11-12 14:23:49' - DEBUG - tb_gateway_service - 135 - Connector "Modbus Default Server" - Saved information - {"deviceName": "FM1.1 G30.1_04", "deviceType": "ModbusDevice", "telemetry": [{"Voltage": 23867}, {"Frequency": -1}], "attributes": []}'
-------------------------------------------------------------
''2019-11-12 14:23:49' - ERROR - tb_gateway_service - 175 - Expecting property name enclosed in double quotes: line 1 column 58 (char 57)'
Traceback (most recent call last):
  File "/home/ubuntu/Downloads/thingsboard-gateway-2.0.1rc-python/thingsboard_gateway/gateway/tb_gateway_service.py", line 158, in __read_data_from_storage
    data_to_send = loads('{"ts": %f,"values": %s}' % (int(time.time()*1000),','.join(dumps(param) for param in current_event["telemetry"])))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 58 (char 57)

**Comment by zbeacon** [comment]
Hello @ankitfidel ,

Thank you for your interest in ThingsBoard IoT Gateway. We just released a new pre-release version, please check if the problem is fixed and give feedback.
