### ISSUE TITLE
Can not  decode IEEE754/32 in modbus.json?

### ISSUE THREAD

**Issue by enyulion** [thingsboard/thingsboard-gateway#235]
I have installed the lastest version(2.0.0.2) in my Raspberry Pi zero w.
I wrote /etc/thingsboard-gateway/config/modbus.json
`{
  "server": {
    "name": "Modbus Default Server",
    "type": "tcp",
    "host": "192.168.64.89",
    "port": 5020,
    "timeout": 35,
    "rtuOverTcp": false,
    "devices": [
      {
        "unitId": 1,
        "deviceName": "Temp Sensor",
        "attributesPollPeriod": 5000,
        "timeseriesPollPeriod": 5000,
        "sendDataOnlyOnChange": false,
        "attributes": [
          {
            "byteOrder": "BIG",
            "tag": "test",
            "type": "double",
            "functionCode": 4,
            "registerCount": 2,
            "address": 4
          }
        ],
        "timeseries": [
          {
            "byteOrder": "BIG",
            "tag": "temp",
            "type": "double",
            "functionCode": 4,
            "registerCount": 2,
            "address": 0
          },
          {
            "byteOrder": "BIG",
            "tag": "humi",
            "type": "double",
            "functionCode": 4,
            "registerCount": 2,
            "address": 2
          }
        ]
      }
    ]
  }
}
`
But in device telemetry date only show the integer part，not decimals
that is：
{'deviceName': 'Temp Sensor', 'deviceType': 'ModbusDevice', 'telemetry': [{'temp': 27}, {'humi': 54}], 'attributes': [{'test': 100}]}'
In fact，I input {‘temp’: 27.051}，{‘humi’: 54.96} in Modbus Slave.

**Comment by zbeacon** [comment]
Hi @enyulion 

Thank you for your interest in ThingsBoard IoT Gateway. I have found the bug, please try to update your gateway from a development branch ( develop/2.4-python ) in the repository.
You can do this using following commands:
```bash
git clone -b develop/2.4-python --single-branch https://github.com/thingsboard/thingsboard-gateway.git
cd thingsboard-gateway
python3 setup.py install
```

And, as usual, start your gateway.
