### ISSUE TITLE
OPC-UA: Get all variables from folder

### ISSUE THREAD

**Issue by david114** [thingsboard/thingsboard-gateway#247]
Hey there,
i've never worked with OPC-UA and i need a little bit of help on how to receive all the sensor data.
**My OPC-UA Server Structure looks like this:**

![order](https://user-images.githubusercontent.com/27721138/74916016-6700f480-53c5-11ea-8542-77be9927423e.png)

I want to read out all variables that are in the main_folder (sensor1, sensor2, ...) **dynamically**
My opc.json currently looks like this:

![json](https://user-images.githubusercontent.com/27721138/74916427-22c22400-53c6-11ea-9b05-c977e0f1cf14.png)

Another problem (maybe because I'm using invalid syntax) is that the opcua-connector keeps reconnecting to the opc-ua server, and i really don't know why:

![logs](https://user-images.githubusercontent.com/27721138/74916757-b85db380-53c6-11ea-8934-2503a52b476d.png)

I'd be really happy if you could help me out with this one. 
Thanks!

**Comment by Ming-Shu** [comment]
Hello @david114 

Actually,I have the similar experience too!
Your opc.json------>"deviceNodePattern":"Root\\.Objects\\.man_folder",
About reconnecting to the opc-ua server, maybe  you can check your host IP of "tb_gateway.yaml"

Hope this would help you.

**Comment by david114** [comment]
Thanks. i got it to work right now.
