### ISSUE TITLE
Cannot install with docker because image does not exist

### ISSUE THREAD

**Issue by IoTopenTech** [thingsboard/thingsboard-gateway#248]
**Describe the bug**
The command 
docker run -it -v ~/.tb-gateway/logs:/var/log/thingsboard-gateway -v ~/.tb-gateway/extensions:/var/lib/thingsboard_gateway/extensions -v ~/.tb-gateway/config:/etc/thingsboard-gateway/config --name tb-gateway --restart always thingsboard/tb-gateway

fails because it cannot find the 'thingsboard/tb-gateway:latest imge

![imagen](https://user-images.githubusercontent.com/52624907/74919429-e04f1600-53ca-11ea-9be3-f567783c154a.png)

**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Thingsboard IoT Gateway version 2.1
 - Python version 2.7.17

**Comment by zbeacon** [comment]
Hi @IoTopenTech 

Thank you for your patience, we have fixed it, and the docker image is available on Dockerhub.
