### ISSUE TITLE
Keep Installation guide up-to-date

### ISSUE THREAD

**Issue by maxsenft** [thingsboard/thingsboard-gateway#253]
Hi,

one request that might help newcomers: 

I installed the Thingsboard IoT Gateway as described at https://thingsboard.io/docs/iot-gateway/install/deb-installation/

There, version "2.0" is part of the advised Github download URL. There's no hint or remark or anything similar that asks one to check the Github release page.

Unfortunately due to that not up-to-date website, I dumped 2 hours searching for a bug that was already fixed since 2.0.0.9 ...

So, it would be great if the Installation Guide websites (also for CentOS) could be updated as soon as there's a new release!

**Comment by zbeacon** [comment]
Hi @maxsenft 

Thank you for your interest in the ThingsBoard IoT Gateway.
Also thank you for your feedback, i will fix this link in documentation.
