### ISSUE TITLE
change opcua.json (connector config) remotely

### ISSUE THREAD

**Issue by david114** [thingsboard/thingsboard-gateway#254]
Hey,

i have read all docs but i couldn't really figure out if its possible to change the connector config file remotely. In my case the `opcua.json`

To visualize what I'm trying to achieve i made a small graphic:

![Untitled Diagram (21)](https://user-images.githubusercontent.com/27721138/75887274-d77a2d80-5e29-11ea-8681-59e59d6c1bb3.png)

I can't access the RaspberryPi (Thingsboard IoT Gateway) directly anymore, because it's located remotely. The problem I'm facing is that the configuration from the OPC-UA Server may change from time to time. So i need to be able to configure the `opcua.json` or somehow be able to get new telemetry data.

How can I achieve this?

Thanks in advance!

**Comment by zbeacon** [comment]
Hi @david114 

I have released this feature in the gateway, but unfortunately, there is no correct dashboard for remote configuration in the ThingsBoard yet, it will be added in the next release.

Also to use this feature you need to add/set configuration parameter ** remoteConfiguration** to **true** in the tb_gateway.yaml

**Comment by david114** [comment]
Allright, i'll be patient then :)
Thanks for answering quickly.
