### ISSUE TITLE
[BUG] Serial connector can only handle a single device

### ISSUE THREAD

**Issue by acetylen** [thingsboard/thingsboard-gateway#260]
**Describe the bug**
The CustomSerialConnector class's main loop seems unable to handle more than one device in case errors occur.

If a device drops out while the main loop is running, it will simply try to poll that device forever, never moving on to the next device.
```python
  def run(self):    # Main loop of thread
...
                    while ch != b'\n':
                        try:
                            try:
                                ch = serial.read(1)    # Reading data from serial
                            except AttributeError as e:
                                if serial is None:
                                    self.__connect_to_devices()    # if port not found - try to connect to it
                                    raise e
                            data_from_device = data_from_device + ch
                        except Exception as e:
                            log.exception(e)
                            continue
          ...
```
The `continue` here means that a continuously erroring device (like one that has disconnected) will block the connector.

Also, as a side note, he connector being hard-coded to only accept `\n` as a line ending seems short-sighted.

**Comment by zbeacon** [comment]
Hi @acetylen,

This connector created to explain how connectors work and it's general goal - show how to create custom connector. Also if you watch a little bit upper in code, you can see that this connector has for loop to loop over devices in the configuration:

```
            ...
            while True:
                for device in self.devices:
                    serial = self.devices[device]["serial"]
                    ...
```

Symbol "\n" is hard coded to simplify configuration in the example.

**Comment by acetylen** [comment]
The outer loop will never advance while a read is in progress, and a read will never finish if a device disconnects.

I realize that the connector is an example but it should at least be a complete one.
