### ISSUE TITLE
Java version tb-gateway

### ISSUE THREAD

**Issue by ropeal** [thingsboard/thingsboard-gateway#263]
Hi there, thanks for your wonderful work on tb-gateway. I am a Java guy and is using the Java version tb-gateway. I noticed that recently there is no more Java version tb-gateway released, I am wondering which is the latest release of Java version tb-gateway and do you plan to release Java version tb-gateway any more, if not, what are the drawbacks of Java version tb-gateway compared to python version? Thank you!

**Comment by zbeacon** [comment]
Hi @ropeal,

Thank you for your interest in ThingsBoard IoT gateway.
We are not going to continue developing the Java version of the gateway. Python Gateway is a completely new solution that provides more customization options and reduces system hardware requirements.
