### ISSUE TITLE
[HELP] 'Attribute updates config not found' in MQTT connector

### ISSUE THREAD

**Issue by slibutti** [thingsboard/thingsboard-gateway#271]
Hi, I'm trying to setup the MQTT connector to receive attributes updates.
The gateway is up and running: I am able to post telemetry and receive RPCs;
however, when updating attributes, notifications arrive to the gateway but are
nor processed by the MQTT connector.

**Relevant part of mqtt.json**
`
    "attributeUpdates":
    [
        {
          "deviceNameFilter": "GALA_ASSET_.*",
          "attributeFilter": "something",
          "topicExpression": "gala/${deviceName}/${attributeKey}",
          "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"
        }
    ],
`

**Relevant part of service.log**
Note: from this, it seems that the update reaches the gateway

`''2020-04-01 12:43:12' - DEBUG - tb_gateway_service - 488 - Attribute request received with content: "{'device': 'GALA_ASSET_1_NODE_2', 'data': {'something': 'some_value_1'}}"''`

**Relevant part of connector.log**
`''2020-04-01 12:43:12' - ERROR - mqtt_connector - 309 - Attribute updates config not found.'
`

**System info**
 - OS: Ubuntu 18.04
 - Thingsboard IoT Gateway version 2.2.4
 - Python 3.6.9

**Comment by zbeacon** [comment]
Hi @slibutti 

Thank you for your interest inThingsBoard IoT gateway.
It was a bug, i fixed it and if you install the version from master branch, you will get it.
How to install the gateway from sources - you can [read here](https://thingsboard.io/docs/iot-gateway/install/source-installation/). Or you can wait for next release, I will publish new pre-release in several days.
