### ISSUE TITLE
[HELP]CPU usage is too high, sometimes exceeding 100%

### ISSUE THREAD

**Issue by lesliechung88** [thingsboard/thingsboard-gateway#272]
**Describe the issue**

### The CPU usage is too high, sometimes exceeding 100%. What causes it? Can it be optimized?

only run MQTT Connector

 - OS:  Ubuntu 18.04
docker:
thingsboard/tb-gateway :latest                                     32fcac115816        2 months ago        525MB

**Comment by zbeacon** [comment]
Hi @lesliechung88 

Thank you for your interest in ThingsBoard IoT gateway and feedback, I will investigate and optimize processing.

**Comment by zbeacon** [comment]
Hi @lesliechung88 

I researched and added some improvements, but processing requires CPU to increase speed. When processing data, the gateway can use almost all available resources to process incoming data. After the data has been processed, the processor load will become equal to 1-2 percent.

**Comment by AngeLinuX99** [comment]
Same problem of huge use of cpu on my docker server. I have 4 thingsboard_gateway instances and CPU is ALWAYS at 100% with 2.8 version. Im going to test 2.9

**Comment by AngeLinuX99** [comment]
> Same problem of huge use of cpu on my docker server. I have 4 thingsboard_gateway instances and CPU is ALWAYS at 100% with 2.8 version. Im going to test 2.9

Same CPU problem in version 2.9

**Comment by abalmos** [comment]
> Hi @lesliechung88
> 
> I researched and added some improvements, but processing requires CPU to increase speed. When processing data, the gateway can use almost all available resources to process incoming data. After the data has been processed, the processor load will become equal to 1-2 percent.

@zbeacon can we please re-open this issue? The expected behavior you described is not what we are experiencing. I see a near constant 100% CPU usage regardless of input data rate, in fact even when there is none.

**Comment by ferguscan** [comment]
Hi,

I am experiencing this issue, and I use Thingsboard IoT Gateway via Docker.  Will the official Docker image be updated to include this fix?  I see the image was last updated two months ago: https://hub.docker.com/r/thingsboard/tb-gateway/tags

Thanks!
