### ISSUE TITLE
[HELP]MQTT with topic filter like /sensor/+/+/data

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard-gateway#281]
**Describe the issue**
I want to use the mqtt connector, In the mqtt.json file, my topic filter is like this "topicFilter": "/sensor/+/+/data", My publish topic is like this:"**/sensor/deviceType/deviceName/data**",
I don't know how to complete the "deviceNameTopicExpression" and the "deviceTypeTopicExpression"。 Can any one help me to complete the JsonPath expression?

![image](https://user-images.githubusercontent.com/31084798/78644896-392a2d80-78e9-11ea-881e-56749b37eed4.png)

**Comment by slibutti** [comment]
Assuming that device type does not contain chars like "_" (if so, change the regexp accordingly),

Device type: (?<=sensor\/)(.*?)(?=\/)
Device name: (?<=\/)([0-9A-Za-z]*?)(?=\/data)

Give it a try on https://pythex.org/
