### ISSUE TITLE
[HELP]Modbus connector, 'BinaryPayloadDecoder' object has no attribute 'decode_16bit_float'

### ISSUE THREAD

**Issue by googlehim** [thingsboard/thingsboard-gateway#286]
**Describe the issue**
If I use this modbus.json, connector.log shows ok:
![image](https://user-images.githubusercontent.com/9864527/79085862-acf68b00-7d6c-11ea-9ac9-c4b26e4bd568.png)
![image](https://user-images.githubusercontent.com/9864527/79085876-b97ae380-7d6c-11ea-9377-86555f6ac271.png)

If I use this modbus.json,   connector.log shows error:
![image](https://user-images.githubusercontent.com/9864527/79085891-c566a580-7d6c-11ea-9904-aa412743075a.png)
![image](https://user-images.githubusercontent.com/9864527/79085903-d0213a80-7d6c-11ea-8e3d-f1da0dc3cad3.png)

**Connector name (If you need help with some connector/converter):**
[e.g. MQTT Connector]
Modbus Connector

**Versions (please complete the following information):**
 - OS: 
![image](https://user-images.githubusercontent.com/9864527/79093750-d7a20d00-7d87-11ea-9a4d-da39e0518b30.png)

 - Thingsboard IoT Gateway version v2.2.4.2
![image](https://user-images.githubusercontent.com/9864527/79085928-ea5b1880-7d6c-11ea-8f81-3754e2a5de8f.png)
thingsboard v2.4.3

**Comment by zbeacon** [comment]
Hi @googlehim 

It looks like you need to change count of registers (try to use registerCount 2 instead 1).
Also you can update your gateway to version from sources and use one of the following types:

string
bit
bits
8int
8uint
16int
16uint
16float
32int
32uint
32float
64int
64uint
64float

**Comment by googlehim** [comment]
Thank you for your reply.
I also tried "type": "long", "registerCount": 1, "functionCode" : 4,  still error.
modbus.json
![image](https://user-images.githubusercontent.com/9864527/79141692-e53dae00-7dec-11ea-86c7-917c5f20a9b2.png)
remote debug:
![image](https://user-images.githubusercontent.com/9864527/79141788-0a322100-7ded-11ea-99bb-6bcb3e883b8f.png)

**Comment by zbeacon** [comment]
@googlehim 

Ok, it looks like a problem with previous version, please try the following command to update the gateway:

`sudo pip3 install thingsboard-gateway --user thingsboard_gateway --upgrade`

**Comment by googlehim** [comment]
@zbeacon 
 After update my gateway to version from sources, problem solved.
 Thank you so much.

**Comment by bmesich** [comment]
@zbeacon - thanks for the fix.  I'm running into this same issue with the official docker image: docker.io/thingsboard/tb-gateway. I confirmed running the pip3 upgrade inside the container fixes the issue.  Rebuilding the container locally with the Dockerfile located in the repository does not pull your fix (and adding the pip install to the Dockerfile does not work either).  Any chance we could git the fix into the official docker image?

**Comment by zbeacon** [comment]
@bmesich 

Thanks for your interest in ThingsBoard IoT gateway. Unfortunately, a new docker image will be available in next release. I'm going to publish on Monday.

**Comment by SERGAMO** [comment]
The same error was happening to me, even with 2.2.5. After upgrading the pymodbus with `pip3 install pymodbus --upgrade` the decode_16bit_float is gone.
