### ISSUE TITLE
Can`t connect to TB wthen remoteConfiguration: true[BUG]

### ISSUE THREAD

**Issue by Alentus** [thingsboard/thingsboard-gateway#288]
**Describe the bug**
When set "remoteConfiguration" to true gateway can`t connect to thingsboard server.
When set to false all is ok.

tb_connection.log

> ''2020-04-15 12:15:47' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:15:47' - DEBUG - tb_device_mqtt - 360 - Subscribed to * with id 1'
''2020-04-15 12:15:47' - INFO - tb_gateway_mqtt - 176 - Subscribed to *|* with id 1'
''2020-04-15 12:15:47' - DEBUG - tb_logger - 37 - Added remote handler to log tb_connection'
''2020-04-15 12:15:47' - INFO - tb_client - 82 - TB client <paho.mqtt.client.Client object at 0x7f09c85e8b00> has been disconnected. Current client for connection is: <paho.mqtt.client.Client object at 0x7f09c85e8b00>'
''2020-04-15 12:15:47' - DEBUG - tb_device_mqtt - 180 - Disconnected client: <paho.mqtt.client.Client object at 0x7f09c85e8b00>, user data: None, result code: 1'
''2020-04-15 12:15:48' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:15:49' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:15:50' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:15:51' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:15:52' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:15:53' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:15:54' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:15:55' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:15:56' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:15:57' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:15:58' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:15:59' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:00' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:01' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:02' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:03' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:04' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:05' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:06' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:07' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:08' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:09' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:10' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:11' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:12' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:13' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:14' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:15' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:16' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:17' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:18' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:19' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:20' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:21' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:22' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:23' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:24' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:25' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:26' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:27' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:28' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:29' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:30' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:31' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:32' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:33' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:34' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:35' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:36' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:37' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:38' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:39' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:40' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:41' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:42' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:43' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:44' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:45' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:46' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:47' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:48' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:49' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:50' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:51' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:52' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:53' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:54' - DEBUG - tb_client - 115 - connecting to ThingsBoard'
''2020-04-15 12:16:55' - DEBUG - tb_client - 115 - connecting to ThingsBoard'

**Comment by zbeacon** [comment]
Hi @Alentus 

Thank you for your interest in the ThingsBoard IoT gateway.

The remote configuration feature will be available in the next ThingsBoard release. Old remote configuration doesn't work with the Python-based gateway. Please wait, to use this feature.
