### ISSUE TITLE
[BUG] Modbus RPC value

### ISSUE THREAD

**Issue by dzurikmiroslav** [thingsboard/thingsboard-gateway#289]
**Describe the bug**
I have modbus rpc method:
```
          "turnOn": {
            "type": "integer",
            "value": 1,
            "functionCode": 6,
            "address": 8192,
            "byteOrder": "BIG",
            "registerCount": 1
          }
```
After call, my mock nodered modbus server register 0x2000h (8192) has value 256 (0100b) not value 1 (0001b).
Probably the value is written as 8bit number, but modbus have 16bit register.

When I try set larger value for example `"value": 256,` I got error:
```
''2020-04-17 06:41:37' - ERROR - tb_gateway_service - 429 - byte format requires -128 <= number <= 127'
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/thingsboard_gateway/gateway/tb_gateway_service.py", line 397, in _rpc_request_handler
    connector_name.server_side_rpc_handler(content)
  File "/root/.local/lib/python3.6/site-packages/thingsboard_gateway/connectors/modbus/modbus_connector.py", line 248, in server_side_rpc_handler
    rpc_command_config["payload"] = self.__devices[content["device"]]["downlink_converter"].convert(rpc_command_config, content)
  File "/root/.local/lib/python3.6/site-packages/thingsboard_gateway/connectors/modbus/bytes_modbus_downlink_converter.py", line 55, in convert
    builder_functions[lower_type](value)
  File "/root/.local/lib/python3.6/site-packages/pymodbus/payload.py", line 205, in add_8bit_int
    self._payload.append(pack(fstring, value))
struct.error: byte format requires -128 <= number <= 127
```

Only when I set `"registerCount": 2` the value is written correctly as 16bit number.

**Connector name (If you need help with some connector/converter):**
Modbus TCP Connector

**Versions (please complete the following information):**
 - Docker image thingsboard/tb-gateway:2.2.4.1 with executed: `pip3 install thingsboard-gateway --user thingsboard_gateway --upgrade`

**Comment by zbeacon** [comment]
Hi @dzurikmiroslav 

Thank you for your interest in ThingsBoard IoT gateway.
We have released a new version of the gateway, and refactored a Modbus connector, please, update your gateway and configure using [this guide](https://thingsboard.io/docs/iot-gateway/config/modbus/).
