### ISSUE TITLE
[HELP]How to provision devices from TB to TB Gateway (python)

### ISSUE THREAD

**Issue by chad007** [thingsboard/thingsboard-gateway#290]
**Describe the issue**
I use Modbus Connector with `modbus.json` of TB Gateway (python, v2.2.4.1) configured like below:

> {
  "server": {
    "name": "Modbus Default Server",
    "type": "tcp",
    "host": "192.168.xxx.xxx",
    "port": 502,
    "timeout": 35,
    "rtuOverTcp": false,
    "devices": [
      {
        "unitId": 1,
        "deviceName": "Temp Sensor",
        "attributesPollPeriod": 5000,
        "timeseriesPollPeriod": 5000,
        "sendDataOnlyOnChange": true,
        "attributes": [
          {
            "byteOrder": "BIG",
            "tag": "test",
            "type": "long",
            "functionCode": 3,
            "registerCount": 1,
            "address": 0
          }
        ]
      }
    ]
  }
}

I can see that TB is receiving telemetry data from TB Gateway. But in this case, it seems that the only way to provision devices to TB Gateway is to edit the `modbus.json`. In earlier version (v2.2.1rc) of the TB Gateway (Java)，when the TB gateway extension status is "Sync", I can provision new devices by configuring the extension in TB, which will push the configuration to TB Gateway.  

The v2.2.4.1 gateway in TB gateway extension is always "Not sync", I wonder if this has something to do with the device provisioning to TB gateway from TB. If it is, then how to make it "Sync"? Or to make the problem easier to solve, is there any other way to provision devices to TB gateway (v2.2.4.1) from TB?

**Configuration** (Attach your configuration file)
**Notate: Remove Access token from file if you wanna attach tb_gateway.yaml**

> thingsboard:
  host: mytb
  port: 1883
  remoteConfiguration: false
  security:
    accessToken: xxxxxxxxxxxxxxxxxx
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
connectors:
  -
    name: Modbus Connector
    type: modbus
    configuration: modbus.json

**Connector name (If you need help with some connector/converter):**
[e.g. MQTT Connector]
Modbus Connector

**Versions (please complete the following information):**
I use this docker image: `thingsboard/tb-gateway:2.2.4.1`
 - OS: Ubuntu 18.04
 - Thingsboard IoT Gateway version 2.2.4.1
 - Python version 3.6.9

**Comment by zbeacon** [comment]
Hi @chad007 

Thank you for your interest in the ThingsBoard IoT gateway. Unfortunately, the old version of the remote configuration is not available in the new gateway. We will release the remote configuration feature in the next version of the ThingsBoard.
