### ISSUE TITLE
Some suggestions about modbus connectors.

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard-gateway#294]
Our current approach is to use tb-gateway as a TCPClient to connect to the modbus server. Each modbus server has an IP address. 

In this case, if the tb-gateway uses the intranet IP, the MODBUS server must also use the intranet IP. This is no problem, but the tb-gateway is deployed on the intranet and cannot be remotely maintained. If we want to add another device, No remote operation.

However, if tb-gateway uses a public IP, the MODBUS server must also be a public IP, and as many MODBUS servers as there are as many public IPs, it is necessary to apply for multiple public IPs from the operator Relatively large cost.

If we use tb-gateway as the TCPServer,modbus server as TCPClient, there will be no such problem.
Even though tb-gateway is deployed on the public network, But, because it is a server, and the modbus client can communicate with tb-gateway using the intranet IP.

So, I mean, tb-gateway serves as the server, and the modbus server serves as the client. Is this better?

**Comment by zbeacon** [comment]
Hi @qwyinxiang,

Thank you for your feedback.

1. We developed feature to configure the gateway remotely, it will be available in the new release of the ThingsBoard.

2. I think it is a good idea about run Modbus connector as a server. We will implement this.
