### ISSUE TITLE
unit test test_modbus_getting_values fails

### ISSUE THREAD

**Issue by jdevoo** [thingsboard/thingsboard-gateway#296]
**Describe the bug**
I just checked out the 2.3.0 branch and ran `python3 -m unittest discover thingsboard_gateway`
I was trying to generate a docker image from source which took me to `generate_deb_package.sh` but that was failing. I have checked my dependencies but must be missing something still.
TIA!!!!

**Connector name (If bug in the some connector):**
ModBus

**Error traceback (If available):**
```
FAIL: test_modbus_getting_values (tests.ConvertersTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jdevoo/lib/thingsboard-gateway/thingsboard_gateway/tests.py", line 247, in test_modbus_getting_values
    self.assertDictEqual(result, test_modbus_result)
AssertionError: {'dev[295 chars]ts': [False, True, False, True, True, False, T[135 chars]59}]} != {'dev[295 chars]ts': '[False, True, False, True, True, False, [137 chars]59}]}
Diff is 1017 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 7 tests in 7.262s

FAILED (failures=1)
```

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04]
 - Thingsboard IoT Gateway version 2.3.0
 - Python version 3.6.9

**Comment by zbeacon** [comment]
Hi @jdevoo,

Thank you for your interest in ThingsBoard IoT gateway. I was an error in test. I have fixed it, please get the latest version from the master branch and use it.
