### ISSUE TITLE
[BUG] ThingsBoard IoT Gateway stalled on "nan" messages in any mqtt topic

### ISSUE THREAD

**Issue by viktorkho** [thingsboard/thingsboard-gateway#299]
**Describe the bug**
ThingsBoard IoT Gateway with custom converter (I've [described here](https://stackoverflow.com/q/61634163/5239616)) stalled if I publish "nan" message in any topic. E.g.:
```
mosquitto_pub -t /devices/wb-adc/controls/test -m 1      # INFO Successfully converted
mosquitto_pub -t /devices/wb-adc/controls/test -m 2      # INFO Successfully converted
mosquitto_pub -t /devices/wb-adc/controls/test -m nan    # Nothing in log
mosquitto_pub -t /devices/wb-adc/controls/test -m 3      # Nothing in log
```

**Connector name (If bug in the some connector):**
MQTT Connector

**Error traceback (If available):**
Nothing in docker container's output after message published to the topic (to which it is subscribed)

**Versions (please complete the following information):**
 - docker-compose version 1.17.1
 - image: thingsboard/tb-gateway:latest
 - Python 3.6.9

**Comment by zbeacon** [comment]
Hi @viktorkho 

It is an issue with mosquitto_pub, could you try to use 
`mosquitto_pub -t /devices/wb-adc/controls/test -m "NaN"`
instead of 
`mosquitto_pub -t /devices/wb-adc/controls/test -m nan`

I used the custom converter from your question on StackOverflow.

Please try and let me know, about results.

**Comment by viktorkho** [comment]
Hi, @zbeacon 

In this case, the issue is NOT ONLY with mosquitto_pub. My `mosquitto_pub ...` case is just reproduction example.

Originally I faced this problem connecting IoT GW to [Wirenboard](wirenboard.com) 's mosquitto broker. I'll try to cpecify librs they are use. (I don't exclude that it is Paho, just like mosquitto_pub do.)

Is it possible to solve this kind of issues with "nan"? (it will take me much more time to understand your code..)

**Comment by zbeacon** [comment]
@viktorkho 

Thank you for your cooperation, 
I found the issue, it was with message decoding. I fixed it in the develop branch, but the ThingsBoard won't save "null" data.

**Comment by zbeacon** [comment]
@viktorkho 

If you need to save this data, you can check in converter - is it None and save string "None" instead of null value.

**Comment by viktorkho** [comment]
Thank you, @zbeacon !

I found your commit [8a7cd76ac617583cca2ad02ca12ada17546712ea](https://github.com/thingsboard/thingsboard-gateway/commit/8a7cd76ac617583cca2ad02ca12ada17546712ea#diff-7279cbd6be0e8c75dc9f94713681e73b) and tested it, all works fine.
