### ISSUE TITLE
Documented OPC-UA example doesn't work

### ISSUE THREAD

**Issue by LilaLipetti** [thingsboard/thingsboard-gateway#30]
I have installed latest thingsboard + gateway + KEPServerEX
and followed the OPC-UA tutorial
https://thingsboard.io/docs/iot-gateway/getting-started/#step-9-connect-to-external-opc-ua-server

The documented tutorial doesn't work.

See more
https://groups.google.com/forum/#!topic/thingsboard/lBeH7zRSLy0

See my git for raw debug logs
https://github.com/LilaLipetti/thingsboard-opc-testing

**Comment by bodiroga** [comment]
It's a shame that the OPC UA extension doesn't work well, because the whole platform (IoT gateway and server) is awesome!

Many thanks for your hard work and looking forward to seeing this fixed someday!

Best regards,

Aitor

**Comment by mp-loki** [comment]
Fixed in ThingsBoard Gateway versions 1.2.2 and 1.4.0
