### ISSUE TITLE
[BUG] tb-gateway deviceType  doesn't work in thingsboard

### ISSUE THREAD

**Issue by Tracy6465** [thingsboard/thingsboard-gateway#301]
**Describe the bug**
In TB gateway, the devicetype field can be parsed normally, but the deviceType value in thingsboard is default
**Connector name (If bug in the some connector):**
[e.g. MQTT Connector]

**Error traceback (If available):**
tb-gateway parsed result:
![image](https://user-images.githubusercontent.com/4995586/81296928-33209b80-90a5-11ea-8688-dbbaf3742305.png)
thingsboard display:
![image](https://user-images.githubusercontent.com/4995586/81296946-3a47a980-90a5-11ea-89e9-15ce8a570994.png)

**Versions (please complete the following information):**
 - OS: [Mac os 10.15.4]
 - Thingsboard IoT Gateway version [the lasted code of master branch]
 - Python version[3.7]
 - thingsboard version[develop/3.0]

**Comment by zbeacon** [comment]
Hi @Tracy6465 

Thank you for your interest in ThingsBoard IoT gateway.
The deviceType sends only one time on device creation. Probably, it didn't contain the correct value of the device type, when sent first message with this device. 
Please attach logs to investigate it more deeply.
