### ISSUE TITLE
[HELP] Dynamic keys with Default JSON Converter Type

### ISSUE THREAD

**Issue by hamed-boumaiza-protectline** [thingsboard/thingsboard-gateway#305]
Hi,

Is that possible to make the key a dynamic input with the Default JSON Converter Type?

![image](https://user-images.githubusercontent.com/64953666/81949058-ade83a00-9602-11ea-815e-08b0148c8556.png)

For exemple if i have `deviceName=DEVICE-GW400`

`mosquitto_pub.exe -d -h localhost -p 1883 -t /central/add -m "{\"deviceName\": \"DEVICE-GW400\"}"`

So if i type that command i would like that `Key=DEVICE-GW400` & `Value=on`
![image](https://user-images.githubusercontent.com/64953666/81949481-323abd00-9603-11ea-8e89-c7eade810445.png)

**PS : I need to add/update devices each time i type that command.**

**Comment by zbeacon** [comment]
Hi @hamed-boumaiza-protectline 

Thank you for your interest in ThingsBoard IoT gateway. 
This is a good feature, thanks. I've implemented it, you can install the version from the develop/2.4-python branch and check it.

**Comment by hamed-boumaiza-protectline** [comment]
Hi again,

Thank you for fasty reply :)
**After downloading the dev/2.4-python and installing it, I typed this command**

`mosquitto_pub.exe -d -h test.mosquitto.org -p 1883 -t /sensor/data -m "{\"serialNumber\": \"SN001\", \"sensorType\": \"Thermometer\", \"sensorModel\": \"T1000\", \"temp\": 42, \"hum\": 58}"`

**And this is what i got** 

`""2020-05-15 13:44:52" - ERROR - [json_mqtt_uplink_converter.py] - json_mqtt_uplink_converter - 77 - Error in converter, for config:
{"type": "json", "deviceNameJsonExpression": "${serialNumber}", "deviceTypeJsonExpression": "${sensorType}", "timeout": 60000, "attributes": [{"type": "string", "key": "model", "value": "${sensorModel}"}, {"type": "string", "key": "${sensorModel}", "value": "on"}], "timeseries": [{"type": "double", "key": "temperature", "value": "${temp}"}, {"type": "double", "key": "humidity", "value": "${hum}"}]}
 and message:
{'serialNumber': 'SN001', 'sensorType': 'Thermometer', 'sensorModel': 'T1000', 'temp': 42, 'hum': 58}
"
""2020-05-15 13:44:52" - ERROR - [json_mqtt_uplink_converter.py] - json_mqtt_uplink_converter - 78 - argument of type 'int' is not iterable"
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\thingsboard_gateway-2.3.0.1-py3.8.egg\thingsboard_gateway\connectors\mqtt\json_mqtt_uplink_converter.py", line 66, in convert
    if ("${" not in value and "}" not in value) \
TypeError: argument of type 'int' is not iterable
""2020-05-15 13:44:52" - INFO - [mqtt_connector.py] - mqtt_connector - 343 - Successfully converted message from topic /sensor/data"`

**PS: I used the same config files.**

Thanks.

**Comment by zbeacon** [comment]
@hamed-boumaiza-protectline 

I'm also encountering this issue when test it, it is has already been fixed, just make git pull, remove old version using `pip3 uninstall thingsboard-gateway` and install it again.

**Comment by hamed-boumaiza-protectline** [comment]
Well that perfectly works !
Thanks @zbeacon 
I'll keep in touch if there is some new ideas 😄

**Comment by zbeacon** [comment]
@hamed-boumaiza-protectline 
If you will do like in the example, the one more connector will be created. Just add one more device in the MQTT configuration file in the mapping section.
Yes you can use the same topic for different devices.

**Comment by hamed-boumaiza-protectline** [comment]
Can you explain  `Just add one more device in the MQTT configuration file in the mapping section.` ?

**Comment by zbeacon** [comment]
`mapping` section in the mqtt.json - is an array of the objects. Every object configuration is a configuration for different devices, you can just add one more object and configure it. 

For example (2 different devices, with the same topics): 

```
  "mapping": [
    {
      "topicFilter": "/sensor/data",
      "converter": {
        "type": "json",
        "deviceNameJsonExpression": "DEVICE1",
        "deviceTypeJsonExpression": "${sensorType}",
        "timeout": 60000,
        "attributes": [
          {
            "type": "string",
            "key": "model",
            "value": "${sensorModel}"
          }
        ],
        "timeseries": [
          {
            "type": "double",
            "key": "temperature",
            "value": "${temp}"
          },
          {
            "type": "double",
            "key": "humidity",
            "value": "${hum}"
          }
        ]
      }
    },
    {
      "topicFilter": "/sensor/data",
      "converter": {
        "type": "json",
        "deviceNameJsonExpression": "DEVICE2",
        "deviceTypeJsonExpression": "${sensorType}",
        "timeout": 60000,
        "attributes": [
          {
            "type": "string",
            "key": "model",
            "value": "${sensorModel}"
          }
        ],
        "timeseries": [
          {
            "type": "double",
            "key": "temperature",
            "value": "${temp}"
          },
          {
            "type": "double",
            "key": "humidity",
            "value": "${hum}"
          }
        ]
      }
    },
```

**Comment by hamed-boumaiza-protectline** [comment]
No i like it like this.
I need 2 files like "mqtt1.json" & "mqtt2.json"

and its contents like this :

**mqtt1.json**
`"mapping": [
    {
      "topicFilter": "/sensor/data",
      "converter": {
        "type": "json",
        "deviceNameJsonExpression": "${sensorName}",
        "deviceTypeJsonExpression": "${sensorType}",
        "timeout": 60000,
        "attributes": [
          {
            "type": "string",
            "key": "model",
            "value": "${sensorModel}"
          }
        ],
        "timeseries": [
          {
            "type": "double",
            "key": "temperature",
            "value": "${temp}"
          }
        ]
      }
    }
]`

**mqtt2.json**
`"mapping": [
    {
      "topicFilter": "/sensor/data",
      "converter": {
        "type": "json",
        "deviceNameJsonExpression": "${sensorName}",
        "deviceTypeJsonExpression": "${sensorType}",
        "timeout": 60000,
        "attributes": [
          {
            "type": "string",
            "key": "model",
            "value": "${sensorModel}"
          }
        ],
        "timeseries": [
          {
            "type": "double",
            "key": "humidity",
            "value": "${hum}"
          }
        ]
      }
    }
]`


**PS: The difference is in **timeseries****

**Comment by zbeacon** [comment]
You can do like this, but it will be run as a different connector.

**Comment by mpbr13** [comment]
Hello, I've installed tb gateway a few days ago so I'm newbie in this and I'm struggling with mapping. I'm using version 3.3.2 and I've been following [this guide](https://thingsboard.io/docs/iot-gateway/config/mqtt/?mqttConnectorCredentialsConfig=anonymous&MqttConverterTypeConfig=json) so I have added an entry on array in mqtt.json file which is shown below.
![mapping tb gateway](https://user-images.githubusercontent.com/36259853/142491629-76837a47-fb82-4824-b352-85dfda9524c8.PNG)
I though that  deviceNameTopicExpression was taken dynamically from {$serialNumber} but when I check in ThingsBoard this is what I get:
![devices tb gateway](https://user-images.githubusercontent.com/36259853/142492009-b5e9f2d1-44a2-4c4d-9e0e-3083d40c31c9.PNG)
However, in last telemetry section, it shows the latests values of timeseries mapping section ({$Property} and {$Value}).
So I think it is not working or I don't understand the process. Below is the telemetry sent from ESP8266.
![sensor tb gateway](https://user-images.githubusercontent.com/36259853/142492264-6a5d96dd-3982-4cac-8d94-e09a7b60ab2e.PNG)
I would be so thankful if you could help me.

**Comment by zbeacon** [comment]
Hi @mpbr13 ,

If you need a help - please create a new issue instead of writing to the closed one, because sometimes we cannot see notification about your message.

Whenever in your case you can use the following configurations:
1. Using deviceNameJsonExpression - it looks like you have a device name in your message, so you can just use default configuration and set `"deviceNameJsonExpression":"${serialNumber}"` - in this case device name will be `mq135 mesa`
2. Using deviceNameTopicExpression - in order to get device name from topic you should change topicFilter to `"sensor/data/+/mesa"` and deviceNameTopicExpression to regular expression `"(?<=sensor\/data\/)(.*?)(?=\/mesa)"`.


Thank you for your interest in ThingsBoard IoT gateway.

**Comment by mpbr13** [comment]
Thanks a lot @zbeacon!!
