### ISSUE TITLE
[HELP] Using many gateways with tb_gateway

### ISSUE THREAD

**Issue by hamed-boumaiza-protectline** [thingsboard/thingsboard-gateway#307]
Hi @zbeacon,

Is it possible to use many access tokens in tb_gateway.yaml ?

![image](https://user-images.githubusercontent.com/64953666/82058380-f6682c00-96c4-11ea-939a-0364c96a9732.png)

Thanks.

**Comment by zbeacon** [comment]
Hi @hamed-boumaiza-protectline ,

You can use only one accessToken and one server per one gateway. If you need several gateways - please use docker images or several instances of the gateway with different tb_gateway.yaml files( We haven't tested this case for stability yet ).

**Comment by hamed-boumaiza-protectline** [comment]
Thanks for your reply.
