### ISSUE TITLE
Modbus.json configuration issue: help wanted

### ISSUE THREAD

**Issue by PrasannaBluetronics** [thingsboard/thingsboard-gateway#319]
I am using Modbus connector to connect my ESP8266 module(modbus device) through modbus TCP.
 I successfully connected and sent rpc commands to my device that has the "value" in the method.
But I couldn't get the knob control widget values that sends value from the thingsboard dashboard .
Help me to configure my modbus.json file.
This is my modbus.json file:

{
  "server": {
    "name": "Modbus Default Server",
    "type": "tcp",
    "host": "***.***.**.***",
    "port": ***,
    "timeout": 35,
    "rtuOverTcp": false,
    "devices": [
      {
        "unitId": 1,
        "deviceName": "Temp Sensor",
        "attributesPollPeriod": 5000,
        "timeseriesPollPeriod": 5000,
        "sendDataOnlyOnChange": true,
        "attributes": [
          {
            "byteOrder": "BIG",
            "tag": "test",
            "type": "long",
            "functionCode": 3,
            "registerCount": 1,
            "address": 0
          }
        ],
        "timeseries": [
          {
            "byteOrder": "BIG",
            "tag": "temperature",
            "type": "long",
            "functionCode": 3,
            "registerCount": 1,
            "address": 1
          },
          {
            "byteOrder": "BIG",
            "tag": "humidity",
            "type": "long",
            "functionCode": 3,
            "registerCount": 1,
            "address": 2
          }
        ],
        "rpc": {
         "setValue1": {
              "byteOrder":"BIG",
              "tag": "Value",
              "value":1,
              "type":"16int",
              "functionCode": 6,
              "objectsCount": 1,
              "address": 15
          },
         "setValue0": {
              "byteOrder":"BIG",
              "tag": "Value",
              "value":0,
              "type":"16int",
              "functionCode": 6,
              "objectsCount": 1,
              "address": 15
          },
         "setAnalogValue": {
              "byteOrder":"BIG",
              "tag": "Value",
              "type":"16float",
              "functionCode": 6,
              "objectsCount": 1,
              "address": 14
          }
        }
      }
    ]
  }
}

I have successfully got the result for setValue0 and setValue1 methods from control widgets in the thingsboard dashboard, but couldn't get result for the setAnalogValue method. 
I need to control my on board LED of esp8266 from the analog values of the holding register 14.
The setAnalogValue in the RPC is used to get float values from knob control widget of my thingsboard dashboard. 
Help me to get the setAnalogValue configured. Thanks in advance.

**Comment by zbeacon** [comment]
Hi @PrasannaBluetronics 

Thank you for your interest in ThingsBoard IoT gateway. Sorry for the long-term reply.

Please attach your gateway logs and widget configuration for investigation.
