### ISSUE TITLE
[BUG] ThingsBoard IoT Gateway stalled on empty messages

### ISSUE THREAD

**Issue by viktorkho** [thingsboard/thingsboard-gateway#320]
**Describe the bug**
ThingsBoard IoT Gateway with custom converter (the same as in #299) stalled if I publish messages is empty, as well as it contains "`\n`" or "`\r`" or "`\t`"  or backslash only "`\`".

File `thingsboard_gateway/tb_utility/tb_utility.py` is from commit 78deef1

How to reproduce:
```
$ mosquitto_pub -t AJXWI7JX/devices/wb-adc/controls/5Vout -m "5"  # INFO Successfully converted
$ mosquitto_pub -t AJXWI7JX/devices/wb-adc/controls/5Vout -m ""   # Nothing in log, stalled
$ mosquitto_pub -t AJXWI7JX/devices/wb-adc/controls/5Vout -m "5"  # Nothing in log, stalled
```
```
$ mosquitto_pub -t AJXWI7JX/devices/wb-adc/controls/5Vout -m "5"  # INFO Successfully converted
$ mosquitto_pub -t AJXWI7JX/devices/wb-adc/controls/5Vout -m "\"  # Nothing in log, stalled
$ mosquitto_pub -t AJXWI7JX/devices/wb-adc/controls/5Vout -m "5"  # Nothing in log, stalled
```
and so on.

Expected behavior:
- Gateway skips empty messages or/and throws warning into log but stays working.
- Gateway performs both ASCII and non ASCII payload or sanitizes it but stays working.

**Connector name (If bug in the some connector):**
MQTT Connector

Error traceback (If available):
Nothing in docker container's output after message with spaces published to the topic (to which it is subscribed)

Versions (please complete the following information):

docker-compose version 1.17.1
image: thingsboard/tb-gateway:latest
Python 3.6.9

**Comment by zbeacon** [comment]
Hi @viktorkho 

I have changed the tb_utility to solve this issue, please try to use it.

**Comment by zbeacon** [comment]
if you will have any problem with this issue, just reopen it.

**Comment by viktorkho** [comment]
Perfect! Thank you, @zbeacon!
