### ISSUE TITLE
[HELP] How set QoS on thingsboard gateway?

### ISSUE THREAD

**Issue by pehedima** [thingsboard/thingsboard-gateway#332]
Hi together,
it is possible to set QoS at gateway (MQTT) and if yes how to do it?
What is the default?

**Comment by zbeacon** [comment]
Hi @pehedima 

There is no ability to change the QoS using config. To change it, you can change the source code of the library.
Default is 1. Also you can set 0 in the gateway service.

**Comment by viktorkho** [comment]
Еhis is a suitable candidate for placement in the [Configuration properties](https://thingsboard.io/docs/user-guide/install/config/), IMHO.

**Comment by DanielRichart** [comment]
Hello,

Where can I change the source code of the library and how can I set qos to 0 in the service?

Thanks,
Daniel

**Comment by zbeacon** [comment]
Hi to change the quality of server in the gateway please download the version from the master branch and check the tb_gateway.yaml file. There is in the section "thingsboard" is appeared new parameter with name "qos". You can put there QoS, you prefer. The gateway supports 0 or 1 qos.
