### ISSUE TITLE
[HELP] Add requirements.txt

### ISSUE THREAD

**Issue by viktorkho** [thingsboard/thingsboard-gateway#333]
**Describe the issue**
Please. For development and customisation purposes. This will slightly reduce time to start and it is good form in python dev.

This is what I found when running tests:

```
# requirements.txt
jsonpath-rw
paho-mqtt
pyrsistent
pyyaml
requests
simplejson
```

**Comment by zbeacon** [comment]
Hi @viktorkho 

Thank you for your investigations.Required modules for basic installation and first run are in the setup.py file. They are installed on installation process automatically. Other modules are load and install on some connector runs.

**Comment by viktorkho** [comment]
Ok, thank you
