### ISSUE TITLE
[HELP] OPC UA Connection 

### ISSUE THREAD

**Issue by sayyam1994** [thingsboard/thingsboard-gateway#340]
Hello Again,

I am trying to connect to Kepserver using opcua connector in two conditions:-
1) Getting data from a Tag with NodeId:- ns=2;s=Channel1.Device1.Tag1
![Capture](https://user-images.githubusercontent.com/47063178/86612040-251bc800-bfcd-11ea-8974-1513b873a6a7.PNG)

In the above screenshot, I am connecting with the node having a complex path(ns=2;s=Channel1.Device1.Tag1) but I am not getting any data even after successful connection.

2)Getting data from a Tag with NodeId:-ns=2;i=2994
![Capture2](https://user-images.githubusercontent.com/47063178/86612555-efc3aa00-bfcd-11ea-8713-311cfcf7c5ab.PNG)

In the above screenshot,  I am connecting with the node having a simple path(ns=2;s=i=2994) and I am able to get data in thingsboard dashboard.

I have tried it in both Windows and Ubuntu and I am getting the same result.
I also tried it with both exact path and Nodeid but I am getting the same result.

I want to know how to correctly map the complex path in opcua.json

**Configuration** (Attach your configuration file)

**Connector name (If you need help with some connector/converter):**
OPC UA Connector

If you want I can mail the log files.

**Versions (please complete the following information):**
 - OS: Windows 7
 - Thingsboard IoT Gateway version 2.4
 - Python version 3.8

**Comment by joerg555** [comment]
Hi 
Were is the contens of your opcua.json
You need correct deviceidpattern.
