### ISSUE TITLE
[BUG] Modbus downlink converter ignores byteOrder parameter

### ISSUE THREAD

**Issue by everardogentil** [thingsboard/thingsboard-gateway#342]
I have installed tb-gateway on ubuntu and them I seted up a modbus tpc connetor to get data from a energy meter.

This is the modbus tcp config file:

```

{
    "server": {
        "type": "tcp",
        "host": "192.168.0.31",
        "port": 502,
        "timeout": 35,
        "method": "socket",
        "byteOrder": "BIG",
        "devices": [
            {
                "unitId": 2,
                "deviceName": "CUSTOMER\\CM SUL\\GERAL",
                "attributesPollPeriod": 10000,
                "timeseriesPollPeriod": 10000,
                "sendDataOnlyOnChange": false,
                "attributes": [],
                "timeseries": [
                    {
                        "tag": "EP_IN_3F",
                        "type": "32float",
                        "functionCode": 3,
                        "objectsCount": 2,
                        "address": 2699
                    },

```

I have noticed that no matter what value I use to **byteOrder** (BIG or LITTLE) the data is allways converted using **LITTLE** configuration.

May be due the fact that in the **bytes_modbus_downlink_converter.py** script the default value for byteOrder is **LITTLE** and for some reason the value that I have configured is not being recognized.

`class BytesModbusDownlinkConverter(ModbusConverter):

    def __init__(self, config):
        self.__config = config

    def convert(self, config, data):
        byte_order_str = config.get("byteOrder", "LITTLE")
        byte_order = Endian.Big if byte_order_str.upper() == "BIG" else Endian.Little
        builder = BinaryPayloadBuilder(byteorder=byte_order)`

The next pic from Wireshark shows two registers from the meter that represents a 32float:

![image](https://user-images.githubusercontent.com/25008130/87117025-d4ff6880-c24d-11ea-9267-434e16bcaa01.png)

This example is allways converted to 1.6347735882007997E-19 (wrong value) and not to 10.0 (real value from meter).

I would like to know how to fix this.

Thanks in advance.

**Comment by zbeacon** [comment]
Hi @everardogentil, 

Please try to use the version from the master branch, it was an issue with uplink converter.
