### ISSUE TITLE
[HELP] Device type of devices always default MQTT connector even when device type is specified

### ISSUE THREAD

**Issue by jazkiddie** [thingsboard/thingsboard-gateway#349]
Hello, 

Title says it all, I'm using a mqtt connector and thingsboard gateway, I have checked that my syntax is correct and it is even properly fetched in the corresponding json mqtt uplink converter file as shown in the following screenshots
![Capture](https://user-images.githubusercontent.com/62754030/88040550-5954c400-cb49-11ea-9b64-c497d9e1821b.PNG)
and this is what I get when I type `systemctl status thingsboard-gateway.service` on my shell
![Capture](https://user-images.githubusercontent.com/62754030/88040819-c2d4d280-cb49-11ea-9c11-2cb7cf688e2c.PNG)
If this can't be easily fixed, I put the device type as a client attribute and I would like to know if there is a way to put that as the device type.

Edit: 

This is what I have in my thingsboard
![Capture](https://user-images.githubusercontent.com/62754030/88041732-198edc00-cb4b-11ea-8257-d3a8149cda2c.PNG)

**Comment by zbeacon** [comment]
Hi @jazkiddie,

Thank for your interest in the ThingsBoard IoT gateway and feedback. This issue caused by first connection of the device. we will fix it.

**Comment by zbeacon** [comment]
Hi @jazkiddie,

could you check that the first message from your device contains the device type and you are configure correctly your gateway (deviceTypeJsonExpression or deviceTypeTopicExpression). The gateway cannot change the device type after device was created.
