### ISSUE TITLE
[BUG] Duplicated telemetry

### ISSUE THREAD

**Issue by everardogentil** [thingsboard/thingsboard-gateway#351]
Is there any reason for thingsboard-gateway sending duplicated telemetry for each modbus device connected to it?

![image](https://user-images.githubusercontent.com/25008130/88325121-0de21780-ccfb-11ea-9d7d-90c927dab484.png)

The data is being sent from device to tb-gateway only once every 10 seconds.

**Comment by zbeacon** [comment]
Hi @everardogentil 

Thank you for your report, I will investigate this issue next week.

**Comment by zbeacon** [comment]
Hi @everardogentil 

Please attach your configuration file for modbus connector.

**Comment by everardogentil** [comment]
@zbeacon ,
here is the config file:

[modbus_tcp.json.txt](https://github.com/thingsboard/thingsboard-gateway/files/4982598/modbus_tcp.json.txt)

**Comment by zbeacon** [comment]
Hi @everardogentil ,

I found and fixed the bug, please try to use the version from the master branch and let me know about the results.

**Comment by everardogentil** [comment]
Thank you, @zbeacon . I will try.
