### ISSUE TITLE
[HELP] Modbus connector has been stopped

### ISSUE THREAD

**Issue by everardogentil** [thingsboard/thingsboard-gateway#352]
After a while trying to connect to modbus devices the tb-gateway raise this information at connector.log.

![image](https://user-images.githubusercontent.com/25008130/88326962-f9068380-ccfc-11ea-9549-89a8b8986cc9.png)

Now, even the modbus devices are online the tb-gateway does not connect to them. 

How can I restart the modbus connector?

**Comment by zbeacon** [comment]
Hi @everardogentil,

The gateway can connect only to Modbus server, currently. We are going to add ability to connect to Modbus devices in one of the future releases.

**Comment by everardogentil** [comment]
I think was not so clear. The problem occurs with connection to masters (in this case energy meters). Even with the meters connected to the network the tb-gw does not connect to them. It is like the connector has freezed and needs some restart to connect again.

**Comment by zbeacon** [comment]
Hi @everardogentil ,

Please try to use the latest version of the gateway.
