### ISSUE TITLE
[HELP] Get telemetrie value from Modbus connector

### ISSUE THREAD

**Issue by JFMALBI** [thingsboard/thingsboard-gateway#356]
Hi sirs,

We are using a PE version 3.0.1 of ThingsBoard. We installed the Thingsboard IoT Gateway in order to get data from devices which use a Modbus TCP protocol to communicate. This IoT Gateway works to import attributes data : we can visualize the value and the name of attributes on the ThingsBoard device. 
However, when we try to import data through telemetries and not through on the modbus.json file, we can't visualize the data on ThingsBoard and we have an error message. 

You will find attached our modbus.json file, our tb_gateway.yaml file, a picture of the error message, a picture of our device (it is a simulated device), a picture of client attributes on TB and a picture of latest telemetry on TB.

Thank you for your help,

[modbus.json_file.pdf](https://github.com/thingsboard/thingsboard-gateway/files/5006942/modbus.json_file.pdf)
[tb_gateway.yaml .pdf](https://github.com/thingsboard/thingsboard-gateway/files/5006943/tb_gateway.yaml.pdf)
 

[Client attributs.pdf](https://github.com/thingsboard/thingsboard-gateway/files/5006969/Client.attributs.pdf)
[Error message.pdf](https://github.com/thingsboard/thingsboard-gateway/files/5006970/Error.message.pdf)
[Latest telemetry.pdf](https://github.com/thingsboard/thingsboard-gateway/files/5006971/Latest.telemetry.pdf)
[Simulated device.pdf](https://github.com/thingsboard/thingsboard-gateway/files/5006972/Simulated.device.pdf)

[Modbus Connector]
 - OS: [Ubuntu 18.04]
 - Thingsboard IoT Gateway version [2.5.0]
 - Python version[3.6.9]

**Comment by zbeacon** [comment]
Hi @JFMALBI ,
Thank you for your interest in the ThingsBoard IoT gateway.
It can be the issue with addressing, but to be sure in this, please give the ssh credentials to the machine with the gateway via email. My email is ibarkov@thingsboard.io
