### ISSUE TITLE
[HELP] using modbus via ethernet,eth0, and internet with wireless lan,wlan0 ?

### ISSUE THREAD

**Issue by ahweeuhl** [thingsboard/thingsboard-gateway#395]
**Describe the issue**
how would I configure the modbus.conf file to point to eth0? for example the device is hardwired to the LAN port of the raspberry Pi. but the internet connection is on wireless, wlan0. 

how do i configure such that it points to the ethernet connection? The application works if place both devices in a router, but that won't be an elegant solution. 

**Connector name (If you need help with some connector/converter):**
Modbus Connector

**Versions (please complete the following information):**
 - OS: Raspbian BUSTER
 - Thingsboard IoT Gateway version [2.5]
 - Python version[e.g. 3.7]

**Comment by zbeacon** [comment]
Hi @ahweeuhl 

Usually this is resolving by network manager, but you are able to add route manually to send traffic to some endpoint using specified gateway. You can read more [here](https://my.esecuredata.com/index.php?/knowledgebase/article/2/add-a-static-route-on-centos).
