### ISSUE TITLE
lack of Modbus contiguous block of holding registers 

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard-gateway#406]
After checking the source code, I think it lack of Modbus contiguous block of holding registers. At the moment it read invidual register. But with some devices require a communication frame interval such as 300 ms, what happens if we need to read 50 registers ? to long to read (300ms x 50 ) ?

**Comment by zbeacon** [comment]
Hi @anhdv1979 ,

Unfortunately, yes - we have to read and process every telemetry/attribute key one by one, because we have to separate them in ThingsBoard. So yes, it will take some time to process them.
