### ISSUE TITLE
[BUG] Mismatch of data types TB vs. TB Gateway (OPC UA) vs. PLC Tag

### ISSUE THREAD

**Issue by ExPS-Pisko** [thingsboard/thingsboard-gateway#409]
I experienced a problem in data consistency between Thingsboard (3.0) and TB Gateway (2.3.1).

I use the Shared attribute of a Real (Double Real = Floating point number) type. But when I try to write a Value 30, the format of the value is automatically changed in TB to Integer. The integer is channeled to TB Gateway, however, ends up with error: The value supplied for the attribute is not of the same type as the "attributes value" (BadTypeMismatch).

This happens also when I write 30.0 in TB.

The value is successfully written to Gateway and down to my PLC only if 30.1 is given. This time the TB keeps the floating point nuber format and all goes right?

Is there a way to prevent this data type change in TB or a way to configure TB Gateway to accept/convert somehow the suplied value to Float?

Best regards

**Comment by zbeacon** [comment]
Hi @ExPS-Pisko ,

Thank you for your report, it is a bug in ThingsBoard UI, I send bug report to our UI developers. I will here when it will be fixed.
