### ISSUE TITLE
[BUG] Handling of messages from TB Gateway - no timestamp???

### ISSUE THREAD

**Issue by ExPS-Pisko** [thingsboard/thingsboard-gateway#410]
Windows, TB 3.0, TB Gateway 2.3.1 (OPC UA)

I made a following test (high data traffic):

Data at the source changing very fast in ascending order. The TB Gateway seems to get the data in time, I also see the correct timestamp in the log. However, in TB, the data start to come with the gaps, like: 1, 2, 3, 4, 7, 9, 10, 15 and so on. When the load stops and the value does not change at the source, I am receiving in TB the missing data for several more seconds (like 30s), getting: 5, 6, 14, 8 etc. in random order. The final value in TB is the last value that came from TB Gateway (8 in this case), regardless of the actual value in the source (15).

It seems to me that the data (messages) between TB Gateway and TB are supplied without timestamt, leading to a havoc in data consistency when the data load is over some TB capabilities...

The UA Connector configuration is:
"server": {
    "name": "OPC-UA Default Server",
    "url": "192.168.0.1:4840",
    "scanPeriodInMillis": 1000,
    "timeoutInMillis": 5000,
    "disableSubscriptions":false,
    "showMap": true,
    "security": "Basic128Rsa15",
    "identity": {
      "type": "anonymous"
    }

The gateway storage config is:
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000

Is there some setting of the Gateway I am missing? Are you avare of this behavior and plan some updates?

Best regards

**Comment by zbeacon** [comment]
Hi @ExPS-Pisko ,

Messages from gateway to ThingsBoard doesn't contain inside timestamp, except telemetry values. You can see gaps because the gateway sends data when it read it from storage. Also, if message from broker doesn't contain ts the gateway sets up timestamp when it adds it into storage.
