### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chetan140293** [thingsboard/thingsboard-gateway#437]
**Describe the bug**
when we have upgrade the Gateway from 2.5.1 to 2.5.5. in the raspberry pi gateway.

**Connector name (If bug in the some connector):**
name: Modbus Connector
type: modbus
configuration: modbus.json

**Error traceback (If available):**
AttributeError: 'NoneType' object has no attribute 'upper'
""2020-12-07 16:24:05" - ERROR - [bytes_modbus_uplink_converter.py] - bytes_modbus_uplink_converter - 84 - 'NoneType' object has no attribute 'upper'"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/thingsboard_gateway/connectors/modbus/bytes_modbus_uplink_converter.py", line 48, in convert
    word_endian_order = Endian.Little if word_order.upper() == "LITTLE" else Endian.Big

**Versions (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Thingsboard IoT Gateway version [2.5.5]
 - Python version[3.7]

**Comment by zbeacon** [comment]
Hi @chetan140293 ,

Thank you for information, please try to remove thingsboard-gateway from your system using the following command:

`sudo pip3 uninstall thingsboard-gateway -y` and `pip3 uninstall thingsboard-gateway -y`

and then install it again using pip:

`sudo pip3 install thingsboard-gateway --upgrade`
