### ISSUE TITLE
[BUG] Device Type 'default' problem

### ISSUE THREAD

**Issue by demirizZz** [thingsboard/thingsboard-gateway#439]
I am using the IoT Gateway MQTT Connector. 
I get the device type in the configuration as $ {deviceType} from the mqtt message.

The device type is mapped differently, most of the time it is saved as default.

`"mapping": [
    {
      "topicFilter": "/danfoss/data",
      "converter": {
        "type": "json",
        "deviceNameJsonExpression": "${serialNumber}",
        "deviceTypeJsonExpression": "${deviceType}",
        "timeout": 60000,
        "timeseries": [
          {
            "type": "string",
            "key": "${dataKey}",
            "value": "${dataValue}"
          }
        ]
      }
    },`

IoT Gateway is the latest version. 

How can i fixed it?

**Comment by samson0v** [comment]
Hi, Buğra Demiriz, if you want to override default device type you can use the next mqtt msg via terminal:
`mosquitto_pub -h 127.0.0.1 -p 1884 -t "/sensor/data" -m '{"serialNumber": "asd", "hum": 1, "temp": 1, "sensorModel": "asd", "deviceType": "Device"}'`
