### ISSUE TITLE
[HELP] Turn-off gateway statistics

### ISSUE THREAD

**Issue by hazarmutgan** [thingsboard/thingsboard-gateway#440]
Is there a way to turn off the gateway statistics to be send to Thingsboard, or changed the frequency? It creates lot of datapoints and rule engine calls.

**Versions (please complete the following information):**
 - OS: Ubuntu 20.0.4
 - Thingsboard IoT Gateway version 2.5.4
 - Python 3.8

**Comment by zbeacon** [comment]
Hi @hazarmutgan ,

Thank you for your interest in ThingsBoard IoT gateway. There is no option to change it from configuration. You may do this only by changing the code of the library.

**Comment by deepthi30192** [comment]
Hi Illia,

I guess you sent the reply to the wrong person. I am not @hazarmutgan<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhazarmutgan&data=04%7C01%7C%7Cc2a720c4090b455b5ad008d8a64a59a8%7C4643991463b7464e83279b13737ae8cf%7C1%7C0%7C637442185573325259%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Pc1mVGiuMKcFaoWJmQAUbIHWF6jsRR%2Fd0Qtl%2FSJ0JdM%3D&reserved=0> . My GitHub name is Deepthi Pisupati. I reached out with a different issue.


Regards,
Deepthi
________________________________
