### ISSUE TITLE
Permission denied issues

### ISSUE THREAD

**Issue by leeweizhang1006** [thingsboard/thingsboard-gateway#445]
https://thingsboard.io/docs/iot-gateway/getting-started/
I follow the instruction in this website and when I to Step 3: Gateway configuration

typing the code below 

`/etc/thingsboard-gateway/config/tb_gateway.yaml`

I get this error

-bash: /etc/thingsboard-gateway/config/tb_gateway.yaml: Permission denied

Can anyone help me?

**Comment by alexvermeersch** [comment]
sudo chmod -R 777 /etc/thingsboard-gateway/config/
will grant you permission to modify
