### ISSUE TITLE
[HELP]Is there any Siemens S7 Ethernet protocol development plan?

### ISSUE THREAD

**Issue by Jaasdsa** [thingsboard/thingsboard-gateway#455]
Is there any Siemens S7 Ethernet protocol development plan?
有没有西门子S7以太网协议开发计划？

**Comment by zbeacon** [comment]
Hi @Jaasdsa ,

There are currently no plans to implement this protocol in a gateway, but if you are familiar with Python, you can write your own connector to use it.
