### ISSUE TITLE
[BUG] strange behavior of modbus byteOrder inheritance

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard-gateway#468]
**Describe the bug**
`byteOrder` can be defined in `server` level and `tag` level. However, it seems that `byteOrder` setting of `tag` is not inherited for the `server` it belongs to. This behavior is not straight forward and I must write byteOrder to every tag. I doubt this behavior also happens to `wordOrder` but I did not test it.

**Connector name (If bug in the some connector): modbus**
[e.g. OPC-UA Connector]

**Error traceback (If available):**
no error

**Versions (please complete the following information):**
 - OS: windows 10
 - Thingsboard IoT Gateway version: 2.5.4
 - Python version: 3.7

**Comment by zbeacon** [comment]
Hi,

Could you try to use the latest version from the master branch and test this issue there?
