### ISSUE TITLE
[HELP] Modbus server that only supports one thread but has multiple devices.

### ISSUE THREAD

**Issue by gzlz** [thingsboard/thingsboard-gateway#473]
My Modbus server only supports one thread but has multiple devices.  For that only the first device telemetry is showed in thingsboard.
I would like to know if is possible to configure the modbus.json file in a way that force the gateway to do the devices requests one by one, only in one thread.

Thank you!

[modbus.json.txt](https://github.com/thingsboard/thingsboard-gateway/files/5919751/modbus.json.txt)

**Versions:**
-The gateway is running over the latest docker installation in a raspberry pi.
-The server is a Ubuntu Server 20.04.1 LTS]

**Comment by Pawol85** [comment]
I have the same problem (BUG?)

**Comment by samson0v** [comment]
Hi @gzlz, it seems from your config file that you are using the same unitId for different devices
![photo_2021-11-10 11 18 41](https://user-images.githubusercontent.com/43861229/141085532-8f17e808-e612-430c-a636-52ff519dfa08.jpeg)

Thanks for your interest in ThingsBoard IoT Gateway!

**Comment by samson0v** [comment]
Hi @gzlz and @Pawol85, we remake the Modbus connector, so you can try and test it (using the version from the master branch)!
Pay attention, that there is a new config file for Modbus, to use it, you have to run Gateway with the old config file for Modbus and Gateway generate a new config file that will be named as "new_modbus.json" in the `config/` folder. And finally, in the `tb_gateway.yml` config file use the new Modbus config file.

If you have some questions, feel free to ask them!

**Comment by samson0v** [comment]
Hi @gzlz and @Pawol85, did you try the new version of Modbus Connector, can we close the issue?
