### ISSUE TITLE
[HELP] - Connection with an external MQTT broker which has a self-signed certificate

### ISSUE THREAD

**Issue by frasavino** [thingsboard/thingsboard-gateway#483]
**Describe the issue**
Hi, I have the following problem. I'm trying to connect to an external MQTT broker which has a self-signed certificate. I have an username and a password but I'm not able to connect to it because of the problem of this self-signed certificate. I have a MQTT Connector for ThingsBoard IoT Gateway  but i don't know how to configure the security section. I tried: 

"security": {
      "type": "basic",
      "username": "user",
      "password": "password"
    }

But it doesn't work. I also have the .pem and .crt files related to the self-signed certificate. Is there a way to insert them in the configuration of the MQTT connector in addition to the username and password? Thank you very much!

**Connector name (If you need help with some connector/converter):**
MQTT Connector

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04
 - Thingsboard Professional Edition 
 - Thingsboard IoT Gateway version [2.5.5.2]

**Comment by zbeacon** [comment]
Hi @frasavino ,

Thank you for your interest in ThingsBoard IoT gateway. You can use parameters username, password, caCert, cert, privateKey at the same time, without type parameter.
