### ISSUE TITLE
[Info] Use the gateway without the platform ThingsBoard

### ISSUE THREAD

**Issue by DeveloperZiggy** [thingsboard/thingsboard-gateway#487]
Hi,

I would like to use the gateway without the platform Thingsboard. I tried to connect the gateway using MQTT on Mosquitto broker directly but the gateway crash after it sends 1 telemetry. I know that its not your main objective. But, Do you plan in yours futures releases a possibility to connect with something else ? (Like Mosquitto Broker)

If you're interested, when I configure Mosquitto with ACLs to restrict topic, its works. But, I give only one right (write or read) access on the topic v1/gateway/attributes.

Content ACL file : 

user tbgateway #ACCES_TOKEN gateway
topic write v1/gateway/attributes # or topic read v1/gateway/attributes
topic v1/gateway/attributes/request
topic v1/gateway/attributes/response
topic v1/gateway/telemetry
topic v1/gateway/rpc
topic v1/gateway/rpc/#
topic v1/devices/me/rpc/#
topic v1/devices/me/attributes
topic v1/devices/me/attributes/#
topic v1/devices/me/telemetry
user **_client_** #username with all rights, example : mosquitto_pub -h IP -p PORT -u **_client_** -t TOPIC -m MESSAGE
topic #

I think the problem is that gateway publish and subscribe on the same topic v1/gateway/attributes. The gateway reads its own message on this topic. The message doesn't respect the expected format and the gateway crash.

I don't speak english fluently, sorry for that :/

**Comment by zbeacon** [comment]
Hi @DeveloperZiggy ,

It is a ThingsBoard IoT gateway, so it will work only with ThingsBoard. We are not going to implement other platforms in our gateway. We can implement only connectors to get data from other platforms, but not to save data there.
