### ISSUE TITLE
Zigbee Protocol

### ISSUE THREAD

**Issue by martin9115** [thingsboard/thingsboard-gateway#501]
Hi, can we add Zigbee protocol to the Gateway?

**Comment by zbeacon** [comment]
Hi @martin9115 ,

Thank you for your interest in ThingsBoard IoT gateway. Yes, you can do this, according to license. If you will add Zegbee connector and create a pull request, we will review it and merge into the repository.

**Comment by martin9115** [comment]
Im new with ThingsBoard IoT gateway, can you show me an example how to do this?

**Comment by zbeacon** [comment]
@martin9115 

Please read this guide https://thingsboard.io/docs/iot-gateway/custom/ , It will be helpful to you for understanding how you can create a connector.
