### ISSUE TITLE
[HELP] Integrate Mysensors with Thingsboard

### ISSUE THREAD

**Issue by garudaonekh** [thingsboard/thingsboard-gateway#502]
**Describe the issue**
I want to send MySensor data to Thingsboard so it's necessary to map the dataformat between the two. I have done the Thingsboard deploiyment and submit directly to Thingsboard cloud but have no idea if it's configurable to map the data from Mysensors to Thingsboard or need to customize the Gateway code or override something.

[https://github.com/mysensors/MySensors](url)

Here's the Mysensors data format: https://www.mysensors.org/download/serial_api_20

**Connector name (If you need help with some connector/converter):**
Devices will pass data to the gateway thru NRF24

**DEVICE**
I will use ESP32 as the Gateway.

**Comment by samson0v** [comment]
Hi @garudaonekh, if you want to use your specific data format and custom logic to reproduce your data, you can use [custom connector](https://thingsboard.io/docs/iot-gateway/custom/).
Thanks for your interest in ThignsBoard IoT Gateway!
