### ISSUE TITLE
[HELP] Thingsboard IOT gateway - Not getting telemetry values for MODBUS.

### ISSUE THREAD

**Issue by NikhilM-Dev** [thingsboard/thingsboard-gateway#507]
In my windows 10 machine i  have installed 
 - Thingsboard community edition, 
 - Thingsboard IOT Gateway master (python module) and its running successfully

But when i run the script for getting values through MODBUS connector from modbus.json, device mentioned in the json file getting created but the telemetry and attribute mentioned in the modbus.json is not found in the Thingsboard instance.

Please give me a solution.

**Comment by zbeacon** [comment]
Hi @NikhilM-Dev ,

Thank you for your interest in ThingsBoard IoT gateway. but unfortunately, we cannot help you with your issue, because of you didn't provide any information about your configuration (Configuration files, logs, etc.).
