### ISSUE TITLE
[HELP] Data restore if TB instace has internal problems

### ISSUE THREAD

**Issue by TheSamabo** [thingsboard/thingsboard-gateway#509]
Hi,
I 've got a problem with the tb gateway in a sense that, if my TB instance is for example down or there is an internal problem with the database will the gateway send all of its data or just some snippet when it detects the TB instance is down?

I 've had a situation where our TB instance was ok but its wasn't saving any data to Cassandra DB, and the gateway didn't send any data back to the instace after i restarted TB and Cassandra instace.

 - TB Instance OS: Ubuntu 18.04 LTS
 - TB Message Queue: Kafka
 - TB Instance DB: Hybrid Postgresql/Cassandra
 - Gateway OS: Ubuntu Server 20.04
 -  - Thingsboard IoT Gateway version: 2.5.5.2
 - Python version: 3.8.5

**Comment by zbeacon** [comment]
Hi @TheSamabo ,

The gateway checks response from ThingsBoard MQTT transport service after data sending. And if the gateway receives acknowledge message, we think that the data was transferred successfully. The gateway is not responsible for data saving in the ThingsBoard database. I can only suggest to try the newest version of ThingsBoard and if the issue appears again - please let us know by creating the issue on ThingsBoard repository or by email.
