### ISSUE TITLE
[Feature Request] Support shared subscriptions for load balancing with multiple gateways

### ISSUE THREAD

**Issue by nan0o** [thingsboard/thingsboard-gateway#514]
I would like to request support for [shared subscriptions](https://docs.emqx.io/en/broker/v4.2/advanced/shared-subscriptions.html) with the MQTT Connector.

![image](https://user-images.githubusercontent.com/48364662/117012565-7831da80-acc5-11eb-8c71-08e382b387cd.png)

I have been able to reproduce this modifying a line in the code in [thingsboard_gateway/connectors/mqtt/mqtt_connector.py](https://github.com/thingsboard/thingsboard-gateway/blob/b2ba956a1f17f61885388f83e889f2ede9af9436/thingsboard_gateway/connectors/mqtt/mqtt_connector.py#L332) in line 337.

I changed:
`topic_handlers = [regex for regex in self.__mapping_sub_topics if fullmatch(regex, message.topic)]`
to:
`topic_handlers = [regex for regex in self.__mapping_sub_topics if fullmatch(regex.removeprefix("$queue/", message.topic)]`

This way, the topic reported from the Broker gets matched with the configuration's.

This is considering you are running Thingsboard Gateway in Python 3.9.x. In [dockerhub](https://hub.docker.com/r/thingsboard/tb-gateway/tags?page=1&ordering=last_updated) the latest tb-gateway image runs in Python3.9 which adds the .removeprefix() method for strings. It would be nice if the Dockerfile could be bumped to the latest version as well.

I know this can be done in a more efficient/cleaner way but I would like this to be implemented correctly in the future. Let me know what you think!

**Comment by samson0v** [comment]
Hi @nan0o, thanks for your proposal, we will discuss it and let you know.

Thanks for your interest in ThingsBoard IoT Gateway.
