### ISSUE TITLE
[BUG] in OPC-UA connector for variables in path format

### ISSUE THREAD

**Issue by jfrancoVicomtech** [thingsboard/thingsboard-gateway#517]
**Describe the bug**
The OPC-UA connector doesn't read properly the variables in path format in full path format if they are not just belong Root/Objects. I've been researching and this is caused by get_node_path function inside opcua_connector.py; It returns always the structure Root.Objects + name of the input node. So that, in the case of getting the path of a node with a intermediate path it doesn't return the correct path. For example:

A node with path ${Root\\.Objects\\.Device0001\\.sensor1}  is returned in the function get_node_path as Root.Objects.sensor1 which doesn't match with the original path that would be Root.Objects.Device0001.sensor1 being never read and sent to thingsboard.

To correct this bug I rewrite the get_node_path function and I can merge it. The new function would be as follows:

```
def get_node_path(self, node):
    return ".".join([current.get_browse_name().Name for current in node.get_path()])
```

**Connector name (If bug in the some connector):**
OPC-UA Connector

**Versions (please complete the following information):**
 - OS: any
 - Thingsboard IoT Gateway master
 - Python version 3.9.1

**Comment by zbeacon** [comment]
Hi @jfrancoVicomtech ,

Thank you for your participating in the project life, could you check the version form the master branch? It seems like this issue isn't present there.

**Comment by zbeacon** [comment]
But get_node_path is different in master branch:

https://github.com/thingsboard/thingsboard-gateway/blob/master/thingsboard_gateway/connectors/opcua/opcua_connector.py#L452

**Comment by jfrancoVicomtech** [comment]
Hi @zbeacon,

You are right, I had done pull against my own repository, not against the central. I checked it and it works correctly.

Thanks and sorry for the inconvenience!
