### ISSUE TITLE
thingsboard gateway modbus, the Boolean type cannot get the correct data

### ISSUE THREAD

**Issue by RenCisco** [thingsboard/thingsboard-gateway#518]
i am configring thingsboard-gateway ,about modbus Connection over TCP/UDP protocol. 
The data type of device is boolean type,Example:
 "timeseries": [
          {
            "tag": "test",
            "type": "bits",
            "functionCode": 2,
            "objectsCount": 1,
            "address": 1
          }
        ],
But all the data of device is false. use 'modbus poll' of tools test ，result  has 1(one) or  0(zero).
Please tell me how to solve this problem
 Tanks a lot!
```


**Versions (please complete the following information):**
 - OS: [CentO S7  ]
 - Thingsboard IoT Gateway version [e.g. 2.6]
 - Python version[e.g. 3.6]
 - Thingsboard 3.2.2

**Comment by zbeacon** [comment]
Hi @RenCisco ,

Thank you for your interest in ThingsBoard IoT gateway. Please try to add configuration field "bit" with a number of bit in the register to get data from one bit. 

```

{
"tag": "test",
"type": "bits",
"bit": 3,
"functionCode": 2,
"objectsCount": 1,
"address": 1
}

```
