### ISSUE TITLE
How to explore data from OPC-UA devices?

### ISSUE THREAD

**Issue by eugene08** [thingsboard/thingsboard-gateway#52]
I met a problem in my exploration, The opc-ua server can connection successful.
But cannot read tag value in devices, No changes have been made to any of the gateway files.
Does KEPServer the expiration have an impact?

Please help me check where is a problem.
Thanks!

**Comment by mp-loki** [comment]
Hi @eugene08 ! Could you please tell which ThingsBoard and Gateway versions are you using?

**Comment by eugene08** [comment]
Hi @mp-loki ，Thanks for your reply. ThingsBoard is currently version 1.4.0 and gateway is currently version 1.2.1.

**Comment by mp-loki** [comment]
Please check out the gateway release 1.2.2. OPC-UA extension had issues in 1.2.1.

**Comment by eugene08** [comment]
Thanks, I went to try. :-)

**Comment by mp-loki** [comment]
Hi @eugene08. Is this issue resolved? If no more concerns, I'll close it
