### ISSUE TITLE
Snmp v3

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard-gateway#523]
It seams that your gateway uses puresnmp, which seems that doesn’t support snmpv3

**Comment by zbeacon** [comment]
Hi @anhdv1979 ,

Thank you for your interest in ThingsBoard IoT gateway. Yes, you are right, the gateway doesn't support SNMP v3, but we will add SNMP transport in ThingsBoard in one of the future releases. Look forward for ThingsBoard updates.
