### ISSUE TITLE
[HELP]I want to use the OPC UA protocol to implement the control device.

### ISSUE THREAD

**Issue by adminlzq6** [thingsboard/thingsboard-gateway#524]
**Describe the issue**
Create description about your issue, and your actions to solve it.
I want to set the "temperature" through the "set_value" method,but the result was beyond my expectation,the RPC request results in timeout.What can I do to set the "temperature" correctly with RPC?
my python opc server:
[test_opcua_connector.txt](https://github.com/thingsboard/thingsboard-gateway/files/6537649/test_opcua_connector.txt)
my  opc device:
![image](https://user-images.githubusercontent.com/54979078/119459595-6ac1ba80-bd70-11eb-9835-8ec23926baba.png)
root rule chain:
![image](https://user-images.githubusercontent.com/54979078/119459856-a8bede80-bd70-11eb-92a1-361bf5374823.png)
![image](https://user-images.githubusercontent.com/54979078/119460104-e91e5c80-bd70-11eb-8476-4374af983c57.png)
result of rpc request:
![image](https://user-images.githubusercontent.com/54979078/119460653-7c579200-bd71-11eb-82b1-9121a1cc22f2.png)
![image](https://user-images.githubusercontent.com/54979078/119460762-942f1600-bd71-11eb-94a5-eae2901ba835.png)
![image](https://user-images.githubusercontent.com/54979078/119460248-12d78380-bd71-11eb-9382-cd6eb927ea18.png)

**Configuration** (Attach your configuration file)
**Notate: Remove Access token from file if you wanna attach tb_gateway.yaml**
![image](https://user-images.githubusercontent.com/54979078/119456411-3ac4e800-bd6d-11eb-8d18-85d63e47e9fa.png)

**Connector name (If you need help with some connector/converter):**
Opcua Connector
opcua.json
![image](https://user-images.githubusercontent.com/54979078/119456916-b6bf3000-bd6d-11eb-9239-febf43d80b11.png)

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04
 - Thingsboard IoT Gateway version 2.6
 - Thingsboard Community
 - Python version 3.6

**Comment by samson0v** [comment]
Hi @adminlzq6, we decided to implement standard service RPC methods: get and set. These methods will be added to every OPC-UA node. So you can easily read and write data from the OPC-UA node.
Examples of use:
<img width="174" alt="зображення" src="https://user-images.githubusercontent.com/43861229/140485895-bb9aea28-4639-427d-848a-917124163eb1.png">
<img width="376" alt="зображення" src="https://user-images.githubusercontent.com/43861229/140485951-ce253de6-9729-455f-bec7-279916aaf967.png">
<img width="218" alt="зображення" src="https://user-images.githubusercontent.com/43861229/140485977-7a370a8a-eec9-4626-8dcb-a50bec03bcce.png">
