### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by GretiCani** [thingsboard/thingsboard-gateway#525]
I'm facing issues with request connector
When I run Tb_gateway I'm getting error 208
""2021-06-01 14:30:36" - ERROR - [request_connector.py] - request_connector - 208 - Timeout error on request http://192.168.1.43:8089/getdata."
""2021-06-01 14:30:46" - ERROR - [request_connector.py] - request_connector - 208 - Timeout error on request http://192.168.1.43:8089/getdata."
""2021-06-01 14:30:56" - ERROR - [request_connector.py] - request_connector - 208 - Timeout error on request http://192.168.1.43:8089/getdata."
""2021-06-01 14:31:06" - ERROR - [request_connector.py] - request_connector - 208 - Timeout error on request http://192.168.1.43:8089/getdata."

Response from api is {"serial":"serialNR","developer":"devname"}. I am using docker tb_gateway. 

**Configuration** 

{
  "host": "http://192.168.1.43:8089",
  "SSLVerify": true,
  "security": {
    "type": "anonymous"
  },
  "mapping": [
    {
      "url": "getdata",
      "httpMethod": "GET",
      "httpHeaders": {
        "ACCEPT": "application/json"
      },
      "allowRedirects": true,
      "timeout": 5,
      "scanPeriod": 10,
      "converter": {
        "type": "json",
        "deviceNameJsonExpression": "SD8500",
        "deviceTypeJsonExpression": "SD",
        "attributes": [
          {
            "key": "serialNumber",
            "type": "string",
            "value": "${serial}"
          }
        ],
        "telemetry": [
          {
            "key": "Maintainer",
            "type": "string",
            "value": "${developer}"
          }
        ]
      }
    } 
....
....
**Notate: Remove Access token from file if you wanna attach tb_gateway.yaml**

thingsboard:
  host: 53.178.89.216
  port: 2883
  remoteShell: true
  remoteConfiguration: true
  security:
    accessToken: token***
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
connectors:
  -
    name: REQUEST Connector
    type: request
    configuration: request.json

**Versions (please complete the following information):**

 - OS: Ubuntu 20.04
 - Thingsboard IoT Gateway latest docker version thingsboard/tb-gateway
 - Python version 3.7

**Comment by samson0v** [comment]
Hi GretiCani, do you running an HTTP server (192.168.1.43) on your local machine? If yes, why are you using a local IP network?
You have to use 127.0.0.1:8089
