### ISSUE TITLE
RPi with opcua server

### ISSUE THREAD

**Issue by Shining9311** [thingsboard/thingsboard-gateway#528]
**Describe the issue**
Hi
I want to use RPi with opcua server. I install Thingsboard IoT Gateway and use IoT Gateway Configuration guide for configuring it. i replace Access Token and Connector in tb_gateway.yaml and i got error about conncecting. after that i change local host with RPi ip address, srial number of device and showMap(false -> true) in opcua.json file and again i got errors:
""2021-06-13 19:33:24" - WARNING - [tb_updater.py] - tb_updater - 85 - Cannot connect to the update service. PLease check your internet connection."
""2021-06-13 19:33:29" - ERROR - [opcua_connector.py] - opcua_connector - 110 - Connection refused on connection to OPC-UA server with url 192.168.1.118:4840/freeopcua/server/"

please help me to fix it
thanks

**Configuration** (Attach your configuration file)
**Notate: Remove Access token from file if you wanna attach tb_gateway.yaml**

**Connector name (If you need help with some connector/converter):**
[OPCUA Connector]

**Error traceback (If it was raised):**
```
'deviceName'
Traceback (most recent call last):
  File "<input>", line 2, in <module>
KeyError: 'deviceName'
```

**Versions (please complete the following information):**
 - OS: [Raspbian GNU/Linux 10 (buster)]
 - Thingsboard IoT Gateway version [2.6]
 - Python version[3.7.3
[tb_gateway.yaml.txt](https://github.com/thingsboard/thingsboard-gateway/files/6644118/tb_gateway.yaml.txt)
]

**Comment by samson0v** [comment]
Hi @Shining9311 , please provide info about your opcua config file (config/opcua.json) and the structure of your OPC-UA server.
Thanks for your interest in ThingsBoard IoT Gateway!
