### ISSUE TITLE
Gateway not working on thingsboard - Ubuntu 16.04

### ISSUE THREAD

**Issue by BeIllegalBeagle** [thingsboard/thingsboard-gateway#53]
Problem

I have the EMQ mqtt broker running fine on my ubuntu build, and can run everything it is expected to.
I am trying to connect my EMQ broker to Thingsboard using the gateway, however Thingsboard does not acknowledge the gateways connection, yet my EMQ broker does as shown:

![screenshot from 2018-04-03 16-54-03](https://user-images.githubusercontent.com/38043915/38257168-0c3ac432-3760-11e8-8185-bb96f5917b54.png)

![screenshot from 2018-04-03 16-54-48](https://user-images.githubusercontent.com/38043915/38257176-11784a0a-3760-11e8-8ebf-f97b7885a78f.png)

![screenshot from 2018-04-03 16-55-10](https://user-images.githubusercontent.com/38043915/38257180-14cfdf38-3760-11e8-97b0-6e90dc6a982f.png)

The Broker is running on port 1883. The gateway.yml is correct here:

![tb-gateway-yml](https://user-images.githubusercontent.com/38043915/38257950-98030898-3761-11e8-9edf-1f987a85f67c.png)

And finally my mqtt json config file(which I had to download from [here](https://thingsboard.io/docs/iot-gateway/getting-started/#step-82-mqtt-broker-gui-configuration) because the default file is not accepted by the Thingsboard UI):

![mqtt-json-config](https://user-images.githubusercontent.com/38043915/38258358-8cd04f52-3762-11e8-966c-3bf403944c79.png)

My Gateway always displays 'Not sync':

![gateway](https://user-images.githubusercontent.com/38043915/38258699-7204c292-3763-11e8-82b6-50587ae0708d.png)

What am I doing wrong here?

**Comment by mp-loki** [comment]
Hi @BeIllegalBeagle !
Can you please tell us which version of ThingsBoard Gateway are you using?
The GUI configuration is only available from version 1.4, but the gateway.yml you provided seems to be from v.1.2

**Comment by mp-loki** [comment]
Any updates on this issue? otherwise I will close it

**Comment by BeIllegalBeagle** [comment]
Hello again! Sorry I'm unable to check which version I had but my issue was the fact that I had not referenced the access token in my gateway on thingsboard, after I did that it was ok and I could see my data. Other wise I didn't have any other issue

**Comment by shrinivassridhar** [comment]
@BeIllegalBeagle hello ! i wanted to know weather the status got synced or not . As you said the default mqtt config.json file is not accepted by the thingsboard UI, but even when i upload the downloaded file the file gets uploaded but the status is still not in sync. Does anyone know how to resolve the issue ?

**Comment by mp-loki** [comment]
@shrinivassridhar I suggest you create another issue for your case. Please upload your tb-gateway.yaml, tb-gateway.log, and mqtt-config.json that you are using. Don't forget to put the device access token in tb-gateway.yml

**Comment by shrinivassridhar** [comment]
@mp-loki hello sir ! As u told, i verified all my files and even have added my access token to the gateway.yml, and still if i import my mqtt-config.json file the sync status gets unsynced. 

[mqtt-gui-extension-configuration.txt](https://github.com/thingsboard/thingsboard-gateway/files/2811846/mqtt-gui-extension-configuration.txt)


[thingsboardyml.txt](https://github.com/thingsboard/thingsboard-gateway/files/2812002/thingsboardyml.txt)

[gatewayyml.txt](https://github.com/thingsboard/thingsboard-gateway/files/2812006/gatewayyml.txt)
