### ISSUE TITLE
[HELP] “Msg body is empty: {}"  problem.

### ISSUE THREAD

**Issue by googlehim** [thingsboard/thingsboard-gateway#536]
**Describe the issue**
Create description about your issue, and your actions to solve it.
Assert latest telemetry view, almost every minute:	
2021-07-12 22:31:51  ruleEngineException	{"ruleNodeId":"501d2780-0301-11ea-9bfb-070356c2cb64","ruleChainId":"50133c70-0301-11ea-9bfb-070356c2cb64","ruleNodeName":"Save Timeseries","ruleChainName":"Root Rule Chain","message":"Msg body is empty: {}"}

wireshark capture show:
normal message
Topic: v1/gateway/telemetry
Message: {"Dehumidifier": [{"ts": 1626008341359, "values": {"ntc1": 432, "ntc2": 432}}]}

unnormal message
Topic: v1/gateway/telemetry
Message: {"Dehumidifier": [{"ts": 1626008342255, "values": {}}]}

**Configuration** (Attach your configuration file)
**Notate: Remove Access token from file if you wanna attach tb_gateway.yaml**
```
connectors:
-
    name: Modbus Serial Connector
    type: modbus
    configureation: modbus_serial.json
```

**Connector name (If you need help with some connector/converter):**
[e.g. MQTT Connector]
modbus_serial.json
```
"timerserials":[
    {
       "tag":"ntc1",
       "type":"16int",
       "functionCode":4,
       "objectsCount":1,
       "address":0
    },
    {
       "tag":"ntc2",
       "type":"16int",
       "functionCode":4,
       "objectsCount":1,
       "address":1
    }
]

```
**Error traceback (If it was raised):**
```
'deviceName'
Traceback (most recent call last):
  File "<input>", line 2, in <module>
KeyError: 'deviceName'
```

**Versions (please complete the following information):**
 - OS: Linux raspberrypi 5.10.17
 - Thingsboard IoT Gateway version 2.4.1
 - Python version[e.g. 3.7]

**Comment by zbeacon** [comment]
Hi @googlehim ,

Please try to use the latest version from the master branch, this issue should be solved there.
