### ISSUE TITLE
[BUG] Example mqtt.json config file is missing attributeRequests section

### ISSUE THREAD

**Issue by pbrkr** [thingsboard/thingsboard-gateway#543]
The example MQTT configuration in thingsboard_gateway/config/mqtt.json is missing the `attributeRequests` section required by the MQTT Connector.

**Comment by zbeacon** [comment]
Hi @pbrkr ,

Thank you for your interest in ThingsBoard IoT gateway.
`attributeRequest` section was presented in the configuration at the very beginning of the project development, at the moment it is renamed to `attributeUpdates`. But it was left in the code to keep the backward compatibility.

**Comment by pbrkr** [comment]
@zbeacon please re-open this issue.

The code in thingsboard_gateway/connectors/mqtt/mqtt_connector.py still requires `attributeRequests` to be present in the config. If it is not present, an error is printed (see call to `load_handlers()` on line 73, error logged on line 135 of current master). If this section is just kept for backwards compatibility then no error should be printed if the `attributeRequests` section is missing. Perhaps `load_handlers()` needs an optional flag?

**Comment by zbeacon** [comment]
I agree with you, we will remove the error logging in this case.

**Comment by samson0v** [comment]
Hi @pbrkr, fixed your issue, please, update your gateway to the latest version via the master branch.
