### ISSUE TITLE
Disconnected client, result code 1 [Thingsboard gateway-Python module]

### ISSUE THREAD

**Issue by santobedi** [thingsboard/thingsboard-gateway#575]
**Describe the issue**
![screenshot](https://user-images.githubusercontent.com/10918248/134342010-4ef19cf8-a81c-4e6a-89a7-318e3fdb0161.PNG)

Why is the client getting disconnected frequently? I can see a device being created in my Web UI (as per deviceNameJsonExpression and deviceTypeJsonExpression in my mqtt.json file) and the telemetry is being updated on this device. However, when I exit out of MobaXterm (the tool I'm using to access my microcomputer where thingboard gateway is installed), the telemetry is no longer updated. 

UPDATE: If I run  **sudo systemctl start thingsboard-gateway** , I've no problem at all. What does really happen when I run only **thingsboard-gateway** command as mentioned [here](https://thingsboard.io/docs/iot-gateway/install/pip-installation/)?

**Connector name (If you need help with some connector/converter):**
MQTT Connector

**Comment by samson0v** [comment]
Hi @santobedi, when you run only thingsboard-gateway, that's run gateway as a terminal app but not as a background task (as a service), for this reason, when you logged out from your server, the terminal close all "foreground" task.
For more understanding example: if you run the VIM/Nano/Emacs in your terminal and logged out, the text editor will close.
Thanks for your interest in ThingsBoard IoT Gateway!

**Comment by santobedi** [comment]
@samson0v  Thank you for the reply. My system is working properly now (after starting the gateway). However, I still wonder about the frequent 'Disconnected' debug msg (it happens after rerunning the gateway with python command and the 'thingsboard-gateway' command. Is it a normal behavior?

**Comment by samson0v** [comment]
@santobedi no, it is very strange behaviour.

**Comment by samson0v** [comment]
Hi @santobedi, did it help, can we close the issue?

**Comment by santobedi** [comment]
Hello @samson0v ,
I've not used Version 2.9 yet. I hope it will solve the issue. It's fine to close the issue. Thank you.
