### ISSUE TITLE
SyntaxError: invalid syntax :  ERROR - [tb_loader.py] - tb_loader - 72 - invalid syntax (mqtt_connector.py, line 371)

### ISSUE THREAD

**Issue by santobedi** [thingsboard/thingsboard-gateway#580]
**Describe the issue**
After installing and editing the configurations (tb_gateway.yaml and mqtt.json), I run **sudo python3 -c 'from thingsboard_gateway.gateway.tb_gateway_service import TBGatewayService; TBGatewayService("./tb_gateway.yaml")'** command to save the changes. However, I get the following ERROR: 
![Capture](https://user-images.githubusercontent.com/10918248/135039683-8d1dedb2-c396-4562-90a2-f09af1f26de0.PNG)

Is it a BUG? How can I solve it? 

**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Thingsboard IoT Gateway version [2.7]
 - Python version[e.g. 3.7]

**Comment by zbeacon** [comment]
Hi @santobedi ,

It looks like you used the python with version lower then 3.7, could you try to install Python 3.7 or above and try to run the gateway again?
