### ISSUE TITLE
Thingsboard IoT Gateway -- BACnet Connector [HELP]

### ISSUE THREAD

**Issue by moharash** [thingsboard/thingsboard-gateway#584]
**Describe the issue**
Hi, i am trying to connect Thingsboard gateway to a bacnet ip device. the gateway and the device are on the same switch with same network.

thingsboard iot gateway installed on Ubuntu and all required settings are there.

the IoT gateway already registered to the Thingsboard platform:
![image](https://user-images.githubusercontent.com/66445698/135253743-b068ea84-15a7-42db-8afa-d9b25fd28eb2.png)

**Configuration** (Attach your configuration file)
![image](https://user-images.githubusercontent.com/66445698/135254356-0ebe7612-65e5-45a1-b514-78cc24833cfc.png)

**Connector name (If you need help with some connector/converter):**
BACnet Connector

**Error traceback (If it was raised):**
![image](https://user-images.githubusercontent.com/66445698/135254442-cd79d406-fc93-4c6f-98f5-a215dea52462.png)

**Versions (please complete the following information):**
 - OS: buntu 18.04
 - Thingsboard IoT Gateway version 2.2.4
 - Python version 3.7

**Comment by moharash** [comment]
Got below from Connector log

![image](https://user-images.githubusercontent.com/66445698/135409484-7e4ea8fa-8cd0-45d0-9e8a-37063f35b78e.png)

**Comment by moharash** [comment]
service log

![image](https://user-images.githubusercontent.com/66445698/135412186-ff2293ef-dd1e-437b-aa98-9c27866752ef.png)

![image](https://user-images.githubusercontent.com/66445698/135412343-403ce266-52fe-4042-861a-c2c4d3a5cc09.png)

**Comment by zbeacon** [comment]
Hi @moharash ,

Thank you for your interest in ThingsBoard IoT gateway.

It looks like some misconfiguration, could you provide your configuration json file for BACnet connector?

**Comment by moharash** [comment]
Hi @zbeacon ,

thank you for your reply,

kindly find attached the bacnet.json file and a 2 screenshots from a BACnet explorer showing the device
[bacnet.txt](https://github.com/thingsboard/thingsboard-gateway/files/7260459/bacnet.txt)
s.
![image006](https://user-images.githubusercontent.com/66445698/135481301-4086aedb-b1ec-49ce-b607-be4c2df47938.jpg)
![image005](https://user-images.githubusercontent.com/66445698/135481326-0fe5a901-f4f5-4d73-9127-9343345a2e09.jpg)

**Comment by moharash** [comment]
Hi @zbeacon ,

what do u think?
