### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by kxiopl** [thingsboard/thingsboard-gateway#587]
**Describe the issue**

There is no provision for Flow control using GPIO in Modbus Serial connector. I think it is necessary to have this option. Is there a workaround ?

**Connector name : modbus_serial

**Versions (please complete the following information):**
-  Raspbian OS on RPI 3B+
 - Thingsboard IoT Gateway version [2.8]

**Comment by samson0v** [comment]
Hi @kxiopl, can you, please, provide more info about your problem and how to reproduce it. Because our investigation didn't find any problem with device connectivity (including tests with disconnected/connected/combine of to state device).

Thanks for your interest in ThingsBoard IoT Gateway.
