### ISSUE TITLE
[HELP] BACnet device not getting detected

### ISSUE THREAD

**Issue by knityanand** [thingsboard/thingsboard-gateway#606]
**Describe the issue**
Thingsboard IOT gateway does not seem to detect my bacnet devices. The logs do not show any error. But if I use any other IP address other than 127.0.0.1 in the address of the general section like 192.168.29.40, it throws an error.. Also, when I use 127.0.0.1, it does not detect the device and hence it is not added in my thingsboard server. In contrast, the modbus device is detected and created in the thingsboard server when I add it in my tb_gateway.yaml file.

I have validated that my bacnet device is working using YABE. Have attached screenshots of YABE showing the data. I think I am missing something in the config file. 

**Configuration** (Attach your configuration file)

[tb-gateway.txt](https://github.com/thingsboard/thingsboard-gateway/files/7421337/tb-gateway.txt)
[bacnet_json.txt](https://github.com/thingsboard/thingsboard-gateway/files/7421346/bacnet_json.txt)
[modbus_json.txt](https://github.com/thingsboard/thingsboard-gateway/files/7421448/modbus_json.txt)

**Connector name (If you need help with some connector/converter):**
[e.g. BACnet Connector]

**Error traceback (If it was raised):**
```
""2021-10-26 20:34:15" - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 76 - Gateway starting..."
""2021-10-26 20:34:15" - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 81 - ThingsBoard IoT gateway version: 2.8"
""2021-10-26 20:34:15" - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_subscribe_to_attribute - 178 - Subscribed to *|* with id 1 for device *"
""2021-10-26 20:34:15" - |INFO| - [tb_device_mqtt.py] - tb_device_mqtt - _on_connect - 138 - connection SUCCESS"
**""2021-10-26 20:34:16" - |INFO| - [tb_loader.py] - tb_loader - import_module - 66 - Import BACnetConnector from /usr/local/lib/python3.7/site-packages/thingsboard_gateway-2.8-py3.7.egg/thingsboard_gateway/connectors/bacnet."
/root/.local/lib/python3.7/site-packages/bacpypes/core.py:114: UserWarning: no signal handlers for child threads
  warnings.warn("no signal handlers for child threads")
""2021-10-26 20:34:16" - |INFO| - [tb_loader.py] - tb_loader - import_module - 66 - Import BACnetUplinkConverter from /usr/local/lib/python3.7/site-packages/thingsboard_gateway-2.8-py3.7.egg/thingsboard_gateway/connectors/bacnet."
""2021-10-26 20:34:16" - |INFO| - [tb_loader.py] - tb_loader - import_module - 66 - Import BACnetDownlinkConverter from /usr/local/lib/python3.7/site-packages/thingsboard_gateway-2.8-py3.7.egg/thingsboard_gateway/connectors/bacnet."**
""2021-10-26 20:34:16" - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 147 - Gateway started."
""2021-10-26 20:34:16" - |INFO| - [tb_gateway_service.py] - tb_gateway_service - _attributes_parse - 285 - Remote logging has being updated. Current logging level is: DEBUG "
""2021-10-26 20:34:18" - |INFO| - [tb_device_mqtt.py] - tb_device_mqtt - _on_connect - 138 - connection SUCCESS"
""2021-10-26 20:34:18" - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_subscribe_to_attribute - 178 - Subscribed to *|* with id 2 for device *"
""2021-10-26 20:34:19" - |INFO| - [tb_device_mqtt.py] - tb_device_mqtt - _on_connect - 138 - connection SUCCESS"
""2021-10-26 20:34:19" - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_subscribe_to_attribute - 178 - Subscribed to *|* with id 3 for device *"
""2021-10-26 20:34:20" - |INFO| - [tb_device_mqtt.py] - tb_device_mqtt - _on_connect - 138 - connection SUCCESS"
""2021-10-26 20:34:22" - |INFO| - [tb_device_mqtt.py] - tb_device_mqtt - _on_connect - 138 - connection SUCCESS"
""2021-10-26 20:34:22" - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_subscribe_to_attribute - 178 - Subscribed to *|* with id 4 for device *"
""2021-10-26 20:34:23" - |INFO| - [tb_device_mqtt.py] - tb_device_mqtt - _on_connect - 138 - connection SUCCESS"
""2021-10-26 20:34:24" - |INFO| - [tb_device_mqtt.py] - tb_device_mqtt - _on_connect - 138 - connection SUCCESS"
""2021-10-26 20:34:25" - |INFO| - [tb_device_mqtt.py] - tb_device_mqtt - _on_connect - 138 - connection SUCCESS"
""2021-10-26 20:34:25" - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_subscribe_to_attribute - 178 - Subscribed to *|* with id 5 for device *"
""2021-10-26 20:34:26" - |INFO| - [tb_device_mqtt.py] - tb_device_mqtt - _on_connect - 138 - connection SUCCESS"
""2021-10-26 20:34:26" - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_subscribe_to_attribute - 178 - Subscribed to *|* with id 6 for device *"
""2021-10-26 20:34:27" - |INFO| - [tb_device_mqtt.py] - tb_device_mqtt - _on_connect - 138 - connection SUCCESS"
""2021-10-26 20:34:28" - |INFO| - [tb_device_mqtt.py] - tb_device_mqtt - _on_connect - 138 - connection SUCCESS"
```

**Versions (please complete the following information):**
 - OS: Windows 10
 - Thingsboard IoT Gateway version [e.g. 2.2.4]
 - Python version[e.g. 3.7]

![image](https://user-images.githubusercontent.com/55359481/138957269-ff2e5c8c-4ab5-483a-b6d9-2ce9499a4264.png)
![image](https://user-images.githubusercontent.com/55359481/138957363-cd09138f-917a-4c27-8a18-5b44d7f0ceba.png)

**Comment by knityanand** [comment]
Tried that as well..  No difference.. You are right.. I tried shutting down the device and then tried the same. Still no difference...

There seems to be no response to the WhoIs request...

**Comment by zbeacon** [comment]
Is it a real device, or simulation? Could you try to collect packages dump using wireshark?

**Comment by knityanand** [comment]
This is a simulation using the bacserv from the bacnet protocol stack utilities... Will check using wireshark and also a real device and revert

**Comment by zbeacon** [comment]
That's strange, I have tested the BACnet connector with the same environment in the different environment and it worked. Please let us know about the results of your testing.

**Comment by knityanand** [comment]
Hi @zbeacon,
    For the simulated device I see the below when I run YABE and the device is discovered

![image](https://user-images.githubusercontent.com/55359481/139708928-c7039e1d-332e-47db-a785-06a3a6161fe6.png)

   And I see a very similar bacnet data when I run tb-gateway as well but the device does not show up in the thingsboard server.

![image](https://user-images.githubusercontent.com/55359481/139709168-3853160a-9c66-44c8-8c87-b82678174dc5.png)

   Have checked the firewall settings as well to see if anything is getting blocked. Could not find anything for tb-gateway or docker

**Comment by knityanand** [comment]
Who is packet info when data is sent from / to yabe

![image](https://user-images.githubusercontent.com/55359481/139710268-0b3e3c53-a5b3-4fd6-b6de-65038d4f8215.png)
![image](https://user-images.githubusercontent.com/55359481/139710330-98b52d8f-c61e-4595-affa-9c5cf45a770f.png)

Who is packet info when data is sent from / to tb-gateway
![image](https://user-images.githubusercontent.com/55359481/139710391-727f0093-db8d-438c-81e6-60c9747e2a04.png)


> That's strange, I have tested the BACnet connector with the same environment in the different environment and it worked. Please let us know about the results of your testing.

Could you please share how your sample bacnet.json files which you have used for connecting with bacserv

**Comment by WeiTangLau** [comment]
Hi,

try changing the "address" under the "general" section to 0.0.0.0
refers: https://github.com/thingsboard/thingsboard-gateway/issues/609

**Comment by knityanand** [comment]
> 
> 
> Hi,
> 
> try changing the "address" under the "general" section to 0.0.0.0 refers: #609

That's what I have currently.. no luck..

**Comment by knityanand** [comment]
> 
> 
> That's strange, I have tested the BACnet connector with the same environment in the different environment and it worked. Please let us know about the results of your testing.

Also, I have tested with real devices using both tb_gateway and Yabe.. I get similar data as a result of whoIs in both. But in Yabe, I see the devices while in thingsboard, I see none..

Am attaching the wireshark data for both scenarios.. and also the bacnet.json. In the devices section, the address is the router address

Looks like the data is coming back from the network but the gateway is not identifying the device and adding it to the thingsboard server. Dunno if there is something wrong in bacnet.json or some other issue

[bacnet_json.txt](https://github.com/thingsboard/thingsboard-gateway/files/7458468/bacnet_json.txt)
[Wireshark.zip](https://github.com/thingsboard/thingsboard-gateway/files/7458469/Wireshark.zip)
[tb_gateway.txt](https://github.com/thingsboard/thingsboard-gateway/files/7458488/tb_gateway.txt)

**Comment by WeiTangLau** [comment]
Have you tried changing the objectId as follows?
![image](https://user-images.githubusercontent.com/42403590/139803882-475b2dc8-8e40-438c-a13e-74ede236ec3f.png)

refer: https://thingsboard.io/docs/iot-gateway/config/bacnet/

![image](https://user-images.githubusercontent.com/42403590/139803959-9ed1f39e-0638-4034-a48e-ac2fd893edfc.png)

**Comment by knityanand** [comment]
> 
> 
> Have you tried changing the objectId as follows? ![image](https://user-images.githubusercontent.com/42403590/139803882-475b2dc8-8e40-438c-a13e-74ede236ec3f.png)
> 
> refer: https://thingsboard.io/docs/iot-gateway/config/bacnet/
> 
> ![image](https://user-images.githubusercontent.com/42403590/139803959-9ed1f39e-0638-4034-a48e-ac2fd893edfc.png)

Yes. previously, I did not have the below in the bacnet.json. Now have added that as well as mentioned below.. But still no luck..

      "attributeUpdates": [
        {
          "key": "brightness",
          "requestType": "writeProperty",
          "objectId": "analogOutput:1",
          "propertyId": "presentValue"
        }
      ],
      "serverSideRpc": [
        {
          "method": "set_state",
          "requestType": "writeProperty",
          "requestTimeout": 30,
          "objectId": "binaryOutput:1",
          "propertyId": "presentValue"
        },
        {
          "method": "get_state",
          "requestType": "readProperty",
          "requestTimeout": 30,
          "objectId": "binaryOutput:1",
          "propertyId": "presentValue"
        }
      ]
    }

**Comment by zbeacon** [comment]
Hi @knityanand ,

It is possible to discover devices in networks using the address for device *:* (GlobalBroadcast). Also you can provide an address like: 15:75, where 15 - network number and 75 - number of station (device). Also please try to use 192.168.4.255/24 for device address, where /24 is a mask for sub network.

**Comment by knityanand** [comment]
Hi @zbeacon 
   Tried with 192.168.4.255/24 as the address. Devices were not detected.
   
    Did not understand how to device : (GlobalBroadcast) and also 15:75. Both threw an error.

    Also, I was looking through the code and realized that I donot seen any logs for the below statement in code log.debug("Received IAm Response: %s", str(apdu)) while in wireshark, I see the IamResponse is recieved..

**Comment by knityanand** [comment]
Hi @zbeacon 

I tried with a fresh gateway installation using https://thingsboard.io/docs/iot-gateway/install/source-installation/

It started working when I reverted the device address to the specific IP of the device..

  "deviceName": "BACnet Device ${objectName}",
      "deviceType": "default",
      "address": "**192.168.0.134:47808",**
      "pollPeriod": 100,
      "attributes": [

Thanks a ton to all of you for patience and educating me all the way...

**Comment by zbeacon** [comment]
Hi @knityanand ,

Thank you for your interest, please let us know if you discover some issue or an ability for improvement.

**Comment by kamisettychandan** [comment]
> Hi @ZBeacon
> 
> I tried with a fresh gateway installation using https://thingsboard.io/docs/iot-gateway/install/source-installation/
> 
> It started working when I reverted the device address to the specific IP of the device..
> 
> "deviceName": "BACnet Device ${objectName}", "deviceType": "default", "address": "**192.168.0.134:47808",** "pollPeriod": 100, "attributes": [
> 
> Thanks a ton to all of you for patience and educating me all the way...



@knityanand 
I am facing same issue. can you tell how you taken device IP address. 
Kindly help me
/

**Comment by kamisettychandan** [comment]
> Hi @knityanand ,
> 
> Thank you for your interest, please let us know if you discover some issue or an ability for improvement.

Followed Steps:
----------------
1. Connected ThingsBoard Gateway in my Laptop (Windows 11)
2. Connected TB-Gateway to ThingsBoard IoT Platform
3. Device connected to TB-Gateway
4. Observing Room Control Simulator data in YABE
Facing Issue:
-------------
Room Control Simulator Data not observing in ThingsBoard Cloud Platform
In bacnet.json file:
 "general": {
    "objectName": "TB_gateway",
    "address": "0.0.0.0:47808",		
    "objectIdentifier": 599,
    "maxApduLengthAccepted": 1476,
    "segmentationSupported": "segmentedBoth",
    "vendorIdentifier": 15
  },

  "devices": [
    {
      "deviceName": "BACnet Device ${objectName}",
      "deviceType": "default",
      "address": "192.168.152.1:47808", #192.168.152.1 address is the Local Machine IP Address
      "pollPeriod": 100,
      "attributes": [

I am facing issue from last 3 days.  Kindly help me.

**Comment by nkambhamettu** [comment]
@kamisettychandan 

In the below section the address should not be for the IP address of the local machine where gateway is installed. It should be the IP address of the panel to which devices are connected. This should be the same as the IP address you will see in YABE in the tree menu after discovery

"devices": [
{
"deviceName": "BACnet Device ${objectName}",
"deviceType": "default",
"address": "192.168.152.1:47808", https://github.com/thingsboard/thingsboard-gateway/pull/192.168.152.1 address is the Local Machine IP Address
"pollPeriod": 100,
"attributes": [

**Comment by kamisettychandan** [comment]
> @kamisettychandan
> 
> In the below section the address should not be for the IP address of the local machine where gateway is installed. It should be the IP address of the panel to which devices are connected. This should be the same as the IP address you will see in YABE in the tree menu after discovery
> 
> "devices": [ { "deviceName": "BACnet Device ${objectName}", "deviceType": "default", "address": "192.168.152.1:47808", https://github.com/[/pull/192](https://github.com/thingsboard/thingsboard-gateway/pull/192).168.152.1 address is the Local Machine IP Address "pollPeriod": 100, "attributes": [

@nkambhamettu,
I am not understanding for sentence "It should be the IP address of the panel to which devices are connected".
How to find that. Kindly guide me... I wants to send "Room control Simulator" data to Things Board Cloud Platform.
Kindly educate me which IP address I have to update in Device section.


{
  "general": {
    "objectName": "TB_gateway",
    "address": "0.0.0.0:47808",		
    "objectIdentifier": 599,
    "maxApduLengthAccepted": 1476,
    "segmentationSupported": "segmentedBoth",
    "vendorIdentifier": 15
  },
  "devices": [
    {
      "deviceName": "BACnet Device ${objectName}",
      "deviceType": "default",
      "address": "<IP Address>:47808",    # Kindly educate me, which IP address have to update
      "pollPeriod": 100,


![Yabe](https://github.com/thingsboard/thingsboard-gateway/assets/58870266/d51b7419-feea-4011-bd28-680129db24b4)

**Comment by knityanand** [comment]
Hi @kamisettychandan 

Your Device 3 (room Controller Simulator)  IP address should be used here w
"devices": [
{
"deviceName": "BACnet Device ${objectName}",
"deviceType": "default",
"address": "192.168.146.1:62865", 
"pollPeriod": 100,

**Comment by kamisettychandan** [comment]
Hi @knityanand 

I tried like that, but no luck. Simulator not connected to Things Board Platform

Successful steps:
-----------------
1. TB-Gateway created in ThingsBoard Platform
2. TB-Gateway installed in Laptop using Docker (using Access Token)
3. Device (for receiving Simulator data) configured in ThingsBoard Platform
4. Device connected to TB-Gateway (updated "provisionDeviceKey & provisionDeviceSecret") 
5. From Device Connectivity (on HTTP), observing dummy data
6. Observed Simulator data in YABE

Unsuccessful steps:
---------------------
1. Simulator data not reached to ThingsBoard Platform

I am attaching snaps below.
Kindly refer & guide me....

Snap 1: Simulator data in YABE
---------------------------------
![Simulator_YABE](https://github.com/thingsboard/thingsboard-gateway/assets/58870266/e272aea8-f0d4-4d29-b8e5-348bb1394f00)

Snap 2: Device & Gateway Connection
------------------------------------------
![device_gateway_connectivity](https://github.com/thingsboard/thingsboard-gateway/assets/58870266/c3b0145d-9c04-4b4c-9575-2150acf65ca4)

Snap 3: Device Connectivity
------------------------------
![device_connectivity](https://github.com/thingsboard/thingsboard-gateway/assets/58870266/1f9d7d65-c2b9-40f2-86e9-132ce69cd21f)

Configuration Files:
---------------------
[bacnet.json.txt](https://github.com/thingsboard/thingsboard-gateway/files/12924969/bacnet.json.txt)
[tb_gateway.json.txt](https://github.com/thingsboard/thingsboard-gateway/files/12924971/tb_gateway.json.txt)

I am not understanding, where I did mistake. Kindly refer guide me...

**Comment by kamisettychandan** [comment]
@knityanand,
Kindly help me...!
As per Docker Logs, BACnet connector not detecting 'Room Control Simulator' device. Could you help me...
[Day 4 Docker_Logs.txt](https://github.com/thingsboard/thingsboard-gateway/files/14523163/Day.4.Docke
[bacnet.json.txt](https://github.com/thingsboard/thingsboard-gateway/files/14523193/bacnet.json.txt)
[tb-gateway.txt](https://github.com/thingsboard/thingsboard-gateway/files/14523194/tb-gateway.txt)
r_Logs.txt)

**Comment by knityanand** [comment]
@kamisettychandan  Sorry for the delayed reply...  Hope you were able to solve this.. If not, can you share the screenshot for yabe with the parameter you are trying to get...

It seems to be an issue with your bacnet.txt
