### ISSUE TITLE
How many lines can be configured in a Modbus file?

### ISSUE THREAD

**Issue by RenCisco** [thingsboard/thingsboard-gateway#625]
**Describe the issue**

issue :1, my modbus file have over 2888 lines, this time is not any   telemeasuring data in the thingsboard.
               so,How many lines can be configured in a Modbus file?
          2,How do I view the tb_gateway version information?
          3, What version of Python does tb_gateway use?

here is config file
[modbusConf (1).txt](https://github.com/thingsboard/thingsboard-gateway/files/7509110/modbusConf.1.txt)

**Versions (please complete the following information):**
 - OS: [e.g. centos7]
 - Thingsboard IoT Gateway version [e.g. 2.2.4] commintu
 - Python version[e.g. 3.7]

**Comment by samson0v** [comment]
Hi @RenCisco, 

1. If you are using an asynchronous Modbus server you can divide your config file into several files. 
     For example: 
     <img width="322" alt="зображення" src="https://user-images.githubusercontent.com/43861229/141076175-51c17634-a32c-41b6-b03c-daac09990fad.png">

2. You can see it when Gateway starts in logs
3. Gateway uses the python version from 3.7
