### ISSUE TITLE
Does tb_Gateway support IEC104?

### ISSUE THREAD

**Issue by RenCisco** [thingsboard/thingsboard-gateway#629]
issue:1.how many lines are supported by single Modbus configuration file ? Instead of configuring multiple Modbus files
         2.Does Gateway support IEC104?

**Versions (please complete the following information):**
 - OS: [e.g. centos7]
 - Thingsboard IoT Gateway version [e.g. 2.2.4]
 - Python version[e.g. 3.7]

**Comment by samson0v** [comment]
Hi @RenCisco,
1. What logs does Gateway output? 
2. Gateway doesn't support the IEC 104 protocol.

**Comment by RenCisco** [comment]
@samson0v

gateway logs are "2021-11-12 16:35:31" - ERROR - [modbus_connector.py] - modbus_connector - 185 - Connection lost! Reconnecting..."

issue:1.How do I obtain hexadecimal Modbus packets?

**Comment by samson0v** [comment]
Hi @RenCisco, you can't send bytes to TB, we are using UTF-8 format, but you can parse the data in RuleChain.
