### ISSUE TITLE
[HELP] Add new RPC method

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard-gateway#631]
Hi,
We have different RPC methods from the RPC methods found on the thingsboard-gateway. How can we add new RPC methods?
We followed the steps below to add a new method, but we were unsuccessful.

1. We stopped the service.
2. We have made changes to the attached file below.
[tb_gateway_service.txt](https://github.com/thingsboard/thingsboard-gateway/files/7537749/tb_gateway_service.txt)

3. We started the service.
After these steps, we observed that the service was not working.

**Configuration**
[tb_gateway.txt](https://github.com/thingsboard/thingsboard-gateway/files/7538323/tb_gateway.txt)

**Connector name**
MQTT Connector

**Versions:**
OS: Raspbian GNU/Linux 10 (buster)
Thingsboard IoT Gateway version [e.g. 2.2.4]
Python version 3.7.3

Best Regards,
Gohm Team

**Comment by samson0v** [comment]
Hi @gohm-tech, yes, you can do it in that way. In the future, we will add a default tool for adding RPCs.
Please, send the gateway logs and errors that you took.
Thanks for your interest in ThingsBoard IoT Gateway.

**Comment by gohm-tech** [comment]
Hi, @samson0v 
Thanks for your helping.
Best Regards,
**Gohm Team**
