### ISSUE TITLE
[HELP] Redirect the gateway attribute update request to a different process.

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard-gateway#632]
Hi,
We have another process that works with C code. When an attribute of the gateway changes in the TB dashboard, we want to transfer this change to this C code.

1. How can we redirect attribute requests. Or How can we achieve this change in another process?
2. How can we undo this change if the gateway is not working at that time?
3. How can we convey to TBCore that we have accessed and changed parameters from other processes?

**Configuration** 
[tb_gateway.txt](https://github.com/thingsboard/thingsboard-gateway/files/7538318/tb_gateway.txt)

Connector name
 - MQTT Connector
 
**Versions:**
 - OS: Raspbian GNU/Linux 10 (buster)
 - Thingsboard IoT Gateway version [e.g. 2.2.4]
 - Python version 3.7.3

Best Regards,
Gohm Team

**Comment by samson0v** [comment]
Hi @gohm-tech, there is two way to solve your problem:
1. You can write your [custom connector](https://thingsboard.io/docs/iot-gateway/custom/)
2. You can use our [Python SDK](https://github.com/thingsboard/thingsboard-python-client-sdk)

Thanks for your interest in ThignsBoard IoT Gateway.

**Comment by gohm-tech** [comment]
Hi, thanks for your quick reply,

I think we didn't explain our situation well.
If I create a custom connector, won't we only handle the parameter update request for the device? But I want to handle the incoming requests for the gateway.

Best Regards,
Gohm Team

**Comment by samson0v** [comment]
Hi @gohm-tech, if you want to process parameter update request for the gateway you have to write your custom method in the tb_gateway_service file.
