### ISSUE TITLE
[BUG] Timeout fields added in server side rpc do not reach thingsboard-gateway

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard-gateway#634]
Hi,
I need to get the timeout field when two-way RPC is received to thingsboard-gateway.

In the screenshot below, there is a two-way RPC request that I sent with the help of a swagger-ui.
![Screenshot from 2021-11-18 13-20-50](https://user-images.githubusercontent.com/91528436/142398887-078bae0b-443b-484b-9e86-eb29c398540f.png)

I have a screenshot of listening to the RPC request with HTTP Get.
![Screenshot from 2021-11-18 13-26-58](https://user-images.githubusercontent.com/91528436/142399567-7288f764-ebf3-4d86-a76d-78ebe786e002.png)

There is a screenshot showing RPC request logs.
![Screenshot from 2021-11-18 13-21-48](https://user-images.githubusercontent.com/91528436/142399923-de5ffa77-ad90-4eaf-a699-1da432b1147f.png)

**Configuration**
[tb_gateway_service.txt](https://github.com/thingsboard/thingsboard-gateway/files/7562035/tb_gateway_service.txt)

**Connector name**
MQTT Connector

**Versions:**
OS: Raspbian GNU/Linux 10 (buster)
Thingsboard IoT Gateway version [e.g. 2.7]
Python version 3.7.3

Best Regards,
**Gohm Team**

**Comment by zbeacon** [comment]
Hi @gohm-tech ,

Thank you for your interest in ThingsBoard IoT gateway.
Unfortunately, it is not possible to get this value from incoming request on the gateway, because timeout field and persistent flag are not send to devices from ThingsBoard. You can just put timeout as a parameter into params and use them on the devices side.

**Comment by gohm-tech** [comment]
Hi @zbeacon 
Thanks for your quick reply,

When I examined the code, I noticed the lines in the picture below. 
![Screenshot from 2021-11-18 14-25-11](https://user-images.githubusercontent.com/91528436/142407227-3fffc532-74ae-4d37-aaa9-570767462d75.png)

Here, the "timeout" variable in the content variable is added to the arguments variable. This arguments variable contains the "params" field in the RPC request body we sent. This arguments variable is added as an argument to the RPC method function. If I was going to add the timeout value into the "params" variable, I think there was no need to write such an if state. Could this be a bug on the server-side? What is the reason for adding this if-statement?

Best Regards,
**Gohm Team**

**Comment by zbeacon** [comment]
Hmm, let me check this point.

**Comment by zbeacon** [comment]
Unfortunately there is no timeout field in RPC request message, this if was redundant.

**Comment by gohm-tech** [comment]
Hi,

@zbeacon Thank you for your interest.

Best Regards,
**Gohm Team**
