### ISSUE TITLE
[HELP] No Data from OPC-UA connector with TB-gateway 2.9

### ISSUE THREAD

**Issue by hangusto** [thingsboard/thingsboard-gateway#637]
Hello everyone,

I tried to connect the tb-gateway to Thingsboard and OPC-UA server (Kepware) by opcua connector.

![image](https://user-images.githubusercontent.com/45854355/143206930-62877b80-d78c-4907-92e9-0e9a5e52e298.png)
![image](https://user-images.githubusercontent.com/45854355/143208745-289b882b-7975-413a-a71c-91f96f264f6e.png)

### But it cannot get the data from OPC-UA server to Thingsboard.

![image](https://user-images.githubusercontent.com/45854355/143210496-9aa57444-1aee-4b0e-95f6-5b30e572032f.png)

I followed the the configuration setting and it was work on **tb-gateway version 2.6**

Here is my _opcua.json_ which is the same on **tb-gateway version 2.9**:
```
{
  "server": {
    "name": "OPC-UA Default Server",
    "url": "opc.tcp://host.docker.internal:49320",
    "timeoutInMillis": 5000,
    "scanPeriodInMillis": 5000,
    "disableSubscriptions": false,
    "subCheckPeriodInMillis": 100,
    "showMap": false,
    "security": "Basic256Sha256",
    "identity": {
      "type": "anonymous"
    },
    "mapping": [
      {
        "deviceNodePattern": "${Root\\.Objects\\.Simulator\\.Device1}",
        "deviceNamePattern": "G-sensor",
        "attributes": [
        ],
        "timeseries": [
          {
            "key": "G-sensor-x",
            "path": "${G-sensor-x}"
          },
          {
            "key": "G-sensor-y",
            "path": "${G-sensor-y}"
          },
	  {
	    "key": "G-sensor-z",
	    "path": "${G-sensor-z}"
	  }
        ]
      }
    ]
  }
}
```
Does anyone know what are the differences from the versions of gateway?
I want to figure out it. 
Thx.

**Versions:**
 - OS: Windows docker 
 - Thingsboard IoT Gateway version: 2.9
 - Python version: 3.7

**Comment by samson0v** [comment]
Hi @hangusto, alternative you can use the next:
```
{
     "key": "G-sensor-x",
     "path": "${ns=2;i=5}"
},
```
I think you can find ns and i arguments in KEPServerEX 6 node info panel.

Thanks for your interest in ThingsBoard IoT Gateway.

**Comment by samson0v** [comment]
Hi @hangusto, did it help, can we close the issue?

**Comment by hangusto** [comment]
@samson0v Thx, it is work.
