### ISSUE TITLE
[HELP] thingsboard_gateway is continuously subscribe with a new id

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard-gateway#643]
**Describe the issue**
Hi,
When the thingsboard_gateway service was running, We execute the mqtt_firmware_client.py. After that we are getting this log. So we are wondering this status will create any problem for us?
![Screenshot from 2021-12-02 14-08-51](https://user-images.githubusercontent.com/91528436/144411570-737daefa-125b-4682-8cb5-bf7d7e4fb270.png)

**Server Environment**
own setup
docker deployment
OS: Linux(Ubuntu 20.04)

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

**Connector name**
MQTT Connector

**Configuration**
[mqtt_firmware_client.txt](https://github.com/thingsboard/thingsboard-gateway/files/7641374/mqtt_firmware_client.txt)

**Versions:**
OS: Raspbian GNU/Linux 10 (buster)
Thingsboard IoT Gateway version [e.g. 2.7]
Python version 3.7.3

Best Regards,
**Gohm Team**

**Comment by zbeacon** [comment]
Hi @gohm-tech ,

Thank you for you interest in ThingsBoard IoT gateway.
This situation can appears when you used the same credentials for the both clients, ThingsBoard doesn't allow connection for two or more clients with the same credentials.
You can change the configuration of your ThingsBoard instance (parameter ACTORS_MAX_CONCURRENT_SESSION_PER_DEVICE)
Or use another device credentials for firmware client.

**Comment by gohm-tech** [comment]
Hi @zbeacon,
Thank you for your quick reply, After your suggestion, we found this question about this subject
[https://github.com/thingsboard/thingsboard/issues/1210](url)
We indicate the location of the file to help other users.
`thingsboard/application/src/main/resources`

Best Regards,
**Gohm Team**
