### ISSUE TITLE
Rest connector with different http headers

### ISSUE THREAD

**Issue by klonhj2015** [thingsboard/thingsboard-gateway#650]
**Describe the bug**
When we use rest connector, the http request only supports the header of application/json. Because the connector converts request to json first, then it will return code 415.

**Connector name (If bug in the some connector):**
[REST Connector]

**Versions (please complete the following information):**
 - OS: [macos]
 - Thingsboard IoT Gateway version [master]
 - Python version[3.9]

**Comment by samson0v** [comment]
Hi @klonhj2015, REST connector works only with JSON data. If you want to use Gateway with other data formats you can write your [custom converter](https://thingsboard.io/docs/iot-gateway/custom/).
