### ISSUE TITLE
What is the specific meaning of "deviceNodePattern" and "deviceNamePattern" in the tutorial?

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard-gateway#66]
Now, I'm going to connect tb-gateway with a third-party opc ua server (milo), and I don't know how to match the fields here?

https://thingsboard.io/docs/iot-gateway/getting-started/

**Step 9.4. Explore data from devices**
`**{
  "deviceNodePattern": "Channel1\\.Device\\d+$",

  "deviceNamePattern": "Device ${_System._DeviceId}",

  "attributes": [
    {"key":"Tag1", "type": "string", "value": "${Tag1}"}
                      ],
  "timeseries": [
    {"key":"Tag2", "type": "long", "value": "${Tag2}"}
  ]
}`**

**Comment by mp-loki** [comment]
deviceNodePattern is a regex to map on the device path. In the example case it will map Channel1.Device1, Channel1.Device2, etc.
 deviceNamePattern is an expression which will be used as a Device Name in ThingsBoard. In the example case it will take "Device " string, than will retrieve _System._DeviceId value (which is usually a number) and in ThingsBoard you will have devices like "Device 1", "Device 2" etc. You can change the expression to take any other that you need
