### ISSUE TITLE
[BUG] Do we have to send sensor connection requests from the gateway to connect between different gateway and sensor connected to another gateway?

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard-gateway#662]
We are working on RPC capabilities.
- Firstly the sensor sent sensor data via MQTT connector using /sensor_data topic. (The sensor has never used connectRequests.)
- We can see this sensor data on the Thingsboard dashboard.
-  We send a rpc_two_way from swagger. 
- Incoming RPC for the sensor received to the MQTT connector. (There is no problem so far.)
- The same sensor sent the sensor data from a different gateway without sending connecRequests before that.
- We send a rpc_two_way from swagger for the same sensor.
- Incoming RPC for the sensor received from the first gateway

How The second gateway can receive this incoming RPC?

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

**Connector name**
MQTT Connector

**Configuration**
[mqtt.txt](https://github.com/thingsboard/thingsboard-gateway/files/7769356/mqtt.txt)

**Versions:**
OS: Raspbian GNU/Linux 10 (buster)
Thingsboard IoT Gateway version [e.g. 2.7]
Python version 3.7.3

Best Regards,
**Gohm Team**

**Comment by gohm-tech** [comment]
Hi @zbeacon,

We think we don't need to send connectRequests.
![Screenshot from 2021-12-23 16-47-33](https://user-images.githubusercontent.com/91528436/147249756-e2d334b8-485f-4aa0-987f-92663aae3267.png)

Best Regards,
**Gohm Team**

**Comment by zbeacon** [comment]
Hi @gohm-tech ,

Actually the gateway sends connect request on the very first message with telemetry/attributes from device. Connect request in your case is not required, it was developed for case when you want to create the device and process it on ThingsBoard, but the data will be sent later.
In order to solve the issue with RPC we have to change the logic in ThingsBoard. Because at the moment ThingsBoard sends RPC to the gateway, that created the device, not to the latest connected gateway.

**Comment by zbeacon** [comment]
In order to send RPC to another gateway - Please try to send disconnect request to old gateway and connect to the new one, then device session will be assigned to the new gateway.

**Comment by gohm-tech** [comment]
Hi @zbeacon, 
Thanks for your interest. If the first gateway is not working and The device connects to the second gateway, We can not send a disconnect request from the first gateway. So How can we do that from another device (computer or server) as if sending the first gateway disconnect message? Any work on this issue? When will you solve this issue?
Best Regards,
**Gohm Team**

**Comment by gohm-tech** [comment]
Hi @zbeacon,

Is there any progress to solve this problem?

Best Regards,
**Gohm Team**

**Comment by imbeacon** [comment]
Hi,

At the moment, the issue was solved on ThingsBoard level, it contains inside information about last connected gateway and sends RPC to it.
