### ISSUE TITLE
Thingsboard Gateway not connecting to Bacnet

### ISSUE THREAD

**Issue by gmgiddikar1** [thingsboard/thingsboard-gateway#668]
Thingsboard IOT gateway does not seem to detect bacnet device. The logs do not show any error. But if I use any other IP address other than 127.0.0.1/0.0.0.0 in the address of the general section like 192.168.1.221, it throws an error.. Also, when I use 127.0.0.1 or 0.0.0.0, it does not detect the device and hence it is not added in my thingsboard server. 
In contrast, the modbus device is detected and created in the thingsboard server when I add it in my tb_gateway.yaml file.

We have installed docker on windows 10 and configured the gateway.       
 
![WhatsApp Image 2021-12-16 at 5 01 27 PM](https://user-images.githubusercontent.com/23236550/147740938-a0dfa6aa-a49d-4302-be93-655c4c49e8ac.jpeg)
![WhatsApp Image 2021-12-16 at 5 07 04 PM](https://user-images.githubusercontent.com/23236550/147740965-bd6ee5ed-b0d2-4208-8127-f2c9ad0a466d.jpeg)
![WhatsApp Image 2021-12-16 at 5 08 25 PM](https://user-images.githubusercontent.com/23236550/147740967-73741cc6-fdd4-4cb9-a9c4-9ba1f9fdd2bc.jpeg)

**Comment by samson0v** [comment]
Hi @gmgiddikar1, thanks for your interest in ThingsBoard IoT Gateway. 
I think that it is problem with the misconfiguration of your docker network. 
I guess so too that if to use the [IP address of docker container](https://www.freecodecamp.org/news/how-to-get-a-docker-container-ip-address-explained-with-examples/) as a server address, it has to work.
Or it can be a problem through port forwarding.

**Comment by gmgiddikar1** [comment]
Hi Vitalii, thanks for comment. We have tried using server address as a IP address of docker container. Please explain why you think its a problem through port forwarding.  AS I already mentioned that Yabe detects the network and device and able to read the object id present values.

**Comment by samson0v** [comment]
Hi @gmgiddikar1, so you have to follow the next instruction:
1. BACnet Connector have to be `"address": "0.0.0.0:47809",`, for example:
    <img width="356" alt="зображення" src="https://user-images.githubusercontent.com/43861229/182332991-43b9c901-cc76-4ea2-990c-d5b9d607088b.png">
2. Device IP address has to be the inner private IP (`192.168.1.198/24`), in my case:
    <img width="218" alt="зображення" src="https://user-images.githubusercontent.com/43861229/182333544-83fbfcce-7b84-4f8c-a37e-3035ced5fcb9.png">
    and device configuration:
    <img width="403" alt="зображення" src="https://user-images.githubusercontent.com/43861229/182333682-8f6c58f1-41e7-458b-b5de-6cc27b730270.png">
3. Run your device
4. Run Gateway via the docker container
5. Voila!
    <img width="930" alt="зображення" src="https://user-images.githubusercontent.com/43861229/182333917-08addb77-a268-41ba-95f8-a8a96a932683.png">
