### ISSUE TITLE
[BUG] High CPU usage because of while loop in mqtt_firmware_client.py

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard-gateway#670]
Hi,
We are using the [mqtt_firmware_client.py](https://thingsboard.io/docs/user-guide/resources/firmware/mqtt_firmware_client.py) code for the [OTA updates](https://thingsboard.io/docs/user-guide/ota-updates/?remoteintegrationdockerinstall=mqtt). But when we used this code, we realized that our device was using a high CPU. Afterward, we investigated this and changed the code as follows.

[mqtt_firmware_client.txt](https://github.com/thingsboard/thingsboard-gateway/files/7795587/mqtt_firmware_client.txt)

![Screenshot from 2021-12-31 10-27-04](https://user-images.githubusercontent.com/91528436/147809839-cba4ce52-cad0-49b3-aa86-396afc4789a5.png)
![Screenshot from 2021-12-31 10-28-49](https://user-images.githubusercontent.com/91528436/147809871-0eed4646-91e2-458c-ae51-6d572c96ea7f.png)

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

**Connector name**
MQTT Connector

**Versions:**
OS: Raspbian GNU/Linux 10 (buster)
Thingsboard IoT Gateway version [e.g. 2.7]
Python version 3.7.3

Best Regards,
**Gohm Team**

**Comment by samson0v** [comment]
Hi @gohm-tech, this bug doesn't relate to Gateway. Create an issue in [thingsboard-python-client-sdk
](https://github.com/thingsboard/thingsboard-python-client-sdk).

**Comment by samson0v** [comment]
@gohm-tech This bug was fixed via the [commit](https://github.com/thingsboard/thingsboard-python-client-sdk/commit/f13e8d2f6e123c91238c701bccf16328e01879e2). The file from documentation will change to a new version soon.
Thanks for your interest in ThingsBoard.
