### ISSUE TITLE
[FEATURE] OPC-UA connector should use SourceTimestamp

### ISSUE THREAD

**Issue by wilterdinkrobert** [thingsboard/thingsboard-gateway#702]
In the OPC-UA protocol a source timestamp is available to record/reflect when a variable was sampled by the server, see SourceTimestamp in https://reference.opcfoundation.org/v104/Core/docs/Part4/7.7.3/. This timestamp should be used for recording the data in thingsboard, because:
* The SourceTimestamp accurately reflects when the value was created. Any data transfer or processing time delays will not affect the measument.
* Multiple synchronized value updates (e.g. in case of a complex control loop) will be recorded with the same timestamp in thingsboard.

The opcua_uplink_converter could be adjusted in the following manner:
```python
full_key = information["key"]
full_value = information["path"].replace("${"+path+"}", str(val))
if information_type == 'timeseries' and data is not None and (
        data.monitored_item.Value.SourceTimestamp is not None or data.monitored_item.Value.ServerTimestamp is not None):
    # Note: SourceTimestamp and ServerTimestamp may be naive datetime objects, hence for the timestamp() the tz must first be overwritten to UTC (which it is according to the spec)
    timestamp = None
    if data.monitored_item.Value.SourceTimestamp is not None:
        timestamp = int(data.monitored_item.Value.SourceTimestamp.replace(tzinfo=timezone.utc).timestamp()*1000)
    if timestamp is None and data.monitored_item.Value.ServerTimestamp is not None:
        timestamp = int(data.monitored_item.Value.ServerTimestamp.replace(tzinfo=timezone.utc).timestamp()*1000)
    if timestamp is None:
        timestamp = int(time()*1000)
    result[information_types[information_type]].append(
        {"ts": timestamp, 'values': {full_key: full_value}})
else:
    result[information_types[information_type]].append({full_key: full_value})
```

If you want I can also prepare a Pull-request.

**Comment by zbeacon** [comment]
Hi @wilterdinkrobert ,

Thank you for participating in the project life. It will be nice, if you prepare a PR.
