### ISSUE TITLE
Question about file type and SQLite type storage

### ISSUE THREAD

**Issue by ndrs-cwt** [thingsboard/thingsboard-gateway#715]
Hi all

I have a question about choosing a storage type. Back then we have memory and file storage. The file type will keep data when power off and the memory type won't.

But now we have a new storage type, SQLite type, so I have some questions about it.
- What is the advantage of SQLite type over file type such as speed, memory usage, storage space usage, wear level of storage(HDD, SD card, EEPROM), or something else. or some simple Pro-Con comparison.
- Any recommended use case when to use SQLite type or file type storage.

Best regard
Chaiwat

**Comment by samson0v** [comment]
Hi @ndrs-cwt, 
SQLite pros:
1. In many common cases, loading content from an SQLite database is faster than loading content out of individual files. See Internal Versus External BLOBs for additional information.
2. The content can be viewed using third-party tools.
3. The application file is portable across all operating systems, 32-bit and 64-bit and big- and little-endian architectures
4. It is easiest to read data (debug)
5. If you want to have some separate analytics of data 

Thanks for your interest in ThingsBoard IoT Gateway!
