### ISSUE TITLE
maven compile error

### ISSUE THREAD

**Issue by jacklicn** [thingsboard/thingsboard-gateway#74]
[ERROR] thingsboard-gateway-1.4.0.1\src\main\java\org\
thingsboard\gateway\service\MqttMessageSender.java:[131,21] Error: Cannot find symbol
[ERROR]  Symbol: Method isConnected()
[ERROR]   Location: Type is MqttClient Variables tbClient
----------------------------------------------------------------------------
Is this project used https://github.com/jk-5/netty-mqtt
? but the interface MqttClient does not have the method isConnected，how to fix it.

**Comment by jacklicn** [comment]
use https://github.com/thingsboard/netty-mqtt

**Comment by Tanushree1989** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project data: Compilation failure: Compilation failure: 
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/device/profile/AlarmCondition.java:[29,18] cannot find symbol
[ERROR]   symbol:   class AlarmConditionFilter
[ERROR]   location: class org.thingsboard.server.common.data.device.profile.AlarmCondition
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/device/profile/AlarmCondition.java:[29,40] cannot find symbol
[ERROR]   symbol:   class AlarmConditionFilter
[ERROR]   location: class org.thingsboard.server.common.data.device.profile.AlarmCondition
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/device/profile/AlarmCondition.java:[25,1] cannot find symbol
[ERROR]   symbol:   class AlarmConditionFilter
[ERROR]   location: class org.thingsboard.server.common.data.device.profile.AlarmCondition
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/query/RelationsQueryFilter.java:[21,51] cannot find symbol
[ERROR]   symbol:   class RelationEntityTypeFilter
[ERROR]   location: package org.thingsboard.server.common.data.relation
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/query/RelationsQueryFilter.java:[35,18] cannot find symbol
[ERROR]   symbol:   class RelationEntityTypeFilter
[ERROR]   location: class org.thingsboard.server.common.data.query.RelationsQueryFilter
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/query/RelationsQueryFilter.java:[35,44] cannot find symbol
[ERROR]   symbol:   class RelationEntityTypeFilter
[ERROR]   location: class org.thingsboard.server.common.data.query.RelationsQueryFilter
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/query/RelationsQueryFilter.java:[25,1] cannot find symbol
[ERROR]   symbol:   class RelationEntityTypeFilter
[ERROR]   location: class org.thingsboard.server.common.data.query.RelationsQueryFilter
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/entityview/EntityViewSearchQuery.java:[22,51] cannot find symbol
[ERROR]   symbol:   class RelationEntityTypeFilter
[ERROR]   location: package org.thingsboard.server.common.data.relation
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/relation/EntityRelationsQuery.java:[29,18] cannot find symbol
[ERROR]   symbol:   class RelationEntityTypeFilter
[ERROR]   location: class org.thingsboard.server.common.data.relation.EntityRelationsQuery
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/relation/EntityRelationsQuery.java:[29,44] cannot find symbol
[ERROR]   symbol:   class RelationEntityTypeFilter
[ERROR]   location: class org.thingsboard.server.common.data.relation.EntityRelationsQuery
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/relation/EntityRelationsQuery.java:[25,1] cannot find symbol
[ERROR]   symbol:   class RelationEntityTypeFilter
[ERROR]   location: class org.thingsboard.server.common.data.relation.EntityRelationsQuery
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/asset/AssetSearchQuery.java:[22,51] cannot find symbol
[ERROR]   symbol:   class RelationEntityTypeFilter
[ERROR]   location: package org.thingsboard.server.common.data.relation
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/device/DeviceSearchQuery.java:[22,51] cannot find symbol
[ERROR]   symbol:   class RelationEntityTypeFilter
[ERROR]   location: package org.thingsboard.server.common.data.relation
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/widget/WidgetType.java:[23,33] cannot find symbol
[ERROR]   symbol: class BaseWidgetType
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/widget/WidgetType.java:[35,23] cannot find symbol
[ERROR]   symbol:   class BaseWidgetType
[ERROR]   location: class org.thingsboard.server.common.data.widget.WidgetType
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/device/profile/DeviceProfileTransportConfiguration.java:[34,37] cannot find symbol
[ERROR]   symbol: class CoapDeviceProfileTransportConfiguration
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/device/data/DeviceTransportConfiguration.java:[33,36] cannot find symbol
[ERROR]   symbol: class CoapDeviceTransportConfiguration
[ERROR] /var/jenkins_home/workspace/thingsboard/common/data/src/main/java/org/thingsboard/server/common/data/query/EntityFilter.java:[32,36] cannot find symbol
[ERROR]   symbol: class EntityTypeFilter
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :data
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE

I am getting this error. The code doesn't have any problem. It builds successfully on local.
I have Jenkins installed on google kubernetes cluster. I selected autometic installation option from global tool configuration to installed java, node and maven that requires to build the project. But for git i provided the path /usr/bin/git which I am not sure is the correct one

java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
+ git --version
git version 2.20.1
+ mvn -version
Apache Maven 3.8.1

OS name: "linux", version: "5.4.89+", arch: "amd64", family: "unix"

Kindly assist.
