### ISSUE TITLE
Where is the configuration specification for the modbus extension?

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard-gateway#76]

**Comment by mp-loki** [comment]
Modbus extension was graciously contributed by @dyosick. We were not able to come up with any documentation yet.

**Comment by dyosick** [comment]
[Documentation](https://github.com/thingsboard/thingsboard.github.io/pull/99) is waiting to be merged.
But you can set up it locally. [Here is how](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/).

**Comment by mp-loki** [comment]
Thank you, @dyosick. Documentation merged. Sorry we missed it out before.

**Comment by edme10** [comment]
You got success, I can not connect my modbus TCP devices....

**Comment by edme10** [comment]
???
