### ISSUE TITLE
[HELP] New Docker image request

### ISSUE THREAD

**Issue by l33tkrew** [thingsboard/thingsboard-gateway#780]
**Describe the issue**
Are you planning to publish a new tb_gateway docker image on DockerHub. When I check the docker hub profile, I see a label "Updated 2 months ago". 

I am asking this because I do not get any error when I install tb_gateway from the latest GitHub repository. But when I used the docker image, I got both MQTT and rest connectors errors

**Comment by samson0v** [comment]
Hi @l33tkrew, we will improve the docker image via the next release.
