### ISSUE TITLE
not generating log files  [HELP]

### ISSUE THREAD

**Issue by akashagre** [thingsboard/thingsboard-gateway#785]
![Screenshot (34)](https://user-images.githubusercontent.com/80543140/159902515-94a88b57-262e-4ea9-ae74-4443f111fbd7.png)

Thingsboard gateway not generating log file

**Comment by samson0v** [comment]
Hi @akashagre, it will be unable to save and see the logs because of the STREAM ONLY mode of your virtual machine.
Please, use the docker image if you are using Windows.

**Comment by imbeacon** [comment]
Hi @akashagre ,

The possible reasons for this issue are:
1. logs folder didn't created, if you installed the gatesway as a service please check folder /var/log/thingsboard-gateway - is it exists? If you installed the gateway from the sources - please create logs folder in the thingsboard-gateway folder.
2. Some issue with permissions - the gateway in case of working like a service uses user thingsboard_gateway to write logs - please check are permissions for writing logs allowed to user thingsboard_user for logs folder.
