### ISSUE TITLE
[HELP] MQTT-SN Gateway

### ISSUE THREAD

**Issue by martin9115** [thingsboard/thingsboard-gateway#791]
Hi, can we install MQTT-SN Gateway on ThingsBoard cloud ?

**Comment by samson0v** [comment]
Hi @martin9115, I think you do not correctly understand what is Gateway and how it is used.
Read the next docs for better understanding:
https://thingsboard.io/docs/iot-gateway/what-is-iot-gateway/
https://thingsboard.io/docs/iot-gateway/getting-started/
https://thingsboard.io/docs/iot-gateway/config/mqtt/

Thanks for your interest in ThingsBoard IoT Gateway!
