### ISSUE TITLE
[HELP] - can't etablish RPC communication  to the opcua server. 

### ISSUE THREAD

**Issue by Andhuooo** [thingsboard/thingsboard-gateway#793]
![image](https://user-images.githubusercontent.com/99332219/160836099-53b601f7-2189-41cc-b2c2-277130b88065.png)
Hi all, can any one please clarify about which variable need to add to the  opcua server code and opcua .json fie in the iot gateway according to  the RPC switch in the TB

**Comment by Andhuooo** [comment]
![image](https://user-images.githubusercontent.com/99332219/160837764-01dd1013-a10b-4d84-969e-072e7e17eaf9.png)

**Comment by samson0v** [comment]
Hi @Andhuooo, in OPC-UA Connector there is the default RPC command (get and set), so every telemetry and attribute parameter in your config file has the get and set RPC method.
For example:
I have the next attribute and telemetry:
<img width="260" alt="зображення" src="https://user-images.githubusercontent.com/43861229/164696034-e446b1e9-c975-4fb5-91f1-29fc6c821332.png">
These two parameters have get and set RPC methods out of the box, so you don't need to configure it manually.
RPC command for getting attribute:
<img width="227" alt="зображення" src="https://user-images.githubusercontent.com/43861229/164697464-877b3069-2a0a-443b-ad62-5e8f0d34a9a7.png">
RPC command for getting telemetry:
<img width="228" alt="зображення" src="https://user-images.githubusercontent.com/43861229/164697766-84d8f7a6-9292-4aa7-ac98-898d2313f871.png">

Additionally, we will update OPC-UA Connector documentation.
Thanks for your interest in ThingsBoard IoT Gateway!

**Comment by AIOTEL-sanjanaa** [comment]
Is the documentation updated regarding this?

**Comment by Da1Liu** [comment]
@samson0v  sry but u would like to know whether can i use "set" command there, i've tried but faild, it told me that "{"set":"Node didn't find!","code":500}" , and i have changed my command like →set "ns=2;s=/Channel/Par
ameter/R" 1, etc. All of them not helpful, wish for your help thx.
