### ISSUE TITLE
[BUG]The telemetry data obtained by thingsboard gateway is misplaced

### ISSUE THREAD

**Issue by bggmjxh** [thingsboard/thingsboard-gateway#794]
I asked a question in thingsboard, but I tested it. I think it's still the reason for thingsboard gateway, so I link the question here.
Please take a look.
[https://github.com/thingsboard/thingsboard/issues/6346#issue-1187666031](url)

**Comment by bggmjxh** [comment]
[#https://github.com/thingsboard/thingsboard/issues/6346#issue-1187666031](url)

**Comment by samson0v** [comment]
Hi @bggmjxh, we will investigate this bug.
Thanks for your interest in ThingsBoard IoT Gateway!

**Comment by samson0v** [comment]
@bggmjxh, there were some bug fixes, please, update your Gateway via the master branch and let us know if it helps.
