### ISSUE TITLE
[HELP] Send data to another iot platform 

### ISSUE THREAD

**Issue by pickedbrian** [thingsboard/thingsboard-gateway#807]
**Describe the issue**

Is it possible that i have use the          thingsboard-gateway to resolve device's massage and send the result to another IOT platform without the ThingsBoard platform.

There have a platform just need device's telemetry data. don't need to control devices or do other things.

How can i push json data to this platform use thingsboard-gateway only. The platform support mqtt.

**Comment by samson0v** [comment]
Hi @pickedbrian, it is not possible to use Gateway without ThingsBoard.
Thanks for your interest in ThingsBoard IoT Gateway!
