### ISSUE TITLE
[BUG] 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by farmerkz** [thingsboard/thingsboard-gateway#818]
**Describe the bug**
In the system log, when using the snmp connector, for each snmp transaction such an entry appears:
`May  4 21:24:56 tb-gateway python3[19013]: ""2022-05-04 21:24:56" - |ERROR| - [tb_gateway_service.py] - tb_gateway_service - __send_to_storage - 654 - 'str' object has no attribute 'get'"`
But at the same time, thingsboard receives telemetry

**Connector name (If bug in the some connector):**
SNMP Connector

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Thingsboard IoT Gateway version v.3.3.4
 - Python version 3.8.10

**Comment by samson0v** [comment]
Hi @farmerkz, we will investigate your problem and let you know about the results.
Thanks for your interest in ThingsBoard IoT Gateway!

**Comment by ilseva** [comment]
Hi,
same problem on MQTT Connector
```
[tb_gateway_service.py] - tb_gateway_service - __send_to_storage - 573 - 'str' object has no attribute 'get'"
```
In our case, Thingsboard does not receive data.

It seems related to the in memory storage configuration.
Thanks for support

**Comment by islomkhon** [comment]
it seems you are parsing the data on the wrong way! which tb_gateway_service function do you use to send the data to the storage in the connector?

**Comment by ilseva** [comment]
hi @islomkhon,
we dont' use any tb_gateway_service function. we implement a custom converter (for MQTT) and simply create an object like the one on the documentation
```json
{
    "deviceName": "DEVICE_NAME",
    "deviceType": "DEVICE_TYPE",
    "attributes": [
                    {"SOME_ATTRIBUTE_KEY":"SOME_ATTRIBUTE_VALUE"},
                    {"SOME_ATTRIBUTE_KEY1":"SOME_ATTRIBUTE_VALUE1"}
                  ],
    "telemetry": [
                    {"SOME_TELEMETRY_KEY": "SOME_TELEMETRY_VALUE"},
                    {"SOME_TELEMETRY_KEY1": "SOME_TELEMETRY_VALUE1"},
                    {"SOME_TELEMETRY_KEY2": "SOME_TELEMETRY_VALUE2"}
                  ]
}
```
we noted that if we add the timestamp on telemetries the error disappear.
thanks

**Comment by samson0v** [comment]
Hi @ilseva, data with a timestamp and without have different structures!

**Comment by samson0v** [comment]
Hi @farmerkz, we will investigate the problem with SNMP Connector!
Thanks for your interest in ThingsBoard IoT Gateway!

**Comment by ilseva** [comment]
Thank @samson0v for your reply.
I know that the structure with timestamp is different... and trust me, and I read all the documentation regarding custom converter.

**Comment by zmj-upupup** [comment]
> Thank @samson0v for your reply. I know that the structure with timestamp is different... and trust me, and I read all the documentation regarding custom converter.

@ilseva hi, Did you solve this problem in the end? I have the same problem

**Comment by ilseva** [comment]
hello @zmj-upupup!
Regarding the error `'str' object has no attribute 'get'"`
We fix the error in this way
- creating a new object on the `convert` method of our custom converter
```python
 def convert(self, topic, body):
        try:
            dict_result = {}
            ....
            ....
            return dict_result;
        except Exception as e:
            log.exception('Error in converter message: \n%s\n', body)
            log.exception(e)

```
- adding the timestamp on the dict created on
```python
telemetry = {"ts": int(time() * 1000), "values": {key: body}}
dict_result["telemetry"].append(telemetry)
```
