### ISSUE TITLE
[BUG] version `GLIBC_2.29' not found 

### ISSUE THREAD

**Issue by dh-jy** [thingsboard/thingsboard-gateway#827]
**Describe the bug**
i installed thingsboard-gateway 3.0.1.post0 . when i run the gateway, I have the problem in the picture below

![image](https://user-images.githubusercontent.com/103489619/168274673-5ad7aa53-43af-46d4-bd2e-7c063b170815.png)

**Versions (please complete the following information):**
 - OS: [e.g. raspberrypi]
 - Thingsboard IoT Gateway version [e.g. 3.0.1.post0]
 - Python version[e.g. 3.7]

**Comment by samson0v** [comment]
Hi @dh-jy, you have to install GRPCIO
`sudo pip3 install grpcio`
Thanks for your interest in ThingsBoard IoT Gateway!

**Comment by dh-jy** [comment]
Hi，i have installed it, but the error is still
 ![image](https://user-images.githubusercontent.com/103489619/168276031-23c8c291-ec99-410f-85d1-50774fe9db13.png)

**Comment by dh-jy** [comment]
It seems that the latest version has this problem。Version 2.9 doesn't seem to have this problem

**Comment by samson0v** [comment]
Hi @dh-jy, any updates? Can we close the issue?

**Comment by samson0v** [comment]
Hi @dh-jy, can we close the issue? or issue is still actual for you?
