### ISSUE TITLE
[HELP]How to cancel remote-logging

### ISSUE THREAD

**Issue by Lanruo555** [thingsboard/thingsboard-gateway#836]
**Describe the issue**
I did this feature https://thingsboard.io/docs/iot-gateway/guides/how-to-enable-remote-logging/ in my project but now I find this operation makes all logs saved to the database with too high memory and I want to cancel this feature , so how can I do it.
Thank you for your reply.

**Connector name (If you need help with some connector/converter):**
MQTT Connector

**Versions (please complete the following information):**
- OS: [ Raspberry Pi ]
- Thingsboard IoT Gateway version [3.0.1]
- Python version[3.9.2]
![image](https://user-images.githubusercontent.com/103398913/170664714-895d375e-62fa-4284-bd45-c13061602281.png)

**Comment by imbeacon** [comment]
Hi @plm55555 ,

The simplest way to disable remote logging is to remove "RemoteLoggingLevel" attribute from the gateway.
Or change it to higher level? like ERROR, the you will receive only error messages.

**Comment by plm55555** [comment]
>Thanks for your reply.  When I delete “RemoteLoggingLevel” this property, although the logging will not be saved to the database again ,but I can't check it in Raspberry Pi again. Before I add this attribute, I can view the DEBUG-level attributes in the Raspberry Pi in the logs file, which is exactly what I need. So how should I do it？
![image](https://user-images.githubusercontent.com/103398913/170901798-21701cd8-864b-45b0-bb6d-f569f72120b4.png)
@imbeacon

**Comment by imbeacon** [comment]
Hi @Lanruo555 ,

Actually after removing this parameter you can restart the gateway and configuration will be taken from logs.conf file in your config folder, as before adding this parameter.

**Comment by samson0v** [comment]
Hi @Lanruo555, any updates? Can we close the issue?
