### ISSUE TITLE
commanding custom mathematic tb-extension

### ISSUE THREAD

**Issue by quirosaur** [thingsboard/thingsboard-gateway#84]
Hi!

I'm in need of calculation properties, and so i plan to create tb-gateway extension, which takes data in, calculates value based on it, and if it is in treshold range sends it forward. This acts as a kind of advanced filter (it possibly alerts if treshold is exceeded).

So, question:

i know tb and gateway use mqtt beetween them to transfer settings and data, so i was wondering if i could use for example mqtt from widget to control treshold limits of the extension

the aim is to reduce strain of server, since there will be lot of useless raw data needed only to monitor if tresholds get exceeded

**Comment by mp-loki** [comment]
You need to
1) implement your gateway extension
2) in GUI, implement extension configuration screen, where you can set the threshold limits
