### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by emrekardaslar** [thingsboard/thingsboard-gateway#842]
**Question About Logs**
Do logs get cleared after a while, is there a mechanism to limit the size of logs or clear them?

Thank you

**Comment by Produmize** [comment]
> **Question About Logs** Do logs get cleared after a while, is there a mechanism to limit the size of logs or clear them?
> 
> Thank you

In /etc/thingsboard-gateway/config/logs.conf you can change these parameters.

**Comment by emrekardaslar** [comment]
Thanks !
