### ISSUE TITLE
[BUG] Gateway Cannot Publish Data For All Devices

### ISSUE THREAD

**Issue by emrekardaslar** [thingsboard/thingsboard-gateway#853]
**Describe the bug**
* Gateway cannot publish every data, some of the devices on the platform cannot recieve new data. Does changing storage type effect the data persistence? What type of storage should I use? I decided to use file storage since it is recommended for persistence. What are your recommendations?

**Connector name**
mqtt connector

**Versions (please complete the following information):**
 - OS: Ubuntu Server 2020.04
 - Thingsboard IoT Gateway version 2.0
 - Python version 3.7

**Comment by samson0v** [comment]
Hi @emrekardaslar, can you, please, send your MQTT config file, data that send to Gateway and logs.

**Comment by samson0v** [comment]
Hi @emrekardaslar, any updates?

**Comment by samson0v** [comment]
Hi @emrekardaslar, try to change to True  `Overwrite activity time for connected device` for the Gateway device.
<img width="928" alt="зображення" src="https://user-images.githubusercontent.com/43861229/176851751-b98bfb75-f1e0-4032-94a6-6a5052ed87db.png">

**Comment by samson0v** [comment]
Hi @emrekardaslar, any updates?

**Comment by emrekardaslar** [comment]
* Unfortunately no. The OS may cause the issue but I'm not sure. If I can figure it out, I will update you.

**Comment by samson0v** [comment]
Hi @emrekardaslar, please, update your Gateway to the newest version via the master branch. It seems that the #877 issue relates to yours and it was fixed.
