### ISSUE TITLE
[HELP] tb-gateway How should Bluetooth data be parsed

### ISSUE THREAD

**Issue by dingbihuii** [thingsboard/thingsboard-gateway#855]
this is my ble.json:
![image](https://user-images.githubusercontent.com/74649974/174779747-f8331513-9229-4948-8e23-b8546d4bd4d0.png)
this is my log:
![image](https://user-images.githubusercontent.com/74649974/174780044-d0b6266a-67e5-4a25-b2e6-34f440d378bd.png)
Why is b'\x01\x00' resolved to '01234567891011121314'?

**Comment by samson0v** [comment]
Hi @dingbihuii, any updates, can we close the issue?
