### ISSUE TITLE
[HELP] Require help for ODBC configuration

### ISSUE THREAD

**Issue by shauser1** [thingsboard/thingsboard-gateway#863]
**Describe the issue**
I am configuring ODBC connector in thingsboard application. 

-> Created mariadb instance and installed pyodbc. 
-> Completed a python program to insert and retrieve the data from table
-> Configured the connection string and query details to odbc.json
-> Mapped the access token in tb_gateway.yaml 

Issue -> Not able to pass data to thingsboard UI from thingsboard gateway.  I am not finding any clue to find the root cause. Need suggestions or help to fix this issue.

**Configuration** (Attach your configuration file)
**Notate: Remove Access token from file if you want to attach a tb_gateway.yaml**

**Connector name (If you need help with some connector/converter):**
[e.g. MQTT Connector]

**Error traceback (If it was raised):**
```
'deviceName'
Traceback (most recent call last):
  File "<input>", line 2, in <module>
KeyError: 'deviceName'
```

**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Thingsboard IoT Gateway version [e.g. 3.0.1]
 - Python version[e.g. 3.9]

**Comment by shauser1** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/thingsboard_gateway-3.1-py3.9.egg/thingsboard_gateway/tb_utility/tb_utility.py", line 141, in install_package
    result = check_call([executable, "-m", "pip", "install", package, "--upgrade", "--user"])
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'pip', 'install', 'pyodbc', '--upgrade', '--user']' returned non-zero exit status 1.

**Comment by samson0v** [comment]
Hi @shauser1, can you provide more logs (but firstly replace all INFO to DEBUG level in logs.conf file).
Thanks for your interest in ThingsBoard IoT Gateway!

**Comment by shauser1** [comment]
[
[logs.txt](https://github.com/thingsboard/thingsboard-gateway/files/9008796/logs.txt)
attached the full logs for reference](url)

**Comment by shauser1** [comment]
> 

I am not able to locate logs.conf file in my ubuntu machine.

**Comment by samson0v** [comment]
@shauser1, this file has to be in the folder where is your connector config file.

**Comment by samson0v** [comment]
Hi @shauser1, any updates?

**Comment by shauser1** [comment]
@samson0v  Hi, We followed your mentioned steps and resolved the issue. We were able to pass the data from TB gateway to thingsboard. Thanks a lot for your timely help.
