### ISSUE TITLE
[BUG] Invalid syntax while installing gateway 3.1.1 on raspberry pi.

### ISSUE THREAD

**Issue by DejonckheereWard** [thingsboard/thingsboard-gateway#865]
**Describe the bug**
I get a syntax error while installing the latest package on a raspberry pi, caused by an incompatible bit of code in the script.

**Connector name (If bug in the some connector):**
OPC-UA Asyncio Connector

**Error traceback (If available):**
```
Setting up python3-thingsboard-gateway (3.1-1) ...
  File "/usr/lib/python3/dist-packages/thingsboard_gateway/connectors/opcua_asyncio/device.py", line 23
    if child := re.search(r"(ns=\d*;[isgb]=.*\d)", node_config['path']):
              ^
SyntaxError: invalid syntax

dpkg: error processing package python3-thingsboard-gateway (--configure):
 installed python3-thingsboard-gateway package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 python3-thingsboard-gateway

```

**Versions (please complete the following information):**
 - OS: Raspbian buster 10
 - Thingsboard IoT Gateway version: 3.1.1
 - Python version: 3.7.3

I traced the issue back to the use of ":=" in the python script, which is supported in Python3.8+.
The latest available python3 package for raspbian/debian by default is 3.7.3, as shown by apt.
```
pi@RevPi:~ $ sudo apt install python3
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3 is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
```

**Comment by samson0v** [comment]
Hi @DejonckheereWard, we will fix this synaxis in the nearest future.
Thanks for your interest in ThingsBoard IoT Gateway!

**Comment by DejonckheereWard** [comment]
> 

Hi, thank you for the quick response,
I tried manually updating and building python 3.8, which should support it, but that way i noticed that the if expression used here: ``` if child := re.search(r"(ns=\d*;[isgb]=.*\d)", node_config['path']):``` should be wrapped with brackets for correct syntax in 3.8. -> ```if (child := re.search(r"(ns=\d*;[isgb]=.*\d)", node_config['path'])):```
This occurs both in line 23 & 25 of device.py
Thanks for the support
