### ISSUE TITLE
How to match key through expressions [HELP]

### ISSUE THREAD

**Issue by DaXian459** [thingsboard/thingsboard-gateway#878]
**For example:"PLC_1A_Q01_Automatic_Status_1"、"PLC_1A_Q01_Automatic_Status_2"、
"PLC_1A_Q02_Automatic_Status_1"。 I want them to match a variable name. Does the gateway support regular expressions**

**Comment by DaXian459** [comment]
I use mqtt connection, and I can't find the corresponding description in the document

**Comment by samson0v** [comment]
Hi @DaXian459, as you can see from the documentation, MQTT Connector can use these two parameters to parse the device name dynamically.
<img width="455" alt="зображення" src="https://user-images.githubusercontent.com/43861229/179235190-6ad665ef-e39e-4278-9793-38fc7289d6bc.png">
<img width="589" alt="зображення" src="https://user-images.githubusercontent.com/43861229/179235249-bab8ce3a-efc0-40ec-9a37-6a717ee01324.png">

**Comment by samson0v** [comment]
Hi @DaXian459, any updates? Can we close the issue?
