### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by dh-jy** [thingsboard/thingsboard-gateway#885]
hello , i used   "sudo pip3 install thingsboard-gateway"  to install the gateway, it can work. but i cannot find the log file. 
As shown below.
![image](https://user-images.githubusercontent.com/103489619/179963297-b6a2d429-6a36-48e0-87bb-d297b563b0a9.png)

could you give me help?

**Comment by samson0v** [comment]
Hi @dh-jy, follow this [guide](https://thingsboard.io/docs/iot-gateway/install/pip-installation/) to install ThingsBoard IoT Gateway via the pip package.

Thanks for your interest in ThingsBoard IoT Gateway!

**Comment by dh-jy** [comment]
yes, i followed it. but in the /var/log/thingsboard-gateway directory i cannot found any log files



发自我的iPhone


------------------ Original ------------------
From: Vitalii Bidochka ***@***.***&gt;
Date: Wed,Jul 20,2022 6:46 PM
To: thingsboard/thingsboard-gateway ***@***.***&gt;
Cc: dh-jy ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [thingsboard/thingsboard-gateway] [HELP] (Issue #885)





 
Hi @dh-jy, follow this guide to install ThingsBoard IoT Gateway via the pip package.
 
Thanks for your interest in ThingsBoard IoT Gateway!

**Comment by dh-jy** [comment]
thank you for your replay.
i follow the guide to install the gateway. and the gateway can run successfully. but i cannot find the log files in /var/log/thingsboard-gateway&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Vitalii Bidochka ***@***.***&gt;
Date: Wed,Jul 20,2022 6:46 PM
To: thingsboard/thingsboard-gateway ***@***.***&gt;
Cc: dh-jy ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [thingsboard/thingsboard-gateway] [HELP] (Issue #885)





 
Hi @dh-jy, follow this guide to install ThingsBoard IoT Gateway via the pip package.
 
Thanks for your interest in ThingsBoard IoT Gateway!

**Comment by dh-jy** [comment]
> @dh-jy, do you run the gateway on the virtual machine?
not , i run the gateway on the Raspberry Pi device

**Comment by dh-jy** [comment]
> I have had a similar issue on a gateway - try adding the path and then making sure that the permissions for that folder allow the gateway to write files there. (chmod will let you do this)

hello thank you for your reply, What is this path you are referring to? And How did you install the gateway apt or pip) ?

**Comment by samson0v** [comment]
Hi @dh-jy, use the next command:
`sudo chown YOUR_USER:YOUR_USER -R /var/log/thingsboard-gateway`
YOUR_USER - is a user who will run the gateway.

We will update the official documentation in the nearest future.

**Comment by samson0v** [comment]
Hi @dh-jy, any updates?

**Comment by samson0v** [comment]
@dh-jy, can we close the issue?

**Comment by dh-jy** [comment]
> Hi @dh-jy, any updates?

yes, i solve this problem
