### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by dh-jy** [thingsboard/thingsboard-gateway#893]
How to increase sample rate in modbus serial (rtu) mode?
as my attampts,change the pollPeriod to 1000ms，500ms， 200ms ，50ms ，the max telemetry recieve rate (i count them in a Timeseries table gadget) is 5 per second (and sometimes 4 or 3 or even 1). how can i increase it?
my configuration file  as the following:
![image](https://user-images.githubusercontent.com/103489619/182790505-5eeaca01-8f11-45f8-ae5f-da1e7f48337b.png)

**Versions (please complete the following information):**
 - OS: [e.g. Raspberry]
 - Thingsboard IoT Gateway version [e.g. 3.0.1]
 - Python version[e.g. 3.9]

**Comment by samson0v** [comment]
Hi @dh-jy, send, please, your logs

**Comment by dh-jy** [comment]
OK
![image](https://user-images.githubusercontent.com/103489619/182792623-42c55d67-33c3-4ea9-98f0-05dd4eb04f37.png)

**Comment by dh-jy** [comment]
No problem uploading data，It just can't achieve high frequency sampling。when i changed the pollPeriod （ Such as：100,50）in the modbus_new_1.json, it cannot imcrease sample.

**Comment by samson0v** [comment]
@dh-jy, it seems that 200ms is the maximum poll period for the now.

**Comment by samson0v** [comment]
@dh-jy, we will try to increase this value by performing certain optimizations.

**Comment by dh-jy** [comment]
OK thank you for your help. 
If you are using sensors to monitor certain devices, high-frequency sampling is important, which means less polling time

**Comment by samson0v** [comment]
@dh-jy, managed to get poll period = 60ms

**Comment by dh-jy** [comment]
To do this?
![image](https://user-images.githubusercontent.com/103489619/182830239-9a032493-5cf0-46bc-ac76-de1e296a5d94.png)

**Comment by dh-jy** [comment]
And i  found the code sleep(.2) also influence the poll time， if i set 0.2 to 2s the poll time  will become 2s.
![image](https://user-images.githubusercontent.com/103489619/182830704-1c8a57a7-298e-4e23-a64a-ce45a2165b70.png)

**Comment by samson0v** [comment]
> To do this? ![image](https://user-images.githubusercontent.com/103489619/182830239-9a032493-5cf0-46bc-ac76-de1e296a5d94.png)

yes

**Comment by dh-jy** [comment]
i have set,but it doesn't seem to work.
![image](https://user-images.githubusercontent.com/103489619/182837685-d6944cfd-8c15-49cd-870e-af0924d8f372.png)

**Comment by samson0v** [comment]
@dh-jy, you misunderstand me, I said that I made some optimization and manage to poll speed up to 60ms.

**Comment by dh-jy** [comment]
ok😂, my bad.could you show the code after optimization

发自我的iPhone


------------------ Original ------------------
From: Vitalii Bidochka ***@***.***&gt;
Date: Thu,Aug 4,2022 7:48 PM
To: thingsboard/thingsboard-gateway ***@***.***&gt;
Cc: dh-jy ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [thingsboard/thingsboard-gateway] [HELP] (Issue #893)





 
@dh-jy, you misunderstand me, I said that I made some optimization and manage to poll speed up to 60ms.

**Comment by samson0v** [comment]
@dh-jy made pull request above
