### ISSUE TITLE
[HELP] Identify the configuration files changes and auto update running connectors 

### ISSUE THREAD

**Issue by STYTY** [thingsboard/thingsboard-gateway#894]
**Describe the issue**
If I update the tb_gateway.yaml and the configuration files (*.json) from connectors (in /etc/thingsboard-gateway/config) remotely to gateway config folder, can tb gateway Identify file changes and auto update running connectors without using gateway rpc method like gateway_restart

**Configuration** 
![image](https://user-images.githubusercontent.com/41984479/182791364-3e64614d-b3e5-4b25-a4ad-ef6af172347a.png)

**Versions (please complete the following information):**
 - OS: centos7
 - Thingsboard IoT Gateway version 3.1
 - Python version 3.9

**Comment by samson0v** [comment]
Hi @STYTY, unfortunately no.

**Comment by STYTY** [comment]
@samson0v Thank you very much!
