### ISSUE TITLE
[HELP] thingsboard-iot-gateway doesn´t start...

### ISSUE THREAD

**Issue by rungg12** [thingsboard/thingsboard-gateway#912]
Hey!

I just made a fresh install of Thingsboard and of the Gateway. Thingsboard service is running without any problems, but the gateway just doesn´t want to start. 

I get following error: 
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

I almost tried everything on google, but always the same error.
I hope someone can help me

BTW, I am on Ubuntu, 20.04.

**Comment by devaskim** [comment]
What installation mode did you use for gateway?

**Comment by rungg12** [comment]
i used the guide on the website: https://thingsboard.io/docs/iot-gateway/install/deb-installation/

**Comment by devaskim** [comment]
Try to totally remove the package and then install again
```
sudo aptitude purge packagename
```

**Comment by samson0v** [comment]
Hi @rungg12, try to run:
`sudo pip3 install protobuf==3.20.0`

**Comment by rungg12** [comment]
@samson0v your tipp did it, @devaskim thank you too
