### ISSUE TITLE
[BUG] Incorrect log directory mapping in Docker container

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard-gateway#915]
**Describe the bug**
I deployed official Docker image of gateway, using [default log](https://github.com/thingsboard/thingsboard-gateway/blob/master/thingsboard_gateway/config/logs.conf) and [Docker Compose configurations](https://github.com/thingsboard/thingsboard-gateway/blob/master/docker/docker-compose.yml) with modified paths.

I expected to find logs in ./logs directory but there was nothing. With the help of *Remote shell* widget I found logs not in `/thingsboard_gateway/logs` directory but in `/logs`. Screenshots below
![shell](https://user-images.githubusercontent.com/86909129/189488500-8ee4f9b4-4828-4282-823c-a9bdf9039dd5.jpg)

![conf](https://user-images.githubusercontent.com/86909129/189488566-87c527b1-9131-4627-9f9c-b8bc3942d928.jpg)

**Versions (please complete the following information):**
 - Ubuntu 
 -  Docker
 - Thingsboard IoT Gateway version 3.1

**Comment by samson0v** [comment]
Hi @devaskim, ok, I will check it and let you know about results.
