### ISSUE TITLE
[HELP] MQTT - regexp in topic filter

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard-gateway#916]
Broker topic structure is:
```
SN1234/
    some_topic1/
    some_topic2/
    PV_description/
    KPI_description/
SN54321/
    some_topic1/
    some_topic2/
    PV_description/
    KPI_description/
```
How to subscribe both and **only** to *PV_description* and to *KPI_description*? Thanks

**Comment by samson0v** [comment]
Hi @devaskim, gateway can't handle regex in a topic so you can restructure topics, for example:
SN1234/
    some_topic1/
    some_topic2/
    PV/description/
    KPI/description/

And use the next `topicFilter`: SN1234/+/description. It will be more similar to the MQTT topic design.

**Comment by devaskim** [comment]
Thanks @samson0v

**Comment by samson0v** [comment]
@devaskim, got some updates for you, Gateway can handle regex in a topic. 
My bad.

**Comment by devaskim** [comment]
Great, could you provide some example?

**Comment by devaskim** [comment]
Great, @samson0v could you provide some example?

**Comment by samson0v** [comment]
Hi @devaskim, the MQTT client can't subscribe to topics that include some regex.
So you can't use them in configuration.
Sorry for the misinformation.

**Comment by samson0v** [comment]
@devaskim, can we close the issue?

**Comment by devaskim** [comment]
Yes, thanks.
Also waiting for response in other tickets ;)
