### ISSUE TITLE
[FEATURE] Make check for new gateway version optional

### ISSUE THREAD

**Issue by solred** [thingsboard/thingsboard-gateway#917]
Some customers do not have an internet connection.

Can we make the check for a new gateway version optional?
https://github.com/thingsboard/thingsboard-gateway/blob/master/thingsboard_gateway/tb_utility/tb_updater.py#L74

**Comment by samson0v** [comment]
Hi @solred, we will discuss your suggestion and let you know about the decision.

**Comment by samson0v** [comment]
Hi @solred, we decided to not change this check. If the user hasn't an internet connector it doesn't break anything.

**Comment by solred** [comment]
Understood, thank you for taking a look.
