### ISSUE TITLE
[FEATURE] Make dependencies static instead of dynamic

### ISSUE THREAD

**Issue by solred** [thingsboard/thingsboard-gateway#918]
Some customers do not have an internet connection.

Configuring e.g. the REST connector will install dependencies on the fly.
Although I understand the idea of doing this dynamically, shouldn't we make this static.
I guess the same goes for all other connector dependencies.

Workaround for the REST connector:
```
FROM thingsboard/tb-gateway:3.1 AS solidred-gateway
RUN python3 -mpip install requests aiohttp cryptography
```

**Comment by samson0v** [comment]
Hi @solred, we can't do it because we have a lot of connectors and their dependencies can take a lot of memory.

**Comment by solred** [comment]
Thanks, understood.
