### ISSUE TITLE
[FEATURE] Optimize docker image

### ISSUE THREAD

**Issue by solred** [thingsboard/thingsboard-gateway#919]
At this moment the docker image is now almost 900 MB.

Probably / possibly this can be optimized?

https://hub.docker.com/r/thingsboard/tb-gateway

```
REPOSITORY                                                          TAG            IMAGE ID       CREATED        SIZE
thingsboard/tb-gateway                                              latest         67d20b264edf   3 months ago   897MB
```

**Comment by samson0v** [comment]
Hi @solred, We already optimized the docker image and fixed the bug with correctly binding extensions.
<img width="918" alt="зображення" src="https://user-images.githubusercontent.com/43861229/190086677-b6013eee-d34a-483f-9b3c-9717cfbf6b04.png">
So you can build a docker image using Dockerfile from the master branch.

**Comment by solred** [comment]
Thanks, I will take a look at it.
