### ISSUE TITLE
Thingsboard backup

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard-gateway#93]
Hello,
I am using thngsboard 1.4.0, and i would like to create a backup about it. So I would like, the backup contain every rule, plugin, dashboard, customer, and device with telemetry data.
How can I do it?

**Comment by mp-loki** [comment]
I think all you need is to backup a database. 
Also, please post these kind of questions under a [relevant project](https://github.com/thingsboard/thingsboard/issues)
