### ISSUE TITLE
[HELP] Telemetry data is only updated every 2 to 3 hours since some devices broke

### ISSUE THREAD

**Issue by redasdasd** [thingsboard/thingsboard-gateway#932]
I have modbus configured in version 2.9. Everything was fine a few days ago. But several of the devices are broken and others are functioning normally. Updates of telemetry data became very slow. I set it to collect every 10 minutes. Telemetry data is only updated every 2 to 3 hours since some devices broke. The configuration of broken devices cannot be deleted in Modbus, as these devices will be repaired in the future. How should I get a working device back to 10 minute telemetry？I have to keep using version 2.9.
{
  "server": {
    "name": "Modbus1 Default Server",
    "type": "tcp",
    "host": "192.168.30.10",
    "port": 502,
    "timeout": 35,
    "methode": "socket",
    "byteOrder": "BIG",
    "retries": true,
    "retryOnEmpty": true,
    "retryOnInvalid": true,
    "devices": [
      {
        "unitId": 200,
        "deviceName": "Krackow_Smartlogger",
        "attributesPollPeriod": 86400000,
        "timeseriesPollPeriod": 600000,
        "sendDataOnlyOnChange": false,
        "connectAttemptTimeMs": 5000,
        "connectAttemptCount": 5,
        "waitAfterFailedAttemptsMs": 300000,
        "attributes": [
          {
            "tag": "Serial Nummer",
            "type": "string",
            "functionCode": 3,
            "objectsCount": 10,
            "address": 40713
          }
       ],
      "timeseries": [
          {
            "tag": "P_AC",
            "type": "32int",
            "functionCode": 3,
            "objectsCount": 2,
            "address": 40525,
            "divider": 1000
          },
          {
            "tag": "RPC_P_PERC",
            "type": "16uint",
            "functionCode": 3,
            "objectsCount": 1,
            "address": 40428,
            "divider": 10
          },
          {
            "tag": "CO2",
            "type": "32uint",
            "functionCode": 3,
            "objectsCount": 2,
            "address": 40523,
            "divider": 10000
          },
          {
            "tag": "Tenergy",
            "type": "32uint",
            "functionCode": 3,
            "objectsCount": 2,
            "address": 40562,
            "divider": 10
          },
          {
            "tag": "Zenergy",
            "type": "32uint",
            "functionCode": 3,
            "objectsCount": 2,
            "address": 40560,
            "divider": 10000
          }
        ],
        "attributeUpdates": [
 	{
            "tag": "All_WR_On",
            "type": "16uint",
            "functionCode": 16,
            "objectsCount": 1,
            "address": 40200
          },
          {
            "tag": "All_WR_Off",
            "type": "16uint",
            "functionCode": 16,
            "objectsCount": 1,
            "address": 40201
          }
        ],
        "rpc":[
        ]
      },
{
	"unitId": 1,
	"deviceName": "Krackow_36KTL(COM2-1)",
	"attributesPollPeriod": 86400000,
	"timeseriesPollPeriod": 600000,
	"sendDataOnlyOnChange": false,
	"attributes": [{
		"tag": "Serial Nummer",
		"type": "string",
		"functionCode": 3,
		"objectsCount": 10,
		"address": 32003
	}],
	"timeseries": [{
		"tag": "Wechselrichter_PV1",
		"type": "16int",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32262,
		"divider": 10
	}, {
		"tag": "Wechselrichter_Wirkleistung",
		"type": "32int",
		"functionCode": 3,
		"objectsCount": 2,
		"address": 32290,
		"divider": 1000
	}, {
		"tag": "Wechselrichter_Leistung",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32285,
		"divider": 100
	}, {
		"tag": "Wechselrichter_Status",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32287
	}]
}, {
	"unitId": 2,
	"deviceName": "Krackow_36KTL(COM2-2)",
	"attributesPollPeriod": 86400000,
	"timeseriesPollPeriod": 600000,
	"sendDataOnlyOnChange": false,
	"attributes": [{
		"tag": "Serial Nummer",
		"type": "string",
		"functionCode": 3,
		"objectsCount": 10,
		"address": 32003
	}],
	"timeseries": [{
		"tag": "Wechselrichter_PV1",
		"type": "16int",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32262,
		"divider": 10
	}, {
		"tag": "Wechselrichter_Wirkleistung",
		"type": "32int",
		"functionCode": 3,
		"objectsCount": 2,
		"address": 32290,
		"divider": 1000
	}, {
		"tag": "Wechselrichter_Leistung",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32285,
		"divider": 100
	}, {
		"tag": "Wechselrichter_Status",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32287
	}]
}, {
	"unitId": 3,
	"deviceName": "Krackow_36KTL(COM2-3)",
	"attributesPollPeriod": 86400000,
	"timeseriesPollPeriod": 600000,
	"sendDataOnlyOnChange": false,
	"attributes": [{
		"tag": "Serial Nummer",
		"type": "string",
		"functionCode": 3,
		"objectsCount": 10,
		"address": 32003
	}],
	"timeseries": [{
		"tag": "Wechselrichter_PV1",
		"type": "16int",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32262,
		"divider": 10
	}, {
		"tag": "Wechselrichter_Wirkleistung",
		"type": "32int",
		"functionCode": 3,
		"objectsCount": 2,
		"address": 32290,
		"divider": 1000
	}, {
		"tag": "Wechselrichter_Leistung",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32285,
		"divider": 100
	}, {
		"tag": "Wechselrichter_Status",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32287
	}]
}, {
	"unitId": 4,
	"deviceName": "Krackow_36KTL(COM2-4)",
	"attributesPollPeriod": 86400000,
	"timeseriesPollPeriod": 600000,
	"sendDataOnlyOnChange": false,
	"attributes": [{
		"tag": "Serial Nummer",
		"type": "string",
		"functionCode": 3,
		"objectsCount": 10,
		"address": 32003
	}],
	"timeseries": [{
		"tag": "Wechselrichter_PV1",
		"type": "16int",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32262,
		"divider": 10
	}, {
		"tag": "Wechselrichter_Wirkleistung",
		"type": "32int",
		"functionCode": 3,
		"objectsCount": 2,
		"address": 32290,
		"divider": 1000
	}, {
		"tag": "Wechselrichter_Leistung",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32285,
		"divider": 100
	}, {
		"tag": "Wechselrichter_Status",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32287
	}]
}, {
	"unitId": 5,
	"deviceName": "Krackow_36KTL(COM2-5)",
	"attributesPollPeriod": 86400000,
	"timeseriesPollPeriod": 600000,
	"sendDataOnlyOnChange": false,
	"attributes": [{
		"tag": "Serial Nummer",
		"type": "string",
		"functionCode": 3,
		"objectsCount": 10,
		"address": 32003
	}],
	"timeseries": [{
		"tag": "Wechselrichter_PV1",
		"type": "16int",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32262,
		"divider": 10
	}, {
		"tag": "Wechselrichter_Wirkleistung",
		"type": "32int",
		"functionCode": 3,
		"objectsCount": 2,
		"address": 32290,
		"divider": 1000
	}, {
		"tag": "Wechselrichter_Leistung",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32285,
		"divider": 100
	}, {
		"tag": "Wechselrichter_Status",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32287
	}]
}, {
	"unitId": 6,
	"deviceName": "Krackow_36KTL(COM2-6)",
	"attributesPollPeriod": 86400000,
	"timeseriesPollPeriod": 600000,
	"sendDataOnlyOnChange": false,
	"attributes": [{
		"tag": "Serial Nummer",
		"type": "string",
		"functionCode": 3,
		"objectsCount": 10,
		"address": 32003
	}],
	"timeseries": [{
		"tag": "Wechselrichter_PV1",
		"type": "16int",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32262,
		"divider": 10
	}, {
		"tag": "Wechselrichter_Wirkleistung",
		"type": "32int",
		"functionCode": 3,
		"objectsCount": 2,
		"address": 32290,
		"divider": 1000
	}, {
		"tag": "Wechselrichter_Leistung",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32285,
		"divider": 100
	}, {
		"tag": "Wechselrichter_Status",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32287
	}]
}, {
	"unitId": 7,
	"deviceName": "Krackow_36KTL(COM2-7)",
	"attributesPollPeriod": 86400000,
	"timeseriesPollPeriod": 600000,
	"sendDataOnlyOnChange": false,
	"attributes": [{
		"tag": "Serial Nummer",
		"type": "string",
		"functionCode": 3,
		"objectsCount": 10,
		"address": 32003
	}],
	"timeseries": [{
		"tag": "Wechselrichter_PV1",
		"type": "16int",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32262,
		"divider": 10
	}, {
		"tag": "Wechselrichter_Wirkleistung",
		"type": "32int",
		"functionCode": 3,
		"objectsCount": 2,
		"address": 32290,
		"divider": 1000
	}, {
		"tag": "Wechselrichter_Leistung",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32285,
		"divider": 100
	}, {
		"tag": "Wechselrichter_Status",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32287
	}]
}, {
	"unitId": 8,
	"deviceName": "Krackow_33KTL(COM2-8)",
	"attributesPollPeriod": 86400000,
	"timeseriesPollPeriod": 600000,
	"sendDataOnlyOnChange": false,
	"attributes": [{
		"tag": "Serial Nummer",
		"type": "string",
		"functionCode": 3,
		"objectsCount": 10,
		"address": 32003
	}],
	"timeseries": [{
		"tag": "Wechselrichter_PV1",
		"type": "16int",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32262,
		"divider": 10
	}, {
		"tag": "Wechselrichter_Wirkleistung",
		"type": "32int",
		"functionCode": 3,
		"objectsCount": 2,
		"address": 32290,
		"divider": 1000
	}, {
		"tag": "Wechselrichter_Leistung",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32285,
		"divider": 100
	}, {
		"tag": "Wechselrichter_Status",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32287
	}]
}, {
	"unitId": 9,
	"deviceName": "Krackow_36KTL(COM2-9)",
	"attributesPollPeriod": 86400000,
	"timeseriesPollPeriod": 600000,
	"sendDataOnlyOnChange": false,
	"attributes": [{
		"tag": "Serial Nummer",
		"type": "string",
		"functionCode": 3,
		"objectsCount": 10,
		"address": 32003
	}],
	"timeseries": [{
		"tag": "Wechselrichter_PV1",
		"type": "16int",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32262,
		"divider": 10
	}, {
		"tag": "Wechselrichter_Wirkleistung",
		"type": "32int",
		"functionCode": 3,
		"objectsCount": 2,
		"address": 32290,
		"divider": 1000
	}, {
		"tag": "Wechselrichter_Leistung",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32285,
		"divider": 100
	}, {
		"tag": "Wechselrichter_Status",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32287
	}]
}, {
	"unitId": 10,
	"deviceName": "Krackow_36KTL(COM2-10)",
	"attributesPollPeriod": 86400000,
	"timeseriesPollPeriod": 600000,
	"sendDataOnlyOnChange": false,
	"attributes": [{
		"tag": "Serial Nummer",
		"type": "string",
		"functionCode": 3,
		"objectsCount": 10,
		"address": 32003
	}],
	"timeseries": [{
		"tag": "Wechselrichter_PV1",
		"type": "16int",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32262,
		"divider": 10
	}, {
		"tag": "Wechselrichter_Wirkleistung",
		"type": "32int",
		"functionCode": 3,
		"objectsCount": 2,
		"address": 32290,
		"divider": 1000
	}, {
		"tag": "Wechselrichter_Leistung",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32285,
		"divider": 100
	}, {
		"tag": "Wechselrichter_Status",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32287
	}]
}, {
	"unitId": 11,
	"deviceName": "Krackow_36KTL(COM3-11)",
	"attributesPollPeriod": 86400000,
	"timeseriesPollPeriod": 600000,
	"sendDataOnlyOnChange": false,
        "connectAttemptTimeMs": 5000,
        "connectAttemptCount": 5,
        "waitAfterFailedAttemptsMs": 300000,
	"attributes": [{
		"tag": "Serial Nummer",
		"type": "string",
		"functionCode": 3,
		"objectsCount": 10,
		"address": 32003
	}],
	"timeseries": [{
		"tag": "Wechselrichter_PV1",
		"type": "16int",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32262,
		"divider": 10
	}, {
		"tag": "Wechselrichter_Wirkleistung",
		"type": "32int",
		"functionCode": 3,
		"objectsCount": 2,
		"address": 32290,
		"divider": 1000
	}, {
		"tag": "Wechselrichter_Leistung",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32285,
		"divider": 100
	}, {
		"tag": "Wechselrichter_Status",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32287
	}]
}, {
	"unitId": 12,
	"deviceName": "Krackow_33KTL(COM3-12)",
	"attributesPollPeriod": 86400000,
	"timeseriesPollPeriod": 600000,
	"sendDataOnlyOnChange": false,
        "connectAttemptTimeMs": 5000,
        "connectAttemptCount": 5,
        "waitAfterFailedAttemptsMs": 300000,
	"attributes": [{
		"tag": "Serial Nummer",
		"type": "string",
		"functionCode": 3,
		"objectsCount": 10,
		"address": 32003
	}],
	"timeseries": [{
		"tag": "Wechselrichter_PV1",
		"type": "16int",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32262,
		"divider": 10
	}, {
		"tag": "Wechselrichter_Wirkleistung",
		"type": "32int",
		"functionCode": 3,
		"objectsCount": 2,
		"address": 32290,
		"divider": 1000
	}, {
		"tag": "Wechselrichter_Leistung",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32285,
		"divider": 100
	}, {
		"tag": "Wechselrichter_Status",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32287
	}]
}, {
	"unitId": 13,
	"deviceName": "Krackow_36KTL(COM3-13)",
	"attributesPollPeriod": 86400000,
	"timeseriesPollPeriod": 600000,
	"sendDataOnlyOnChange": false,
        "connectAttemptTimeMs": 5000,
        "connectAttemptCount": 5,
        "waitAfterFailedAttemptsMs": 300000,
	"attributes": [{
		"tag": "Serial Nummer",
		"type": "string",
		"functionCode": 3,
		"objectsCount": 10,
		"address": 32003
	}],
	"timeseries": [{
		"tag": "Wechselrichter_PV1",
		"type": "16int",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32262,
		"divider": 10
	}, {
		"tag": "Wechselrichter_Wirkleistung",
		"type": "32int",
		"functionCode": 3,
		"objectsCount": 2,
		"address": 32290,
		"divider": 1000
	}, {
		"tag": "Wechselrichter_Leistung",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32285,
		"divider": 100
	}, {
		"tag": "Wechselrichter_Status",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32287
	}]
}, {
	"unitId": 14,
	"deviceName": "Krackow_36KTL(COM3-14)",
	"attributesPollPeriod": 86400000,
	"timeseriesPollPeriod": 600000,
	"sendDataOnlyOnChange": false,
        "connectAttemptTimeMs": 5000,
        "connectAttemptCount": 5,
        "waitAfterFailedAttemptsMs": 300000,
	"attributes": [{
		"tag": "Serial Nummer",
		"type": "string",
		"functionCode": 3,
		"objectsCount": 10,
		"address": 32003
	}],
	"timeseries": [{
		"tag": "Wechselrichter_PV1",
		"type": "16int",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32262,
		"divider": 10
	}, {
		"tag": "Wechselrichter_Wirkleistung",
		"type": "32int",
		"functionCode": 3,
		"objectsCount": 2,
		"address": 32290,
		"divider": 1000
	}, {
		"tag": "Wechselrichter_Leistung",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32285,
		"divider": 100
	}, {
		"tag": "Wechselrichter_Status",
		"type": "16uint",
		"functionCode": 3,
		"objectsCount": 1,
		"address": 32287
	}]
}
    ]
  }
}

**Comment by samson0v** [comment]
Hi @redasdasd, it seems that you are using the old version of Gateway. Please, update your gateway (version 3.1) via any accessible for your method.

**Comment by samson0v** [comment]
@redasdasd, any updates?

**Comment by samson0v** [comment]
@redasdasd, did you try?
