### ISSUE TITLE
[BUG] tb-gateway parses the received message as “INF“.

### ISSUE THREAD

**Issue by zlwjzf** [thingsboard/thingsboard-gateway#942]
**Describe the bug**
When I access an MQTT protocol device and receive a message such as "42646174611E010000", the tb-gateway will parse the message as "INF", resulting in my custom "MqttCustomConverter.py" cannot parse the message content accurately

**Comment by zlwjzf** [comment]
I also encountered messages that were parsed into data of type float, but I forgot to save the exact message contents. Please help to provide solutions, thank you!

**Comment by devaskim** [comment]
Is "42646174611E010000" string or number on the broker side? And is this data wrapped in JSON object, e.g. `{ "my_variable": "42646174611E010000" }`?

**Comment by zlwjzf** [comment]
@devaskim Hi, thanks for your attention
1、"42646174611E010000" is a string on the broker side
2、This data is not included in json

**Comment by devaskim** [comment]
As I understand [decoding algorithm](https://github.com/thingsboard/thingsboard-gateway/blob/master/thingsboard_gateway/tb_utility/tb_utility.py#L31) for incoming mqtt data there is no quick fix for your case. 
MQTT Connector tries to interpret data as json-formatted and your string hits [this branch](https://github.com/thingsboard/thingsboard-gateway/blob/master/thingsboard_gateway/tb_utility/tb_utility.py#L36) as number in string.

**Comment by devaskim** [comment]
I think it makes sense to add new configuration parameter for MQTT connector called e.g. `processRawData` to pass data to converter without any encoding.

@imbeacon @samson0v What do you think about this?

**Comment by samson0v** [comment]
Hi @zlwjzf, please, send your MQTT Connector config file.
