### ISSUE TITLE
 Failure to find nl.jk5.netty-mqtt:netty-mqtt:jar:2.0.0TB in https://repo.spring.io/libs-release 

### ISSUE THREAD

**Issue by zhangwonderful** [thingsboard/thingsboard-gateway#96]
When I executed "mvn install " , the console output the following error:
 Failed to execute goal on project gateway: Could not resolve dependencies for project org.thingsboard:gateway:jar:2.0.4-SNAPSHOT: Failure to find nl.jk5.netty-mqtt:netty-mqtt:jar:2.0.0TB in https://repo.spring.io/libs-release was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by mp-loki** [comment]
Please build our version of [netty-mqtt](https://github.com/thingsboard/netty-mqtt) first
