### ISSUE TITLE
[BUG]Modbus connector should be "registerCount" not "objectsCount"

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard-gateway#961]
**Describe the bug**
First, My modbus.json is configured like below, I can only get value of address 0，can't get the value of address 1.
`    "timeseries": [
          {
            "tag": "humidity",
            "type": "16int",
            "functionCode": 3,
            "objectsCount": 1,
            "address": 0
          },
          {
            "tag": "temperature",
            "type": "16int",
            "functionCode": 3,
            "objectsCount": 1,
            "address": 1
          }
        ]
      }
    ]
  }
}`

Then, I replace “objectsCount” to "registerCount", I can get the value of  address 0 adn address 1。
My new modbus.json is configured like below:
`       "timeseries": [
          {
            "tag": "humidity",
            "type": "16int",
            "functionCode": 3,
            "registerCount": 1,
            "address": 0
          },
          {
            "tag": "temperature",
            "type": "16int",
            "functionCode": 3,
            "registerCount": 1,
            "address": 1
          }
        ]
      }
    ]`
The configure in the modbus_connector.py
![image](https://user-images.githubusercontent.com/31084798/197926688-7d5bd2bf-bf2e-4b09-91b8-85f81c447fdd.png)

**Comment by samson0v** [comment]
Hi @qwyinxiang, there is no bug, argument `count` will get from `objectsCount` (see on the first get `OBJECTS_COUNT_PARAMETER`), then if there is no `objectsCount`, will get `registersCount`, if there is no, will get `registerCount`, if there is no, will get 1.

**Comment by qwyinxiang** [comment]
ok, I know, thank you very much.
