### ISSUE TITLE
[HELP] I want gateway to be modbus server, how can I config the modbus.json?

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard-gateway#962]
**Describe the issue**
 The example of modbus.json shows the gateway as modbus slave.
I want to gateway as modbus server, How can I config the modbus.json file?

**Comment by samson0v** [comment]
Hi @qwyinxiang, see the official [documentation](https://thingsboard.io/docs/iot-gateway/config/modbus/#section-master-description-and-configuration-parameters) where describe how to run Gateway as a master and as a slave.

**Comment by qwyinxiang** [comment]
OK。thanks alot。
