### ISSUE TITLE
[HELP] the modbus connector doesn't work well

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard-gateway#966]
My machine is ARMv7 architecture.
 I pulled the latest image and configured the modbus connector, but the docker failed to run properly。
The error logs are showing below:
`/thingsboard_gateway/gateway/tb_gateway_service.py", line 528, in _connect_with_connectors
    if connector_type.lower() != 'grpc' and 'Grpc' not in self._implemented_connectors[
AttributeError: 'NoneType' object has no attribute '__name__'
`

**Comment by samson0v** [comment]
Hi @qwyinxiang, we are investigating this bug and let you know about the result.

**Comment by samson0v** [comment]
Hi @qwyinxiang, try, please, the new Gateway version 3.2 and let us know about the result.

**Comment by samson0v** [comment]
@qwyinxiang, any updates? Can we close the issue?
