### ISSUE TITLE
[HELP] how to draw dynamic diagram svg like thingsboard gateways

### ISSUE THREAD

**Issue by roybiz** [thingsboard/thingsboard-gateway#980]
could  someone tell me  how to draw super cool dynamic diagram like this?   please help ^_^

<img width="987" alt="image" src="https://user-images.githubusercontent.com/8134120/199920536-e37a723b-5d8d-4f3a-b362-041a2f7ce260.png">

**Comment by samson0v** [comment]
Hi @roybiz, you can use [Figma](https://www.figma.com/).

**Comment by roybiz** [comment]
> Hi @roybiz, you can use [Figma](https://www.figma.com/).

Thinks so mouch for your help!
