### ISSUE TITLE
[HELP] OPCUA Server <-> TB Gateway <-> TB

### ISSUE THREAD

**Issue by mica83** [thingsboard/thingsboard-gateway#982]
Hi all,

this is my scenario: I have a OPCUA Server (Prosys) <-> TB Iot Gateway <-> Thingboard.

I'm able connect to OPCUA Server trough TB Gateway and i'm able to visualize on TB Device:  attributes and timeseries.

I'm able also to visualize on TB Device attributes_updates and when i change the value trough TB UI actually the value of the attributes_updates change also into the OPCUA Server.

The problem is when i try to change the value of the attributes_updates on the OPCUA Server the value is not update on Thingboard UI.

![image](https://user-images.githubusercontent.com/19794899/200555014-7355a386-6573-4501-b279-b770deb9996d.png)

![image](https://user-images.githubusercontent.com/19794899/200555257-b733358f-ba6a-448b-b9f1-1d55f0a1faae.png)

Anyone can help me? 

Thanks.

**Comment by devaskim** [comment]
To get updates from OPC server you need to configure `attributes` or/and `timeseries` [section(s)](https://thingsboard.io/docs/iot-gateway/config/opc-ua/#subsection-attributes)

**Comment by devaskim** [comment]
Look at client attributes

**Comment by mica83** [comment]
Yes the client attribute is updated but in the shared attribute the value is old

**Comment by devaskim** [comment]
Maybe I misunderstood what you need, but here is my thoughts
If you change value **directly** on OPC server and want to get that update on TB server, you will need 2 things:
1. Configure `attributes` section of gateway configuration.
2. Observe client attributes of target device to find updates.

If you change value on OPC server **but through TB server** and want to get that update on TB server as well, you will have 2 more step to configure:
3. Configure `attributes_updates` section of gateway configuration.
4. On TB server create shared attribute for target device with the name you specified in step 3 in `attributeOnThingsBoard`

**Comment by mica83** [comment]
Thanks @devaskim it's clear.
I configured all as reported by you.

I'm just saying that if you change value directly on OPC server the client **attributes** of target device is updated but not in **attributes_updates** . So the attributes_updates is not synchronized with attributes though the value of attribute is the same.

**Comment by devaskim** [comment]
It is by design that **attributes_updates ** (TB shared attributes) and **attributes ** (TB client attributes) are not synchronized, it is like independent OUT and IN traffic correspondingly. If you need synchronization you may add this login to Rule TB Chains, i.e. just save client attributes additionally to shared or only to shared

**Comment by imbeacon** [comment]
Hi @mica83 ,

> It is by design that **attributes_updates** (TB shared attributes) and **attributes** (TB client attributes) are not synchronized, it is like independent OUT and IN traffic correspondingly. If you need synchronization you may add this logic to TB Rule Chains, i.e. just save client attributes additionally to shared or only to shared

@devaskim right, there is no more way to handle attribute update from device. Also I recommends to use script filter rule node to save only required attribute to shared, to avoid saving unnecessary attributes twice.
