### ISSUE TITLE
[BUG]The modbus connector will report an error after running for a while

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard-gateway#987]
**Describe the bug**
The modbus connector will report an error after running for a while

**Connector name (If bug in the some connector):**
Modbus Connector

I use the modbus connector. My gateway is V3.1. When I started the gateway, modbus was able to get data, but after running it for a few hours, it was unable to get data, and the following error apears:

![image](https://user-images.githubusercontent.com/31084798/201238920-6f002f3d-af0d-415d-95e0-c61080d8671a.png)

**Comment by samson0v** [comment]
Hi @qwyinxiang, try to use the latest version of Gateway (3.2), there were bug fixes related to Modbus Connector.

**Comment by samson0v** [comment]
@qwyinxiang any updates? Can we close the issue?
